-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 31 „Kosten von Studium und Ausbildung“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 31;
delete from public.abdeckung where thema_id = 31;
delete from public.pruef_einheiten where thema_id = 31;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (9445, 31, 'BAföG-Bedarfssätze und Wohnkostenpauschale automatisch an Lebenshaltungskosten anpassen (Bund)', 'Verhindert, dass das BAföG zwischen Reformen real an Wert verliert (DIW empfiehlt Indexierung); Bund ist zuständig. Zuschüsse wirken laut Studien nur klein positiv auf Studienverlauf, und die Anpassung erhöht das Niveau nicht über den heutigen Stand.', 'gemischt', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'bund', null, true, 'blind'),
  (9446, 31, 'BAföG elternunabhängig und als Vollzuschuss für alle Studierenden (Bund)', 'Mehr Geförderte und keine Schulden würden den Zwang zum Nebenjob deutlich senken; Studien sehen die heutige Bedarfsdeckung als unzureichend. Dagegen: sehr hohe, ungeklärte Kosten und Mitnahme durch Studierende aus wohlhabenden Familien.', 'gemischt', 'https://www.studierendenwerke.de/fileadmin/api/files/210928_fibs_entwicklung_der_einnahmen_von_studierenden_210927_final.pdf', 'bund', null, true, 'blind'),
  (9447, 31, 'Studien- und Bildungskredite ausbauen und Konditionen absichern (Bund)', 'Kredite schließen kurzfristig Finanzierungslücken und sind leicht umsetzbar; sie werden aber nur von wenigen Studierenden genutzt und verlagern die Belastung in Schulden nach dem Abschluss.', 'gemischt', 'https://www.t-online.de/finanzen/beruf-karriere/bildung/id_90444520/60-prozent-mehr-vertraege-zahl-der-studien-neukredite-steigt-sprunghaft-an.html', 'bund', null, true, 'blind'),
  (9448, 31, 'Bundesförderung für Wohnheime von Studierenden und Auszubildenden verstetigen und erhöhen (Bund)', 'Wohnheimplätze sind deutlich günstiger als der freie Markt, es fehlen laut IW über 200.000 Plätze; der Bund finanziert bereits ein Programm. Dagegen: Bau dauert Jahre und erreicht nur einen Teil der Studierenden und Auszubildenden.', 'belegt', 'https://www.iwkoeln.de/presse/iw-nachrichten/philipp-deschermeier-bundesweit-fehlen-mehr-als-200000-wohnheimplaetze-fuer-studenten.html', 'bund', null, true, 'blind'),
  (9449, 31, 'Gesetzliche Mindestausbildungsvergütung anheben (Bund)', 'Hebt die Vergütung genau in Branchen und Regionen mit niedrigen Sätzen (Handwerk, Osten, 7-10 % der Verträge), Bund regelt das im BBiG. Dagegen: Betriebe warnen vor weniger Ausbildungsplätzen; die Wirkung darauf ist noch nicht evaluiert.', 'gemischt', 'https://www.bibb.de/de/pressemitteilung_199964.php', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 31 and id not in (9445, 9446, 9447, 9448, 9449);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (9450, 31, 11, null, 'BAföG soll auskömmlich sein und mit dem KfW-Studienkredit besser abgestimmt werden; Anträge sollen digital und schneller bearbeitet werden.', '{3102}', null, 1, 3, null, 'Bessere Abstimmung mit dem Kredit und schnellere digitale Anträge erleichtern die Finanzierung; „auskömmlich“ ist aber nicht beziffert, daher bleibt die Wirkung auf den Lebensunterhalt unsicher.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9451, 31, 11, null, 'BAföG-Empfänger sollen mehr hinzuverdienen können.', '{3102}', null, 1, 3, null, 'Höhere Hinzuverdienstgrenzen erlauben mehr Einkommen ohne Kürzung und sind leicht umsetzbar; sie setzen aber auf mehr Erwerbsarbeit, die laut DIW das Studium verlängert.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', 'https://www.diw.de/de/diw_01.c.584349.de/bachelor_studierende_mit_nebenjobs_haben_kaum_schlechtere_noten_brauchen_fuer_ihr_studium_aber_etwas_laenger.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9452, 31, 11, null, 'Studienkredit mit fairen Konditionen und festem Zinssatz absichern.', '{3102}', 9447, 1, 3, null, 'Kredite schließen kurzfristig Finanzierungslücken und sind leicht umsetzbar; sie werden aber nur von wenigen Studierenden genutzt und verlagern die Belastung in Schulden nach dem Abschluss.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', 'https://www.t-online.de/finanzen/beruf-karriere/bildung/id_90444520/60-prozent-mehr-vertraege-zahl-der-studien-neukredite-steigt-sprunghaft-an.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9453, 31, 12, null, 'Mindestausbildungsvergütung anheben', '{3101}', 9449, 2, 3, null, 'Hebt die Vergütung genau in Branchen und Regionen mit niedrigen Sätzen (Handwerk, Osten, 7-10 % der Verträge), Bund regelt das im BBiG. Dagegen: Betriebe warnen vor weniger Ausbildungsplätzen; die Wirkung darauf ist noch nicht evaluiert.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', 'https://www.bibb.de/de/pressemitteilung_199964.php', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9454, 31, 12, null, 'BAföG reformieren, sodass die Förderhöhe regelmäßig an die Lebenshaltungskosten angepasst wird', '{3102}', 9445, 2, 3, null, 'Verhindert, dass das BAföG zwischen Reformen real an Wert verliert (DIW empfiehlt Indexierung); Bund ist zuständig. Zuschüsse wirken laut Studien nur klein positiv auf Studienverlauf, und die Anpassung erhöht das Niveau nicht über den heutigen Stand.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9455, 31, 12, null, 'BAföG-Anspruch schrittweise ausweiten, elternunabhängiger machen und zum Vollzuschuss zurückkehren', '{3102}', null, 2, 2, null, 'Schrittweise mehr Anspruchsberechtigte und weniger Darlehensanteil senken den Druck zum Nebenjob; Zuschüsse wirken laut Studien klein positiv. Dagegen: Kosten steigen deutlich, Zeitplan bleibt offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=16', 'https://www.studierendenwerke.de/fileadmin/api/files/210928_fibs_entwicklung_der_einnahmen_von_studierenden_210927_final.pdf', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9456, 31, 12, null, 'Bundesprogramm Junges Wohnen fortsetzen und aufstocken für bezahlbaren Wohnraum für Auszubildende und Studierende', '{3101,3102}', 9448, 2, 3, null, 'Wohnheimplätze sind deutlich günstiger als der freie Markt, es fehlen laut IW über 200.000 Plätze; der Bund finanziert bereits ein Programm. Dagegen: Bau dauert Jahre und erreicht nur einen Teil der Studierenden und Auszubildenden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=16', 'https://www.iwkoeln.de/presse/iw-nachrichten/philipp-deschermeier-bundesweit-fehlen-mehr-als-200000-wohnheimplaetze-fuer-studenten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9457, 31, 12, null, 'Automatische, regelmäßige Erhöhung der BAföG-Wohnkostenpauschale gemäß Mietpreisentwicklung', '{3102}', 9445, 2, 3, null, 'Verhindert, dass das BAföG zwischen Reformen real an Wert verliert (DIW empfiehlt Indexierung); Bund ist zuständig. Zuschüsse wirken laut Studien nur klein positiv auf Studienverlauf, und die Anpassung erhöht das Niveau nicht über den heutigen Stand.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=21', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9458, 31, 12, null, 'Mittel für Studierenden- und Azubi-Wohnheime verstetigen und erhöhen, damit WG-Zimmer höchstens 400 Euro kosten', '{3102,3101}', 9448, 2, 3, null, 'Wohnheimplätze sind deutlich günstiger als der freie Markt, es fehlen laut IW über 200.000 Plätze; der Bund finanziert bereits ein Programm. Dagegen: Bau dauert Jahre und erreicht nur einen Teil der Studierenden und Auszubildenden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=21', 'https://www.iwkoeln.de/presse/iw-nachrichten/philipp-deschermeier-bundesweit-fehlen-mehr-als-200000-wohnheimplaetze-fuer-studenten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9459, 31, 12, null, 'Kostenfreie Ausbildungen in Gesundheitsfachberufen und faire Vergütung für alle Auszubildenden', '{3101}', null, 2, 2, null, 'Ohne Schulgeld entfällt in Gesundheitsfachberufen eine direkte Kostenlast, ähnlich wie zuvor in der Pflege. Dagegen: betrifft nur einige Berufe, die Schulfinanzierung liegt teils bei den Ländern; Wirkung kaum untersucht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=32', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9460, 31, 12, null, 'Bundesweit vergünstigtes Deutschlandticket für Auszubildende und Studierende', '{3101}', null, 1, 2, null, 'Ein günstigeres Ticket entlastet Auszubildende bei Fahrtkosten und fördert laut Evaluation Teilhabe; es lindert aber nur Kosten. Die Finanzierung muss mit den Ländern vereinbart werden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=35', 'https://www.bmv.de/SharedDocs/DE/Pressemitteilungen/2026/027-schnieder-evaluation-deutschlandticket.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9461, 31, 12, null, 'Steuer- und abgabenfreier Führerscheinzuschuss des Arbeitgebers für Auszubildende', '{3101}', null, 1, 3, null, 'Ein steuerfreier Zuschuss erleichtert Auszubildenden auf dem Land die Mobilität und ist einfach umzusetzen; er hängt aber vom Arbeitgeber ab und ist eine einmalige Hilfe.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=36', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9462, 31, 13, null, 'Mindestausbildungsvergütung deutlich anheben, damit Auszubildende selbstständig leben können', '{3101}', 9449, 2, 3, null, 'Hebt die Vergütung genau in Branchen und Regionen mit niedrigen Sätzen (Handwerk, Osten, 7-10 % der Verträge), Bund regelt das im BBiG. Dagegen: Betriebe warnen vor weniger Ausbildungsplätzen; die Wirkung darauf ist noch nicht evaluiert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', 'https://www.bibb.de/de/pressemitteilung_199964.php', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9463, 31, 13, null, 'Auszubildendenwerke nach Vorbild der Studierendenwerke fördern, mit Wohnheimen und Beratung für Auszubildende', '{3101}', null, 2, 2, null, 'Auszubildendenwerke bündeln günstiges Wohnen und Beratung; Wohnheimplätze für Auszubildende fehlen (rund 20.000). Dagegen: Aufbau der Strukturen dauert, Bund kann nur fördern; Wirkung kaum untersucht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9464, 31, 13, null, 'BAföG existenzsichernd machen, Bedarfssätze und Freibeträge regelmäßig an Lebenshaltungskosten anpassen', '{3102}', 9445, 2, 3, null, 'Verhindert, dass das BAföG zwischen Reformen real an Wert verliert (DIW empfiehlt Indexierung); Bund ist zuständig. Zuschüsse wirken laut Studien nur klein positiv auf Studienverlauf, und die Anpassung erhöht das Niveau nicht über den heutigen Stand.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9465, 31, 13, null, 'Bau und Sanierung von Wohnheimen über das Programm Junges Wohnen weiter fördern, Auszubildende stärker einbeziehen', '{3102}', 9448, 2, 3, null, 'Wohnheimplätze sind deutlich günstiger als der freie Markt, es fehlen laut IW über 200.000 Plätze; der Bund finanziert bereits ein Programm. Dagegen: Bau dauert Jahre und erreicht nur einen Teil der Studierenden und Auszubildenden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.iwkoeln.de/presse/iw-nachrichten/philipp-deschermeier-bundesweit-fehlen-mehr-als-200000-wohnheimplaetze-fuer-studenten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9466, 31, 14, null, 'BAföG zu einem elternunabhängigen Baukasten-System weiterentwickeln, damit die Studienwahl nicht vom Elternhaus abhängt.', '{3102}', 9446, 2, 1, null, 'Mehr Geförderte und keine Schulden würden den Zwang zum Nebenjob deutlich senken; Studien sehen die heutige Bedarfsdeckung als unzureichend. Dagegen: sehr hohe, ungeklärte Kosten und Mitnahme durch Studierende aus wohlhabenden Familien.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=10', 'https://www.studierendenwerke.de/fileadmin/api/files/210928_fibs_entwicklung_der_einnahmen_von_studierenden_210927_final.pdf', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9467, 31, 14, null, 'Bildungskreditprogramm kurzfristig stärken und ausbauen.', '{3102}', 9447, 1, 3, null, 'Kredite schließen kurzfristig Finanzierungslücken und sind leicht umsetzbar; sie werden aber nur von wenigen Studierenden genutzt und verlagern die Belastung in Schulden nach dem Abschluss.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=10', 'https://www.t-online.de/finanzen/beruf-karriere/bildung/id_90444520/60-prozent-mehr-vertraege-zahl-der-studien-neukredite-steigt-sprunghaft-an.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9468, 31, 14, null, 'Azubi-Stipendien ausbauen.', '{3101}', null, 1, 3, null, 'Stipendien entlasten einzelne Auszubildende und sind über Bundesprogramme leicht auszubauen; sie erreichen aber nur wenige und ändern die Vergütungsunterschiede nicht.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=9', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9469, 31, 15, null, 'BAföG-Empfängern wird bei einer Geburt während Ausbildung oder Studium die Rückzahlung nach erfolgreichem Abschluss erlassen.', '{3102}', null, 1, 3, null, 'Der Erlass entlastet Studierende mit Kind nach dem Abschluss und ist leicht umsetzbar; er betrifft wenige und hilft nicht beim laufenden Lebensunterhalt.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=149', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9470, 31, 16, null, 'Gesetzliche Mindestausbildungsvergütung in Höhe von 80 % der durchschnittlichen tariflichen Vergütung der Branchen.', '{3101}', 9449, 2, 3, null, 'Hebt die Vergütung genau in Branchen und Regionen mit niedrigen Sätzen (Handwerk, Osten, 7-10 % der Verträge), Bund regelt das im BBiG. Dagegen: Betriebe warnen vor weniger Ausbildungsplätzen; die Wirkung darauf ist noch nicht evaluiert.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', 'https://www.bibb.de/de/pressemitteilung_199964.php', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9471, 31, 16, null, 'Unternehmen sollen sich finanziell an bezahlbaren Wohnheimplätzen für Auszubildende beteiligen müssen.', '{3101}', null, 1, 1, null, 'Eine Beteiligung der Betriebe könnte Wohnheimplätze für Auszubildende auf dem Land finanzieren. Dagegen: Eine Pflichtabgabe ist rechtlich heikel, Ausgestaltung und Wirkung sind offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9472, 31, 16, null, 'Kostenloses Nahverkehrsticket für Auszubildende.', '{3101}', null, 1, 1, null, 'Ein kostenloses Ticket spart Auszubildenden Fahrtkosten und fördert laut Evaluation des Deutschlandtickets Teilhabe; es lindert aber nur Kosten. Für mehrere große Gruppen sofort kostenlos ist die Finanzierung mit den Ländern ungeklärt.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=36', 'https://www.bmv.de/SharedDocs/DE/Pressemitteilungen/2026/027-schnieder-evaluation-deutschlandticket.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9473, 31, 16, null, 'BAföG für alle: elternunabhängig, existenzsichernd, als Vollzuschuss, regelmäßig an die Lebenshaltungskosten angepasst.', '{3102}', 9446, 2, 1, null, 'Mehr Geförderte und keine Schulden würden den Zwang zum Nebenjob deutlich senken; Studien sehen die heutige Bedarfsdeckung als unzureichend. Dagegen: sehr hohe, ungeklärte Kosten und Mitnahme durch Studierende aus wohlhabenden Familien.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=40', 'https://www.studierendenwerke.de/fileadmin/api/files/210928_fibs_entwicklung_der_einnahmen_von_studierenden_210927_final.pdf', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9474, 31, 16, null, 'Studierendenwerke ausreichend finanzieren, damit Semesterbeiträge, Mensapreise und Wohnkosten sinken.', '{3102}', null, 1, 2, null, 'Mehr Geld für Studierendenwerke senkt Beiträge, Mensa- und Wohnkosten etwas; die Entlastung je Person ist aber gering. Die Grundfinanzierung liegt bei den Ländern, der Bund kann nur über Programme beitragen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=40', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9475, 31, 18, null, 'Ausbildungsvergütung soll für ein menschenwürdiges Leben reichen; der Staat schließt Lücken über Anreize mit Orientierung am Mindestlohn.', '{3101}', null, 2, 1, null, 'Eine Vergütung nahe am Mindestlohn würde niedrige Ausbildungsvergütungen deutlich anheben. Dagegen: Wie der Staat Lücken über Anreize schließt, bleibt unbestimmt, die Finanzierung ist ungeklärt.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=117', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9476, 31, 18, null, 'BAföG-Sätze an ortsabhängige Lebenshaltungskosten anpassen und unabhängig von der Ausbildungsart gewähren.', '{3102}', null, 2, 2, null, 'Ortsabhängige Sätze treffen die großen Mietunterschiede zwischen Hochschulstädten; ähnliche Staffelungen gibt es beim Wohngeld. Dagegen: mehr Verwaltungsaufwand und kaum Erfahrung mit dem BAföG.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=117', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9477, 31, 18, null, 'Teilzeit-BAföG einführen, Anspruchsvoraussetzungen senken und Berechtigung erst nach der Auszahlung prüfen.', '{3102}', null, 2, 2, null, 'Teilzeit-BAföG und niedrigere Hürden erreichen Studierende, die wegen Arbeit oder Pflege heute herausfallen; schnellere Auszahlung hilft. Dagegen: Prüfung erst nach Auszahlung birgt Rückforderungen; Wirkung kaum untersucht.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=117', null, 'offen', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (9445, 31),
  (9446, 31),
  (9447, 31),
  (9448, 31),
  (9449, 31),
  (9450, 31),
  (9451, 31),
  (9455, 31),
  (9459, 31),
  (9460, 31),
  (9461, 31),
  (9463, 31),
  (9468, 31),
  (9469, 31),
  (9471, 31),
  (9472, 31),
  (9474, 31),
  (9475, 31),
  (9476, 31),
  (9477, 31);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (31, 11, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 12, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 13, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 14, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 15, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 16, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}'),
  (31, 17, null, 'keine', 'Bildungskapitel (S. 22–26) und Fundstellen S. 23, 25 gelesen. Nur Feststellungen (Wohnraummangel für Studenten und Auszubildende) und die Aussage, eine BAföG-Reform und ein Hochschulsozialpakt seien dringend nötig; keine konkrete Zusage.', '2026-10-08', true, '{3101,3102}'),
  (31, 18, null, 'massnahmen', null, '2026-10-08', true, '{3101,3102}');

commit;
