-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 28 „Sexismus und Benachteiligung von Frauen“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 28;
delete from public.abdeckung where thema_id = 28;
delete from public.pruef_einheiten where thema_id = 28;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (9490, 28, 'Mehr nicht übertragbare Elterngeldmonate je Elternteil im bisherigen Umfang (Bund)', 'Reservierte Partnermonate erhöhen die Elternzeit von Vätern deutlich; Studien aus Deutschland und Québec zeigen danach dauerhaft mehr Haus- und Sorgearbeit der Väter, in Schweden fand sich kein solcher Effekt. Umbau im bestehenden Elterngeld ohne große Mehrkosten.', 'belegt', 'https://www.rwi-essen.de/publikationen/zitationsansicht/gemischt/detail/fathers-parental-leave-taking-childcare-involvement-and-1043', 'bund', null, true, 'blind'),
  (9491, 28, 'Elterngeld verlängern mit mehr nicht übertragbaren Monaten je Elternteil (Bund)', 'Reservierte Monate für jeden Elternteil verschieben laut Québec- und Deutschland-Studien die Hausarbeit dauerhaft zu den Vätern. Die Verlängerung des Bezugs verursacht aber erhebliche Mehrkosten und braucht Finanzierung.', 'belegt', 'https://ideas.repec.org/a/ucp/jlabec/doi10.1086-703115.html', 'bund', null, true, 'blind'),
  (9492, 28, 'Bezahlte Freistellung des zweiten Elternteils direkt nach der Geburt (Bund)', 'Kurze Partnerfreistellung wird stark genutzt und erleichtert Müttern den Wiedereinstieg; in Spanien änderte sie die längerfristige Aufteilung aber kaum. Gesetzlich einfach, umlage- oder steuerfinanziert machbar.', 'gemischt', 'https://www.iza.org/publications/dp/10865', 'bund', null, true, 'blind'),
  (9493, 28, 'Elterngeld bei Teilzeit und Partnerschaftsbonus verbessern (Bund)', 'ElterngeldPlus und Partnerschaftsbonus werden zunehmend genutzt, der Bonus aber nur von einem kleinen Teil der Väter; eine messbare Wirkung auf Aufteilung oder Rückkehr aus der Teilzeit ist kaum untersucht. Leicht im bestehenden Gesetz umsetzbar.', 'offen', 'https://www.bundestag.de/webarchiv/textarchiv/2018/kw08-de-elterngeld-plus-542316', 'bund', null, true, 'blind'),
  (9494, 28, 'Flexible Arbeitszeiten, Homeoffice und betriebliche Kinderbetreuung fördern (Bund)', 'Homeoffice erhöht laut Paneldaten die vertraglichen Stunden von Müttern; Appelle an Arbeitgeber und Steueranreize für Betriebskitas bleiben aber unverbindlich, ihre Wirkung auf Teilzeit ist offen.', 'gemischt', 'https://www.zew.de/PU80770', 'bund', null, true, 'blind'),
  (9495, 28, 'Haushaltsnahe Dienstleistungen staatlich fördern (Bund)', 'Zuschüsse oder Steuerabzug entlasten Haushalte bei Routinearbeit, verändern aber nicht die Aufteilung zwischen Partnern; Evaluationen in Belgien und Schweden können Effekte für die Nutzenden nicht sicher belegen. Ein neues Budget braucht Finanzierung.', 'offen', 'https://www.tillvaxtanalys.se/en-GB/publikationer/pm/pm/branschspecifikaskattelattnadereninternationelljamforelse.4573.html', 'bund', null, true, 'blind'),
  (9496, 28, 'Geschlechterrollen in Kita, Schule, Berufsorientierung und Fachkräfteausbildung thematisieren (Land)', 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'gemischt', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'land', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 28 and id not in (9490, 9491, 9492, 9493, 9494, 9495, 9496);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (9497, 28, 11, null, 'Elterngeld verbessern und den Partnerschaftsbonus für gleichzeitige vollzeitnahe Teilzeit beider Eltern weiterentwickeln.', '{2801}', 9493, 1, 3, null, 'ElterngeldPlus und Partnerschaftsbonus werden zunehmend genutzt, der Bonus aber nur von einem kleinen Teil der Väter; eine messbare Wirkung auf Aufteilung oder Rückkehr aus der Teilzeit ist kaum untersucht. Leicht im bestehenden Gesetz umsetzbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=62', 'https://www.bundestag.de/webarchiv/textarchiv/2018/kw08-de-elterngeld-plus-542316', 'offen', '2026-10-08', false, true, 'blind'),
  (9498, 28, 11, null, 'Steuerliche Absetzbarkeit haushaltsnaher Dienstleistungen verbessern.', '{2801}', 9495, 1, 2, null, 'Zuschüsse oder Steuerabzug entlasten Haushalte bei Routinearbeit, verändern aber nicht die Aufteilung zwischen Partnern; Evaluationen in Belgien und Schweden können Effekte für die Nutzenden nicht sicher belegen. Ein neues Budget braucht Finanzierung.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=15', 'https://www.tillvaxtanalys.se/en-GB/publikationer/pm/pm/branschspecifikaskattelattnadereninternationelljamforelse.4573.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9499, 28, 12, null, 'Elterngeld ausbauen: je sechs nicht übertragbare Monate pro Elternteil plus sechs frei verteilbare Monate.', '{2801}', 9491, 3, 2, null, 'Reservierte Monate für jeden Elternteil verschieben laut Québec- und Deutschland-Studien die Hausarbeit dauerhaft zu den Vätern. Die Verlängerung des Bezugs verursacht aber erhebliche Mehrkosten und braucht Finanzierung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=26', 'https://ideas.repec.org/a/ucp/jlabec/doi10.1086-703115.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9500, 28, 12, null, 'Familienstartzeit: bezahlte Freistellung für Väter oder Partnerinnen und Partner in den ersten zwei Wochen nach der Geburt.', '{2801}', 9492, 2, 3, null, 'Kurze Partnerfreistellung wird stark genutzt und erleichtert Müttern den Wiedereinstieg; in Spanien änderte sie die längerfristige Aufteilung aber kaum. Gesetzlich einfach, umlage- oder steuerfinanziert machbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=26', 'https://www.iza.org/publications/dp/10865', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9501, 28, 12, null, 'Jährliches Familienbudget für Alltagshelfer, das haushaltsnahe Dienstleistungen direkt fördert.', '{2801}', 9495, 1, 2, null, 'Zuschüsse oder Steuerabzug entlasten Haushalte bei Routinearbeit, verändern aber nicht die Aufteilung zwischen Partnern; Evaluationen in Belgien und Schweden können Effekte für die Nutzenden nicht sicher belegen. Ein neues Budget braucht Finanzierung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=26', 'https://www.tillvaxtanalys.se/en-GB/publikationer/pm/pm/branschspecifikaskattelattnadereninternationelljamforelse.4573.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9502, 28, 12, null, 'Allgemeines Gleichbehandlungsgesetz modernisieren und Antidiskriminierungsberatung ausbauen, für wirksameren Schutz vor Diskriminierung.', '{2804}', null, 1, 3, null, 'Mehr Beratung und ein reformiertes AGG können Betroffenen den Beschwerdeweg erleichtern; die Zusage bleibt allgemein und nennt sexuelle Belästigung am Arbeitsplatz nicht ausdrücklich.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=41', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9503, 28, 13, null, 'Elternzeit so gestalten, dass jeder Elternteil mindestens ein Drittel nutzen kann, als Anreiz zu partnerschaftlicher Aufteilung.', '{2801}', 9490, 3, 3, null, 'Reservierte Partnermonate erhöhen die Elternzeit von Vätern deutlich; Studien aus Deutschland und Québec zeigen danach dauerhaft mehr Haus- und Sorgearbeit der Väter, in Schweden fand sich kein solcher Effekt. Umbau im bestehenden Elterngeld ohne große Mehrkosten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=82', 'https://www.rwi-essen.de/publikationen/zitationsansicht/gemischt/detail/fathers-parental-leave-taking-childcare-involvement-and-1043', 'belegt', '2026-10-08', false, true, 'blind'),
  (9504, 28, 13, null, 'Brückenteilzeit und Rückkehrrecht in Vollzeit ausweiten und individueller gestalten.', '{2802}', null, 2, 3, null, 'Ein breiteres Rückkehrrecht in Vollzeit setzt direkt an ungewollter Teilzeit an, da die heutige Brückenteilzeit viele kleine Betriebe ausnimmt und selten genutzt wird; eine Wirkungsevaluation fehlt. Änderung im Teilzeitgesetz.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=69', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9505, 28, 13, null, 'Minijobs schrittweise in sozialversicherungspflichtige Beschäftigung überführen, weil sie für Frauen zur Teilzeitfalle werden.', '{2802}', null, 2, 2, null, 'Minijobs verstärken mit Splitting und Mitversicherung geringe Stunden verheirateter Frauen; ihre Überführung würde diesen Anreiz abbauen. Wie viele Stunden tatsächlich steigen, ist unsicher; der schrittweise Umbau braucht Zeit.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=69', 'https://www.bertelsmann-stiftung.de/de/themen/aktuelle-meldungen/2026/maerz/nach-kinderphase-ehegattensplitting-bremst-beschaeftigung-von-frauen-aus', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9506, 28, 13, 'ST', 'Schulungen in Kitas für geschlechterneutrale Erziehung, um stereotype Rollenbilder früh abzubauen', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=58', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9507, 28, 14, null, 'Volles Elterngeld soll ausgezahlt werden, wenn beide Partner mindestens vier Monate nehmen; die übrigen Monate frei aufteilbar.', '{2801}', 9490, 3, 3, null, 'Reservierte Partnermonate erhöhen die Elternzeit von Vätern deutlich; Studien aus Deutschland und Québec zeigen danach dauerhaft mehr Haus- und Sorgearbeit der Väter, in Schweden fand sich kein solcher Effekt. Umbau im bestehenden Elterngeld ohne große Mehrkosten.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=30', 'https://www.rwi-essen.de/publikationen/zitationsansicht/gemischt/detail/fathers-parental-leave-taking-childcare-involvement-and-1043', 'belegt', '2026-10-08', false, true, 'blind'),
  (9508, 28, 14, null, 'Arbeitszeitgesetz abschaffen, um flexible Arbeitszeiten, Teilzeit, Jobsharing und Homeoffice für Frauen wie Männer zu ermöglichen.', '{2802}', null, 1, 1, null, 'Flexiblere Arbeitszeiten können Vereinbarkeit erleichtern, ein Bezug zur Teilzeitfalle ist aber kaum belegt. Eine ersatzlose Abschaffung widerspräche der EU-Arbeitszeitrichtlinie (Höchstarbeitszeit, Ruhezeiten); nötig wäre eine Ersatzregelung.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=31', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9509, 28, 14, 'BE', 'Eltern früh über tradierte Rollenbilder informieren; Kitas sollen geschlechtersensible Erziehung leben.', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=81', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9510, 28, 15, null, 'Erziehungsgeld für die Eigenbetreuung in den ersten drei Lebensjahren sowie Hilfen beim beruflichen Wiedereinstieg.', '{2802}', null, 1, 1, null, 'Hilfen zum Wiedereinstieg setzen an langer Teilzeit an; ein Erziehungsgeld für Eigenbetreuung senkte in Westdeutschland aber leicht die Erwerbstätigkeit von Müttern. Ein Bundes-Betreuungsgeld wurde 2015 mangels Bundeskompetenz verworfen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=21', 'https://jhr.uwpress.org/node/11990', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9511, 28, 15, null, 'Arbeitgeber sollen Telearbeit, flexible Arbeitszeiten und Betriebskindergärten anbieten, damit Eltern Betreuung und Arbeit vereinbaren können.', '{2802}', 9494, 1, 3, null, 'Homeoffice erhöht laut Paneldaten die vertraglichen Stunden von Müttern; Appelle an Arbeitgeber und Steueranreize für Betriebskitas bleiben aber unverbindlich, ihre Wirkung auf Teilzeit ist offen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=148', 'https://www.zew.de/PU80770', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9512, 28, 16, null, 'Einführung eines bezahlten Elternschutzes von 28 Tagen für den zweiten Elternteil ab Geburt, um Sorge- und Erwerbsarbeit partnerschaftlich aufzuteilen.', '{2801}', 9492, 2, 3, null, 'Kurze Partnerfreistellung wird stark genutzt und erleichtert Müttern den Wiedereinstieg; in Spanien änderte sie die längerfristige Aufteilung aber kaum. Gesetzlich einfach, umlage- oder steuerfinanziert machbar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', 'https://www.iza.org/publications/dp/10865', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9513, 28, 16, null, 'Ausdrückliches Rückkehrrecht auf den gleichen oder einen gleichwertigen Arbeitsplatz nach der Elternzeit.', '{2802}', null, 1, 3, null, 'Ein Rückkehrrecht auf denselben oder gleichwertigen Arbeitsplatz erleichtert den Wiedereinstieg, schreibt aber weitgehend fest, was EU-Recht (Richtlinie 2019/1158) bereits vorsieht; zur Wirkung gibt es kaum Studien.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9514, 28, 16, null, 'Rechtsanspruch auf eine Vollzeitstelle und auf familienfreundliche Schichten.', '{2802}', null, 2, 2, null, 'Ein Anspruch auf Vollzeit und familienfreundliche Schichten setzt direkt an ungewollter Teilzeit an; Belege zur Wirkung fehlen. Ein allgemeiner Anspruch greift stark in betriebliche Planung ein und braucht Ausnahmen, daher aufwendig.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=27', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9515, 28, 16, null, 'Arbeitsschutzgesetz um Gewalt und sexuelle Belästigung ergänzen, damit das Gesetz gegen Gewalt und Belästigung in der Arbeitswelt in der Praxis ankommt.', '{2804}', null, 2, 3, null, 'Belästigung als Pflicht im Arbeitsschutz (Gefährdungsbeurteilung, Aufsicht) macht Prävention und Beschwerdewege verbindlicher, wo 40 % die Beschwerdestelle nicht kennen; die Wirkung dieses Wegs ist kaum evaluiert. Einfache Gesetzesänderung.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=47', 'https://www.antidiskriminierungsstelle.gov.de/SharedDocs/pressemitteilungen/EN/2019/20191025_Study_sexual_harrasment.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9516, 28, 16, 'BE', 'Aufklärung und Weiterbildung, besonders in Schulen, über Sexismus, häusliche Gewalt und stereotype Rollenbilder.', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=214', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9517, 28, 16, 'MV', 'Berufsorientierung ohne Geschlechterstereotype; Girls'' Day und Boys'' Day in Klasse 9 verpflichtend.', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=15', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9518, 28, 16, 'MV', 'Genderkompetenz verbindlich in der Ausbildung von Lehrkräften und pädagogischen Fachkräften verankern, um Rollenmuster aufzubrechen.', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=14', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9519, 28, 16, 'ST', 'Kinder und Jugendliche früh für alltägliche Aufgaben sensibilisieren, damit Sorgearbeit besser verteilt wird.', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=22', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9520, 28, 18, null, 'Achtwöchiger Vaterschaftsurlaub und dreimonatige Mindest-Elternzeit je Elternteil, um Familienarbeit partnerschaftlich aufzuteilen', '{2801}', 9491, 3, 2, null, 'Reservierte Monate für jeden Elternteil verschieben laut Québec- und Deutschland-Studien die Hausarbeit dauerhaft zu den Vätern. Die Verlängerung des Bezugs verursacht aber erhebliche Mehrkosten und braucht Finanzierung.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=149', 'https://ideas.repec.org/a/ucp/jlabec/doi10.1086-703115.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9521, 28, 18, null, 'Ehegattensplitting abschaffen und jedem Elternteil einen eigenen Elterngeld-Anspruch auf sieben Monate geben', '{2801}', null, 3, 2, null, 'Eigene Elterngeldmonate je Elternteil verschieben belegt Sorgearbeit zu Vätern; das Splitting bremst laut Studien die Stundenausweitung von Ehefrauen. Eine Abschaffung muss aber das Existenzminimum des Partners sichern und betrifft Bestandsehen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=52', 'https://www.bertelsmann-stiftung.de/de/themen/aktuelle-meldungen/2026/maerz/nach-kinderphase-ehegattensplitting-bremst-beschaeftigung-von-frauen-aus', 'belegt', '2026-10-08', false, true, 'blind'),
  (9522, 28, 18, null, 'Teilzeit-Elterngeld attraktiver gestalten und fördern', '{2802}', 9493, 1, 3, null, 'ElterngeldPlus und Partnerschaftsbonus werden zunehmend genutzt, der Bonus aber nur von einem kleinen Teil der Väter; eine messbare Wirkung auf Aufteilung oder Rückkehr aus der Teilzeit ist kaum untersucht. Leicht im bestehenden Gesetz umsetzbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=149', 'https://www.bundestag.de/webarchiv/textarchiv/2018/kw08-de-elterngeld-plus-542316', 'offen', '2026-10-08', false, true, 'blind'),
  (9523, 28, 18, null, 'Flexible Arbeitszeitmodelle ausbauen und betriebliche Kinderbetreuung steuerlich fördern, um Beruf und Familie besser zu vereinbaren', '{2802}', 9494, 1, 3, null, 'Homeoffice erhöht laut Paneldaten die vertraglichen Stunden von Müttern; Appelle an Arbeitgeber und Steueranreize für Betriebskitas bleiben aber unverbindlich, ihre Wirkung auf Teilzeit ist offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=151', 'https://www.zew.de/PU80770', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9524, 28, 18, 'BE', 'Pflichtfach Lebenskompetenz an Schulen (Pilotschulen), das auch die kritische Auseinandersetzung mit Rollenbildern behandelt', '{2803}', 9496, 1, 3, null, 'Ein Schulexperiment in Indien veränderte Rollenbilder messbar und dauerhaft; Evaluationen hier messen meist Zufriedenheit, die Wirkung auf Erwartungen an Mütter ist offen. Liegt in Landeszuständigkeit und ist günstig umsetzbar.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=48', 'https://www.aeaweb.org/doi/10.1257/aer.20201112', 'gemischt', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (9490, 28),
  (9491, 28),
  (9492, 28),
  (9493, 28),
  (9494, 28),
  (9495, 28),
  (9496, 28),
  (9502, 28),
  (9504, 28),
  (9505, 28),
  (9508, 28),
  (9510, 28),
  (9513, 28),
  (9514, 28),
  (9515, 28),
  (9521, 28);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (28, 11, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 11, 'BE', 'keine', 'Inhaltsverzeichnis, Kapitel ''Gewalt gegen Frauen'' (S. 11), ''Chancen bieten'' (S. 102-103) und ''Starke Familien'' (S. 108-109) gelesen. Nichts zu Rollenbildern oder widersprüchlichen Erwartungen an Mütter; Vereinbarkeit und Kita-Ausbau gehören zu anderen Ursachen.', '2026-10-08', true, '{2803}'),
  (28, 11, 'MV', 'keine', 'Inhaltsverzeichnis, Kapitel Familienland (S. 96-98), Gesundheit von Frauen (Gesundheitskapitel) und alle Textstellen zu Frauen, Mütter, Vereinbarkeit, Rollen per Volltextsuche gelesen; nichts zu Rollenbildern oder Erwartungen an Mütter (2803).', '2026-10-08', true, '{2803}'),
  (28, 11, 'ST', 'keine', 'Kapitel Soziale Gerechtigkeit und Familie (S. 30-33), Frühkindliche Bildung (S. 48-50) und Justiz (S. 57-58) gelesen; nichts zu Rollenbildern oder Erwartungen an Mütter. Nur Wahlfreiheit, Vereinbarkeit, Chancengleichheit in Führungspositionen und Sorgearbeit (andere Ursachen).', '2026-10-08', true, '{2803}'),
  (28, 12, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 12, 'BE', 'keine', 'Inhaltsverzeichnis, Kapitel Gute Arbeit (S. 8), Zusammenleben, Familie und Gleichstellung (S. 47-48) und Fundstelle S. 11 gelesen; keine Zusage zu Rollenbildern oder Erwartungen an Mütter, nur Parität, Gleichstellungsgesetz, Pay Gap, Wiedereinstieg.', '2026-10-08', true, '{2803}'),
  (28, 12, 'MV', 'keine', 'Kapitel Gleichstellung (S. 38) und Leitsatz S. 6 gelesen. Zu Rollenbildern/Erwartungen an Mütter (2803) nur Rückblick (Führungspositionen in Landesverwaltung ergriffen) und allgemeine Ziele; Gewalt und Frauenhäuser gehören zu Sicherheit.', '2026-10-08', true, '{2803}'),
  (28, 12, 'ST', 'keine', 'Kapitel Gleichstellung auf dem Arbeitsmarkt (S. 9), Vielfalt/Diskriminierung (S. 36), Fundstelle S. 27 gelesen: nichts zu Rollenbildern oder Erwartungen an Mütter; Sorgearbeit-Zusagen (S. 9) gehören zu 2801, nicht Landesursache.', '2026-10-08', true, '{2803}'),
  (28, 13, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 13, 'BE', 'keine', 'Kapitel 4.1 Strukturelle Gleichstellung (S. 130-133), Gleichstellung am Arbeitsplatz (S. 109-110) und Fundstelle S. 183 gelesen; nichts zu Rollenbildern oder Erwartungen an Mütter. S. 183 meint Familienbildung/Sprach-Kitas.', '2026-10-08', true, '{2803}'),
  (28, 13, 'MV', 'keine', 'Kapitel 13 (S. 80-85) und Fundstelle S. 81 gelesen. Rollenbilder werden nur als Lagebeschreibung genannt; keine Zusage, die Rollenbilder oder Erwartungen an Mütter angeht. Care-Arbeit/Gleichstellung (S. 83-85) zählt nicht zu 2803.', '2026-10-08', true, '{2803}'),
  (28, 13, 'ST', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 14, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 14, 'BE', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 14, 'MV', 'keine', 'Kapitel Familie (S. 37) und Fundstelle gelesen; Rollenbilder werden nur als Ziel genannt (sollen aufgebrochen werden), ohne Handlungszusage. Sonst nichts zu Müttern, Rollenerwartungen, Teilzeit oder Belästigung im Landesprogramm gefunden.', '2026-10-08', true, '{2803}'),
  (28, 14, 'ST', 'keine', 'Kapitel Gleichstellung und Frauenpolitik (S. 38-39) und Familien (S. 24) gelesen; nur Bekenntnis zu gleichberechtigter Erziehungs- und Erwerbsarbeit und allgemeine Weiterentwicklung des Frauenfördergesetzes, nichts zu Rollenbildern oder Erwartungen an Mütter.', '2026-10-08', true, '{2803}'),
  (28, 15, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 15, 'BE', 'keine', 'Erfasste Stellen (S. 59) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-08', true, '{2803}'),
  (28, 15, 'MV', 'keine', 'Kapitel Familienland MV (S. 17-21) und Fundstellen S. 17, 19, 26 gelesen. Nur Leitbilder (Wahlfreiheit, positives Familienbild) und Kritik an Rollenbildern in der Schule; keine konkrete Zusage zu Rollenbildern oder Erwartungen an Mütter.', '2026-10-08', true, '{2803}'),
  (28, 15, 'ST', 'keine', 'Kapitel I. Familie und Kinder (S. 10-19), Gleichberechtigung (S. 94), Girls and Boys Day (S. 63) und Fundstelle S. 17 gelesen; nichts setzt an widersprüchlichen Erwartungen an Mütter an. S. 17 ist Kritik, keine Zusage.', '2026-10-08', true, '{2803}'),
  (28, 16, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 16, 'BE', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 16, 'MV', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 16, 'ST', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 17, null, 'keine', 'Kapitel Frauenrechte statt Gender-Ideologie (S. 33-34), Arbeit/Löhne (S. 18) und Fundstellen S. 5, 6, 15, 16, 22 gelesen. Nur Kita-, Ferienbetreuung und Frauenhäuser (R2: andere Themen) sowie Lagebeschreibung zu Sorgearbeit; nichts zu Aufteilung, Teilzeit-Wiedereinstieg, Rollenbildern oder Belästigung.', '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 17, 'BE', 'keine', 'Soziales/Familie (S. 10-13), Bildung, Sport (S. 27), Wirtschaft, Sicherheit/Frauenhäuser sowie Volltextsuche (Frauen, Mütter, Gleichstellung, Rollen, Vereinbarkeit) gelesen; nichts zu Rollenbildern oder Erwartungen an Mütter. Frauenhäuser gehören zu Sicherheit (R2).', '2026-10-08', true, '{2803}'),
  (28, 17, 'MV', 'keine', 'Kapitel Familien (S. 11-12), Gute Arbeit (S. 19) und Frauenschutz (S. 69) gelesen; nichts zu Rollenbildern oder Erwartungen an Mütter (2803). Vereinbarkeit/Gleichstellung am Arbeitsmarkt gehört nicht zu 2803.', '2026-10-08', true, '{2803}'),
  (28, 17, 'ST', 'keine', 'Kapitel ''Gleichstellung voranbringen'' (S. 37-39) und ''Gute Arbeit'' (S. 22) gelesen. Zu Rollenbildern und Erwartungen an Mütter nur Wahlfreiheit-Bekenntnis und Betreuungsfinanzierung (gehört zu Kita-Betreuung); keine Zusage gegen widersprüchliche Rollenerwartungen.', '2026-10-08', true, '{2803}'),
  (28, 18, null, 'massnahmen', null, '2026-10-08', true, '{2801,2802,2803,2804}'),
  (28, 18, 'BE', 'massnahmen', null, '2026-10-08', true, '{2803}'),
  (28, 18, 'MV', 'keine', 'Inhaltsverzeichnis, Kapitel Bildung, Gesellschaftlicher Zusammenhalt (S. 13-19, u.a. Diskriminierung) und Stichwortsuche (Frauen, Mütter, Gleichstellung, Geschlecht, Sexismus, Vereinbarkeit, Rollen) gelesen; keine Zusage zu Rollenbildern oder Erwartungen an Mütter.', '2026-10-08', true, '{2803}'),
  (28, 18, 'ST', 'keine', 'Inhaltsverzeichnis und Fundstelle S. 128 gelesen (Männerpolitik: moderne Rollenbilder für Männer, nicht Erwartungen an Mütter). Volltextsuche nach Frauen, Mütter, Rollenbild, Stereotyp, Elternzeit, Teilzeit, Vereinbarkeit ergab nur Gewalt-, Gesundheits- und Männerthemen.', '2026-10-08', true, '{2803}');

commit;
