-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 26 „Barrieren für Menschen mit Behinderung“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 26;
delete from public.abdeckung where thema_id = 26;
delete from public.pruef_einheiten where thema_id = 26;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (9297, 26, 'Beschäftigungspflicht durchsetzen: Ausgleichsabgabe erhöhen oder staffeln, Schlupflöcher schließen (Bund)', 'Eine spürbare Abgabe erhöht die Beschäftigung an der Quotenschwelle (Österreich, IAB); Übersichtsstudien finden aber gemischte Effekte, Betriebe weichen teils unter Schwellen aus. Der Bund regelt das im SGB IX selbst.', 'gemischt', 'https://econpapers.repec.org/RePEc:jku:nrnwps:2009_11', 'bund', null, true, 'blind'),
  (9298, 26, 'Barrieren in Bahn, Bus und an Haltestellen durch mehr Investitionen schneller abbauen (Bund)', 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'gemischt', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'bund', null, true, 'blind'),
  (9299, 26, 'Werkstätten für behinderte Menschen zu Inklusionsbetrieben mit Mindestlohn umbauen (Bund)', 'Nach Schließung der Werkstätten fanden in Vermont viele reguläre Arbeit, in Maine sanken Stunden und Einkommen. Mindestlohn für rund 300.000 Beschäftigte und tragfähige Inklusionsbetriebe sind finanziell ungeklärt.', 'gemischt', 'https://www.publicsource.org/vermont-closed-workshops-for-people-with-disabilities-what-happened-next/', 'bund', null, true, 'blind'),
  (9300, 26, 'Vermittlung und Förderung für Arbeit auf dem allgemeinen Arbeitsmarkt stärken (Bund)', 'Vermittlung kann Menschen mit Behinderung und Betriebe mit geeigneten Tätigkeiten zusammenbringen; Förderungen wie Lohnzuschüsse wirken laut Übersichtsstudie aber uneinheitlich, die Zusage bleibt unbestimmt. Bund und Arbeitsagentur sind zuständig.', 'gemischt', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'bund', null, true, 'blind'),
  (9301, 26, 'Finanzielle Anreize für Arbeitgeber, barrierefreie und zusätzliche Arbeitsplätze zu schaffen (Bund)', 'Setzt an Ausstattungskosten an, die ein Viertel der Betriebe als Hürde nennt; Betriebe wünschen vor allem Zuschüsse. Studien zu Einstellungsanreizen sind gemischt (Mitnahmeeffekte); Steuergutschriften brauchen den Bundesrat und Gegenfinanzierung.', 'gemischt', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 26 and id not in (9297, 9298, 9299, 9300, 9301);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (9302, 26, 11, null, 'Barrieren in Bus und Bahn sollen schneller beseitigt werden.', '{2601}', 9298, 1, 2, null, 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=62', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9303, 26, 11, null, 'Zugang zu Ausbildung und Arbeit erleichtern: Vermittlung auf den ersten Arbeitsmarkt sowie Inklusionsbetriebe und Werkstätten stärken.', '{2602}', 9300, 2, 3, null, 'Vermittlung kann Menschen mit Behinderung und Betriebe mit geeigneten Tätigkeiten zusammenbringen; Förderungen wie Lohnzuschüsse wirken laut Übersichtsstudie aber uneinheitlich, die Zusage bleibt unbestimmt. Bund und Arbeitsagentur sind zuständig.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=61', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9304, 26, 12, null, 'Barrierefreiheit auch in der Mobilität zu einem Schwerpunkt machen', '{2601}', 9298, 1, 2, null, 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=39', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9305, 26, 12, null, 'Aufnahme einer Arbeit auf dem allgemeinen Arbeitsmarkt verstärkt fördern und Werkstätten weiterentwickeln', '{2602}', 9300, 2, 3, null, 'Vermittlung kann Menschen mit Behinderung und Betriebe mit geeigneten Tätigkeiten zusammenbringen; Förderungen wie Lohnzuschüsse wirken laut Übersichtsstudie aber uneinheitlich, die Zusage bleibt unbestimmt. Bund und Arbeitsagentur sind zuständig.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=39', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9306, 26, 13, null, 'Erhebliche Investitionen in umfassende Barrierefreiheit im Verkehr, an Haltestellen und Mobilitätsangeboten.', '{2601}', 9298, 1, 2, null, 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=47', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9307, 26, 13, null, 'Veraltete Regelwerke erneuern, um Ausnahmen bei der Barrierefreiheit im Nahverkehr zu beenden.', '{2601}', null, 2, 2, null, 'Das Ende von Ausnahmen schafft verbindlichen Druck, Haltestellen und Fahrzeuge barrierefrei zu machen; die Wirkung ist kaum untersucht. Umsetzung liegt bei Ländern und Kommunen, die Finanzierung ist offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=48', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9308, 26, 13, null, 'Gesetzliche Schlupflöcher bei der Beschäftigungspflicht schließen und die Ausgleichsabgabe anpassen.', '{2602}', 9297, 2, 3, null, 'Eine spürbare Abgabe erhöht die Beschäftigung an der Quotenschwelle (Österreich, IAB); Übersichtsstudien finden aber gemischte Effekte, Betriebe weichen teils unter Schwellen aus. Der Bund regelt das im SGB IX selbst.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=123', 'https://econpapers.repec.org/RePEc:jku:nrnwps:2009_11', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9309, 26, 13, null, 'Werkstättensystem schrittweise zu Inklusionsunternehmen weiterentwickeln, mit Mindestlohn und individueller Unterstützung.', '{2602}', 9299, 2, 1, null, 'Nach Schließung der Werkstätten fanden in Vermont viele reguläre Arbeit, in Maine sanken Stunden und Einkommen. Mindestlohn für rund 300.000 Beschäftigte und tragfähige Inklusionsbetriebe sind finanziell ungeklärt.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=123', 'https://www.publicsource.org/vermont-closed-workshops-for-people-with-disabilities-what-happened-next/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9310, 26, 14, null, 'Praxisnahe Förderung und Arbeitsvermittlung für Menschen mit Behinderung, um Chancen auf dem ersten Arbeitsmarkt zu verbessern.', '{2602}', 9300, 2, 3, null, 'Vermittlung kann Menschen mit Behinderung und Betriebe mit geeigneten Tätigkeiten zusammenbringen; Förderungen wie Lohnzuschüsse wirken laut Übersichtsstudie aber uneinheitlich, die Zusage bleibt unbestimmt. Bund und Arbeitsagentur sind zuständig.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=25', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9311, 26, 16, null, 'Bahnnetz sanieren, elektrifizieren und Strecken ausbauen bzw. reaktivieren, dabei barrierefrei', '{2601}', 9298, 1, 2, null, 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=37', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9312, 26, 16, null, 'Beschäftigungspflicht für Menschen mit Behinderung wieder auf sechs Prozent anheben, ohne Freikaufen', '{2602}', null, 1, 1, null, 'Die Senkung der Quote von 6 auf 5 % (2000) veränderte die Beschäftigungschancen laut IAB-Studie nicht; Abgaben wirken eher an Schwellen. Eine Pflicht ohne Abgabe als Ausgleich wirft Fragen der Berufsfreiheit auf, wenn geeignete Bewerbungen fehlen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=54', 'https://iab.de/publication/?id=591316', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9313, 26, 16, null, 'Inklusionsbetriebe besser öffentlich finanzieren', '{2602}', null, 2, 3, null, 'Inklusionsbetriebe schaffen Arbeitsplätze mit passenden Tätigkeiten; die BMAS-Evaluation bewertet die Beschäftigung dort als nachhaltig. Die Zahl der Plätze ist begrenzt, ohne Betrag bleibt der Umfang der Förderung offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=54', 'https://www.bmas.de/DE/Service/Publikationen/Forschungsberichte/fb-578-foerderung-inklusionsbetriebe.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (9314, 26, 17, null, 'Mehr Anreize für Betriebe, barrierefreie Arbeitsplätze zu schaffen.', '{2602}', 9301, 2, 2, null, 'Setzt an Ausstattungskosten an, die ein Viertel der Betriebe als Hürde nennt; Betriebe wünschen vor allem Zuschüsse. Studien zu Einstellungsanreizen sind gemischt (Mitnahmeeffekte); Steuergutschriften brauchen den Bundesrat und Gegenfinanzierung.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=22', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9315, 26, 18, null, 'Ausgleichsabgabe für Betriebe, die zu wenige Menschen mit Behinderung beschäftigen, wird nach Unternehmensgröße und Erfüllungsgrad der Quote gestaffelt.', '{2602}', 9297, 2, 3, null, 'Eine spürbare Abgabe erhöht die Beschäftigung an der Quotenschwelle (Österreich, IAB); Übersichtsstudien finden aber gemischte Effekte, Betriebe weichen teils unter Schwellen aus. Der Bund regelt das im SGB IX selbst.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=146', 'https://econpapers.repec.org/RePEc:jku:nrnwps:2009_11', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9316, 26, 18, null, 'Zusätzliche Arbeitsplätze für Menschen mit Behinderung über die Quote hinaus werden mit steuerlichen Gutschriften gefördert.', '{2602}', 9301, 2, 2, null, 'Setzt an Ausstattungskosten an, die ein Viertel der Betriebe als Hürde nennt; Betriebe wünschen vor allem Zuschüsse. Studien zu Einstellungsanreizen sind gemischt (Mitnahmeeffekte); Steuergutschriften brauchen den Bundesrat und Gegenfinanzierung.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=146', 'https://pureportal.strath.ac.uk/en/publications/employer-focused-interventions-targeting-disability-employment-a-/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9317, 26, 18, null, 'Werkstätten für Menschen mit Behinderung werden abgeschafft und in Inklusionsbetriebe mit Arbeitnehmendenrechten und Mindestlohn umgewandelt.', '{2602}', 9299, 2, 1, null, 'Nach Schließung der Werkstätten fanden in Vermont viele reguläre Arbeit, in Maine sanken Stunden und Einkommen. Mindestlohn für rund 300.000 Beschäftigte und tragfähige Inklusionsbetriebe sind finanziell ungeklärt.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=147', 'https://www.publicsource.org/vermont-closed-workshops-for-people-with-disabilities-what-happened-next/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9318, 26, 18, null, 'Öffentlicher Nahverkehr wird barrierefrei ausgebaut.', '{2601}', 9298, 1, 2, null, 'Investitionen beseitigen Barrieren, wo sie verbaut werden; laut Bundesrechnungshof lag die Verzögerung aber vor allem an der Steuerung, Fördergeld blieb ungenutzt. Ohne bessere Steuerung wenig Beschleunigung; der ÖPNV liegt zudem bei Ländern.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=69', 'https://bundesrechnungshof.de/berichte/bmdv-verschleppt-investitionen-in-bahnhoefe', 'gemischt', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (9297, 26),
  (9298, 26),
  (9299, 26),
  (9300, 26),
  (9301, 26),
  (9307, 26),
  (9312, 26),
  (9313, 26);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (26, 11, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 12, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 13, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 14, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 15, null, 'keine', 'Erfasste Stellen (S. 23) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-08', true, '{2601,2602,2603}'),
  (26, 16, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 17, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}'),
  (26, 18, null, 'massnahmen', null, '2026-10-08', true, '{2601,2602,2603}');

commit;
