-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 25 „Hass und Anfeindungen im Internet“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 25;
delete from public.abdeckung where thema_id = 25;
delete from public.pruef_einheiten where thema_id = 25;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (9253, 25, 'Durchsetzung der Pflichten von Plattformen zur Entfernung rechtswidriger Inhalte (DSA) stärken (Bund)', 'Eine Studie zum NetzDG zeigt weniger Hassbeiträge und weniger Hassdelikte durch Löschpflichten. Dagegen: Die Aufsicht über sehr große Plattformen liegt bei der EU-Kommission, der Bund stärkt vor allem die nationale Aufsicht.', 'belegt', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'bund', null, true, 'blind'),
  (9254, 25, 'Digitales Gewaltschutzgesetz mit gerichtlicher Accountsperre und Rechten für Betroffene (Bund)', 'Gibt Betroffenen Auskunfts- und Sperransprüche gegen Täter-Accounts und erleichtert das Löschen; ein Referentenentwurf liegt vor. Dagegen: Wirkung noch unerprobt, neue Accounts lassen sich leicht anlegen.', 'offen', null, 'bund', null, true, 'blind'),
  (9255, 25, 'Beratung und Unterstützung für Betroffene digitaler Gewalt ausbauen (Land)', 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'offen', null, 'land', null, true, 'blind'),
  (9256, 25, 'Medienbildung und digitale Prävention gegen Hass im Netz (Land)', 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'gemischt', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'land', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 25 and id not in (9253, 9254, 9255, 9256);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (9257, 25, 11, 'BE', 'Bekämpfung digitaler Gewalt verstärken, bestehende Beratungsangebote ausbauen und psychische sowie digitale Gewalt strafrechtlich umfassend erfassen.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=12', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9258, 25, 11, 'MV', 'Auf Bundesebene eine EU-rechtskonforme Vorratsdatenspeicherung einfordern, um Hasskriminalität im Internet wirksam zu bekämpfen.', '{2501}', null, 1, 1, null, 'Gespeicherte IP-Adressen können Täter identifizieren helfen. Dagegen: Ein MPI-Gutachten fand keinen Einfluss auf Aufklärungsquoten; regeln kann es nur der Bund, der EuGH setzt enge Grenzen.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=35', 'https://www.computerwoche.de/article/2644660/leutheusser-schnarrenberger-sieht-sich-durch-vorratsdaten-studie-bestaetigt.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9259, 25, 11, 'MV', 'Gesetzliche Klarnamen- und ID-Pflicht gegenüber Plattformbetreibern und Providern, damit Straftäter im Netz identifizierbar sind.', '{2503}', null, 1, 1, null, 'Identifizierbarkeit könnte abschrecken. Dagegen: Studien zeigen kaum weniger, teils mehr Aggression unter Klarnamen; ein Land kann das nicht regeln, und EU-Recht steht nationalen Pflichten für Plattformen entgegen.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=38', 'https://news.uzh.ch/en/articles/2016/Trolls-often-waive-their-anonymity-online.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9260, 25, 12, null, 'Digitales Gewaltschutzgesetz: Täter-Accounts einfacher sperren, Rechte Betroffener per Verbandsklagerecht durchsetzen.', '{2501}', 9254, 2, 3, null, 'Gibt Betroffenen Auskunfts- und Sperransprüche gegen Täter-Accounts und erleichtert das Löschen; ein Referentenentwurf liegt vor. Dagegen: Wirkung noch unerprobt, neue Accounts lassen sich leicht anlegen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=44', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9261, 25, 12, null, 'Zentralstelle für strafbare Inhalte im Internet beim BKA ausbauen, um Online-Hasskriminalität effektiver zu verfolgen.', '{2501}', null, 2, 3, null, 'Eine zentrale BKA-Stelle erhöht die Chance, Täter zu ermitteln, was laut Forschung stärker abschreckt als höhere Strafen. Dagegen: Wirkung bei Online-Hass nicht eigens untersucht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=48', 'https://nij.ojp.gov/topics/articles/five-things-about-deterrence', 'offen', '2026-10-08', false, true, 'blind'),
  (9262, 25, 12, null, 'Wohnanschrift Betroffener von Hassdelikten im Strafverfahren nicht mehr per Akteneinsicht offenlegen.', '{2501}', null, 1, 3, null, 'Nimmt Betroffenen die Sorge, dass Täter über die Akte ihre Anschrift erfahren, und kann Anzeigen erleichtern; der Bund ist zuständig. Dagegen: setzt nur an einer einzelnen Hürde an.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=48', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9263, 25, 12, null, 'Plattformbetreiber zur Entfernung illegaler Inhalte verpflichten.', '{2502}', 9253, 2, 3, null, 'Eine Studie zum NetzDG zeigt weniger Hassbeiträge und weniger Hassdelikte durch Löschpflichten. Dagegen: Die Aufsicht über sehr große Plattformen liegt bei der EU-Kommission, der Bund stärkt vor allem die nationale Aufsicht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=45', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'belegt', '2026-10-08', false, true, 'blind'),
  (9264, 25, 12, null, 'Plattformen zur Offenlegung ihrer Algorithmen und zur Prüfung auf diskriminierende Praktiken verpflichten.', '{2503}', null, 1, 1, null, 'Transparenz über Empfehlungsalgorithmen kann verstärkende Effekte sichtbar machen. Dagegen: Der DSA regelt das bereits auf EU-Ebene, Wirkung auf Anfeindungen ist unbelegt.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=50', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9265, 25, 12, 'BE', 'Spezialisierte Beratungsstellen gegen Hasskriminalität stärken, online wie offline, und Aufklärungsquoten erhöhen.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=30', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9266, 25, 12, 'BE', 'Strategie für Zusammenhalt im Netz mit digitalen Präventionsansätzen gegen Hassrede.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=29', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9267, 25, 12, 'MV', 'Kampagnen gegen Fake News und Fehlinformationen sowie landesweite Förderung von Medienkompetenz, um Hass auch im Netz zu begegnen.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf#page=44', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9268, 25, 12, 'ST', 'Hilfesystem gegen digitale Gewalt und Hass im Netz: Fachkräfte schulen, Behörden digital präsenter machen und digitale Beratungsangebote ergänzen.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=32', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9269, 25, 12, 'ST', 'Medienbildung an Schulen weiter ausbauen, insbesondere zu Hass im Netz, Desinformation und gezielten Kampagnen.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=35', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9270, 25, 13, null, 'Strafbare Hassinhalte konsequent löschen, Accounts schneller sperren, per digitalem Gewaltschutzgesetz und mit mehr Nutzerrechten.', '{2502}', 9254, 2, 3, null, 'Gibt Betroffenen Auskunfts- und Sperransprüche gegen Täter-Accounts und erleichtert das Löschen; ein Referentenentwurf liegt vor. Dagegen: Wirkung noch unerprobt, neue Accounts lassen sich leicht anlegen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=114', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9271, 25, 13, null, 'Konsequente Durchsetzung des Digitale-Dienste-Gesetzes (DSA) gegenüber Plattformen gemeinsam mit der EU.', '{2502}', 9253, 2, 3, null, 'Eine Studie zum NetzDG zeigt weniger Hassbeiträge und weniger Hassdelikte durch Löschpflichten. Dagegen: Die Aufsicht über sehr große Plattformen liegt bei der EU-Kommission, der Bund stärkt vor allem die nationale Aufsicht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=115', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'belegt', '2026-10-08', false, true, 'blind'),
  (9272, 25, 13, null, 'Medienanstalten der Länder mit mehr Ressourcen für Löschung und Verfolgung von Hasskriminalität im Netz ausstatten.', '{2502}', null, 2, 2, null, 'Mehr Mittel für Löschung und Verfolgung setzen an der Durchsetzung an; Löschpflichten senken Hass laut NetzDG-Studie. Dagegen: Medienanstalten sind Ländersache, der Bund kann nur beitragen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=115', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'belegt', '2026-10-08', false, true, 'blind'),
  (9273, 25, 13, null, 'Strafverfolgung bei Hasskriminalität im digitalen Raum stärken, auch bei anonymen Accounts (Login-Falle, Accountsperren).', '{2501,2502}', null, 2, 2, null, 'Login-Falle und gerichtliche Accountsperren erhöhen die Chance, anonyme Täter zu ermitteln und zu stoppen. Dagegen: Datenschutzrechtlich heikel, Ausgestaltung aufwendig, Wirkung noch nicht untersucht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=140', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9274, 25, 13, 'BE', 'Beratungs- und Unterstützungsangebote für Betroffene digitaler Gewalt ausbauen sowie Melde- und Dokumentationsstrukturen stärken.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=133', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9275, 25, 13, 'BE', 'Zentrale Meldestelle für digitale Gewalt als Kompetenzzentrum, die Meldungen aufnimmt und mit den Strafverfolgungsbehörden zusammenarbeitet.', '{2501}', null, 2, 3, null, 'Meldestellen der Länder haben zu vielen Ermittlungsverfahren und Verurteilungen geführt und erleichtern das Melden. Dagegen: Täter werden oft nicht ermittelt, Wirkung auf das Ausmaß des Hasses unerforscht.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=161', 'https://sonntagsblatt.de/artikel/epd/bayerisches-online-meldeverfahren-gegen-hass-im-netz-zieht-bilanz', 'offen', '2026-10-08', false, true, 'blind'),
  (9276, 25, 13, 'BE', 'Bekämpfung von Onlinekriminalität und Hasskriminalität im Netz stärken.', '{2501}', null, 1, 3, null, 'Stärkere Verfolgung von Hass im Netz kann Täter eher stellen; das Land ist für Polizei und Justiz zuständig. Dagegen: ohne konkrete Maßnahme, Wirkung nicht abschätzbar.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=224', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9277, 25, 13, 'BE', 'Digitale Präventionsangebote wie Digital Streetwork ausbauen und Medienkompetenz in allen Altersgruppen fördern, um Hass früh zu erkennen.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=159', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9278, 25, 13, 'MV', 'Beratungs- und Unterstützungsangebote für Opfer von Bedrohungen und Angriffen (Hass und Hetze, online wie offline) weiter ausbauen.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://gruene-mv.de/?wpdmdl=33772#page=90', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9279, 25, 14, 'BE', 'Opferschutz ausbauen: Schutz vor Stalking und Hasskriminalität durch höhere Strafandrohung im Gewaltschutzgesetz und bessere Durchsetzung.', '{2501}', null, 1, 2, null, 'Psychologische Hilfe für Betroffene kann das Land selbst anbieten. Dagegen: Höhere Strafen schrecken laut Forschung kaum ab, entscheidend ist die Entdeckungswahrscheinlichkeit; das Strafmaß regelt der Bund.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=73', 'https://nij.ojp.gov/topics/articles/five-things-about-deterrence', 'belegt', '2026-10-08', false, true, 'blind'),
  (9280, 25, 15, null, 'Das Netzwerkdurchsetzungsgesetz mit seinen Löschfristen für Plattformen zurücknehmen und den europäischen Digital Services Act in Deutschland nicht umsetzen.', '{2502}', null, 0, 0, null, 'Weniger Löschpflichten lassen nach der NetzDG-Studie mehr Hass online. Der DSA ist eine unmittelbar geltende EU-Verordnung; ihn nicht anzuwenden wäre EU-rechtswidrig.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=50', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'belegt', '2026-10-08', false, true, 'blind'),
  (9281, 25, 15, null, 'Große Anbieter sozialer Medien verpflichten, die Meinungsfreiheit ihrer Nutzer zu respektieren; staatliche Zensurvorschriften und Abkommen mit Plattformen abschaffen.', '{2502}', null, 0, 1, null, 'Zielt auf weniger Eingriffe in Nutzerinhalte, nicht auf Schutz vor Anfeindungen. Pflichten großer Plattformen regelt der DSA abschließend auf EU-Ebene, nationale Vorgaben sind kaum möglich.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=132', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9282, 25, 15, 'BE', 'Öffentliche Förderung von Meldestellen für Anfeindungen und Vorfälle unterhalb der Strafbarkeitsgrenze beenden; sie sollen sich privat finanzieren.', '{2501}', null, 0, 3, null, 'Das Land kann Förderungen beenden. Weniger Meldestellen erschweren aber das Melden; Meldestellen haben zu vielen Strafverfahren geführt.', 'https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf#page=77', 'https://sonntagsblatt.de/artikel/epd/bayerisches-online-meldeverfahren-gegen-hass-im-netz-zieht-bilanz', 'offen', '2026-10-08', false, true, 'blind'),
  (9283, 25, 15, 'BE', 'Bundesratsinitiative, um den Sonderstraftatbestand der Beleidigung von Politikern (§ 188 StGB) ersatzlos zu streichen.', '{2501}', null, 0, 1, null, 'Ein Land kann nur eine Bundesratsinitiative starten, entscheiden muss der Bund. Für Betroffene von Hass entsteht kein besserer Schutz oder Meldeweg.', 'https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf#page=16', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9284, 25, 15, 'ST', 'Bestehende Meinungsstraftatbestände entschlacken, statt neue Gesetze gegen sogenannte Hasskriminalität zu schaffen.', '{2501}', null, 0, 1, null, 'Weniger Straftatbestände verbessern weder Schutz noch Meldewege für Betroffene. Strafrecht ist Bundesrecht, das Land kann sich nur einsetzen.', 'https://afd-lsa.de/wp-content/uploads/2026/07/AfD_Sachsen-Anhalt_Regierungsprogramm_2026_230726-web.pdf#page=123', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9285, 25, 16, null, 'Bundesnetzagentur personell so ausstatten, dass der Digital Services Act gegenüber Plattformen wirksam umgesetzt wird.', '{2502}', 9253, 2, 3, null, 'Eine Studie zum NetzDG zeigt weniger Hassbeiträge und weniger Hassdelikte durch Löschpflichten. Dagegen: Die Aufsicht über sehr große Plattformen liegt bei der EU-Kommission, der Bund stärkt vor allem die nationale Aufsicht.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=57', 'https://econpapers.repec.org/RePEc:cge:wacage:701', 'belegt', '2026-10-08', false, true, 'blind'),
  (9286, 25, 16, 'BE', 'Technik-Kompetenzzentren unterstützen Beratungsstellen und Betroffene bei digitaler Gewalt; mehr Schutz- und Therapieangebote, Fachdezernate bei der Staatsanwaltschaft.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=287', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9287, 25, 16, 'MV', 'Beratungs- und Unterstützungsangebote für Betroffene digitaler Gewalt ausbauen und stärken.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=14', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9288, 25, 16, 'MV', 'Medienbildung für alle Altersgruppen ausbauen, auch mit Blick auf Hassbotschaften in sozialen Medien.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=27', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9289, 25, 16, 'ST', 'Beratungsstellen gegen Hass im Netz stärken; Verfasser von Hassnachrichten sollen Konsequenzen tragen.', '{2501}', 9255, 2, 3, null, 'Spezialisierte Beratung hilft Betroffenen, Hass zu melden, anzuzeigen und durchzustehen; Länder können sie selbst fördern. Dagegen: Wirkung auf Meldequote und Ausmaß des Hasses kaum evaluiert.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=21', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9290, 25, 16, 'ST', 'Spezialisierte Ansprechpersonen für Hasskriminalität in jeder Polizeibehörde und jedem Landkreis.', '{2501}', null, 2, 3, null, 'Feste Ansprechpersonen bei der Polizei senken Hürden für Anzeigen; das Land ist zuständig. Dagegen: Wirkung auf Anzeige- und Aufklärungsquote bisher kaum untersucht.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=127', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9291, 25, 17, null, 'Staatlich finanzierte Meldestellen für Äußerungen im Netz abschaffen und nicht mehr mit Steuergeld finanzieren.', '{2501}', null, 0, 3, null, 'Der Bund kann seine Förderung beenden. Weniger Meldestellen erschweren aber das Melden; Meldestellen haben zu vielen Strafverfahren geführt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=39', 'https://sonntagsblatt.de/artikel/epd/bayerisches-online-meldeverfahren-gegen-hass-im-netz-zieht-bilanz', 'offen', '2026-10-08', false, true, 'blind'),
  (9292, 25, 17, null, 'Den Straftatbestand der Beleidigung von Personen des politischen Lebens (§ 188 StGB) streichen.', '{2501}', null, 0, 3, null, 'Der Bund kann den Tatbestand streichen, allgemeiner Beleidigungsschutz bleibt. Für Betroffene von Hass entsteht dadurch kein besserer Schutz oder Meldeweg.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=35', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9293, 25, 18, null, 'Strafrahmen für Hasskriminalität, besonders im digitalen Raum, werden verschärft.', '{2501}', null, 1, 3, null, 'Der Bund kann Strafrahmen anheben. Dagegen: Laut Abschreckungsforschung wirkt die Wahrscheinlichkeit, erwischt zu werden, weit stärker als die Strafhöhe.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=18', 'https://nij.ojp.gov/topics/articles/five-things-about-deterrence', 'belegt', '2026-10-08', false, true, 'blind'),
  (9294, 25, 18, null, 'Schutz vor geschlechtsspezifischer Gewalt wird auf digitale Räume ausgeweitet, mit Maßnahmen gegen Cyber-Harassment und Revenge Porn.', '{2501}', null, 1, 3, null, 'Bezieht digitale Belästigung und bildbasierte Gewalt in den Gewaltschutz ein, der Bund ist zuständig. Dagegen: Die Maßnahmen bleiben unbestimmt, Wirkung offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=152', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9295, 25, 18, 'BE', 'Früh ansetzende Unterstützungs- und Präventionsangebote in Bezirken und digitalen Räumen gegen Diskriminierung, Hass im Netz und Gewaltentwicklung ausbauen.', '{2503}', 9256, 1, 3, null, 'Schulische Präventionsprogramme senken Cybermobbing leicht. Dagegen: Eine systematische Übersicht findet für Online-Maßnahmen gegen Hassrede bisher keinen gesicherten Effekt; Wirkung indirekt und langfristig.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=74', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133687/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9296, 25, 18, 'ST', 'Auf Beteiligungsplattformen verifizierte Accounts mit Klarnamenpflicht und Moderationsregeln, die rechtswidrige Inhalte und Beleidigungen entfernen', '{2503}', null, 1, 3, null, 'Moderation auf eigenen Beteiligungsplattformen kann das Land sofort regeln. Dagegen: Gilt nur dort, und Klarnamen senken Aggression laut Studien kaum, teils steigt sie.', 'https://voltdeutschland.org/storage/assets-sachsen-anhalt/pdf/landtagswahl-2026/wahlprogramm_volt_lv_lsa.pdf#page=114', 'https://news.uzh.ch/en/articles/2016/Trolls-often-waive-their-anonymity-online.html', 'gemischt', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (9253, 25),
  (9254, 25),
  (9255, 25),
  (9256, 25),
  (9258, 25),
  (9259, 25),
  (9261, 25),
  (9262, 25),
  (9264, 25),
  (9272, 25),
  (9273, 25),
  (9275, 25),
  (9276, 25),
  (9279, 25),
  (9280, 25),
  (9281, 25),
  (9282, 25),
  (9283, 25),
  (9284, 25),
  (9290, 25),
  (9291, 25),
  (9292, 25),
  (9293, 25),
  (9294, 25),
  (9296, 25);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (25, 11, null, 'keine', 'Kapitel Innere Sicherheit/Sicherheit im digitalen Raum (S. 38-41) und Fundstellen S. 39, 40, 41, 45, 46, 63 gelesen; nichts zu Hass, Bedrohung oder Anfeindung im Netz (nur IP-Speicherung, Cyberabwehr, DSA-Schwerpunkt Desinformation/Jugendschutz).', '2026-10-08', true, '{2501,2502,2503}'),
  (25, 11, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 11, 'MV', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 11, 'ST', 'keine', 'Kapitel Medien (S. 34-37), Sicherheit (S. 8-9) und alle Fundstellen (S. 19, 22, 32, 35, 36, 58-60) gelesen; keine Zusage gegen Hass im Netz zu Meldewegen/Hilfe für Betroffene oder Prävention/Gesprächsdesign. Nur Medienkompetenz allgemein, Jugendmedienschutz, Plattformverantwortung allgemein.', '2026-10-08', true, '{2501,2503}'),
  (25, 12, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 12, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 12, 'MV', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 12, 'ST', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 13, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 13, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 13, 'MV', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 13, 'ST', 'keine', 'Erfasste Stellen (S. 46) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-08', true, '{2501,2503}'),
  (25, 14, null, 'keine', 'Inhaltsverzeichnis, Kapitel Bildung (S. 9), Sicherheit und Bürgerrechte (S. 23-24), Gleichbehandlung (S. 25), Meinungsfreiheit (S. 27) und Fundstelle S. 49 gelesen; keine Zusage gegen Hass oder Anfeindung im Netz (nur Hasskriminalität allgemein, Medienkompetenz allgemein, DSA nur als Begrenzung).', '2026-10-08', true, '{2501,2502,2503}'),
  (25, 14, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 14, 'MV', 'keine', 'Fundstellen S. 53, 95, 136-139, 146, 151 sowie Kapitel Schule (S. 87) und Rechtsstaatlichkeit/Meinungsfreiheit (S. 151) gelesen; nichts setzt an den Landesursachen 2501 oder 2503 an.', '2026-10-08', true, '{2501,2503}'),
  (25, 14, 'ST', 'keine', 'Erfasste Stellen (S. 26) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-08', true, '{2501,2503}'),
  (25, 15, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 15, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 15, 'MV', 'keine', 'Kapitel Sicherheit/Justiz (S. 42-44), Freiheitsland MV (S. 47) und Fundstellen S. 43, 44, 47, 53 gelesen; keine Zusage zu Hass, Bedrohung oder Anfeindung im Netz, zu Meldewegen, Betroffenenhilfe oder Plattformen. Stichwort Cybercrime nur allgemein (LKA-Personal).', '2026-10-08', true, '{2501,2503}'),
  (25, 15, 'ST', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 16, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 16, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 16, 'MV', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 16, 'ST', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 17, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 17, 'BE', 'keine', 'Inhaltsverzeichnis, Kapitel Schule/Medienbildung (S. 16-17), Gewaltprävention (S. 40), Diskriminierung (S. 33), Digitalisierung (S. 64-65) und Fundstellen S. 11, 24 gelesen; nichts zu Hass, Anfeindung oder Bedrohung im Netz, zu Meldewegen oder Plattformpflichten.', '2026-10-08', true, '{2501,2503}'),
  (25, 17, 'MV', 'keine', 'Fundstellen S. 47, 48, 52, 61, 62, 64, 69, 91 gelesen, dazu Volltextsuche nach Hass, Hetze, Anfeindung, Bedrohung, Beleidigung, digitale Gewalt, Plattform, soziale Netzwerke, Internet, Online; S. 12 (Regeln für digitale Medien) gelesen. Nichts setzt an Hass oder Anfeindung im Netz an.', '2026-10-08', true, '{2501,2503}'),
  (25, 17, 'ST', 'keine', 'Inhaltsverzeichnis, Kapitel ''Demokratie & Debatte'' (S. 11-15), ''Sicherheit durch Rechtsstaatlichkeit'' (S. 65-71) und alle sechs Fundstellen (S. 14, 37, 39, 45, 67, 71) gelesen; nichts zu Hass, Bedrohung oder Anfeindung im Netz, zu Meldewegen, Plattformpflichten oder Moderationsdesign.', '2026-10-08', true, '{2501,2503}'),
  (25, 18, null, 'massnahmen', null, '2026-10-08', true, '{2501,2502,2503}'),
  (25, 18, 'BE', 'massnahmen', null, '2026-10-08', true, '{2501,2503}'),
  (25, 18, 'MV', 'keine', 'Kapitel Medien- und Demokratiebildung (S. 6-7), Schutz/Sicherheit (S. 14-15), Diskriminierung (S. 17-18), Digitale Sicherheit (S. 44-45) gelesen; nichts zu Hass, Bedrohung oder Anfeindung im Netz. Beratungsstelle (S. 15) betrifft Gewalt, nicht Online-Hass.', '2026-10-08', true, '{2501,2503}'),
  (25, 18, 'ST', 'massnahmen', null, '2026-10-08', true, '{2501,2503}');

commit;
