-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 21 „Armut und Kinderarmut“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 21;
delete from public.abdeckung where thema_id = 21;
delete from public.pruef_einheiten where thema_id = 21;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (8613, 21, 'Sozialleistungen automatisch bzw. antragslos auszahlen, Datenaustausch zwischen Behörden (Bund)', 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'belegt', 'https://www.nber.org/papers/w10488', 'bund', null, true, 'blind'),
  (8614, 21, 'Aktiv über Ansprüche informieren und beim Antrag helfen (Bund)', 'Experimente zeigen: Information erhöht die Inanspruchnahme, mit Antragshilfe noch stärker. Dagegen: Effekte bleiben begrenzt und erreichen die Bedürftigsten schlechter.', 'belegt', 'https://www.nber.org/papers/w24652', 'bund', null, true, 'blind'),
  (8615, 21, 'Regelsätze regelmäßig an die Preisentwicklung anpassen (Bund)', 'Sichert die Kaufkraft und verhindert, dass Regelsätze hinter der Inflation zurückbleiben. Dagegen: Eine Fortschreibung besteht bereits; die Lücke durch die Bemessung selbst bleibt unberührt.', 'offen', null, 'bund', null, true, 'blind'),
  (8616, 21, 'Steuerliche Entlastung für Alleinerziehende ausbauen oder als Abzug von der Steuerschuld gestalten (Bund)', 'Entlastet erwerbstätige Alleinerziehende, als Abzug von der Steuerschuld stärker bei kleinen Einkommen. Dagegen: Wer kaum Steuern zahlt, etwa im Grundsicherungsbezug, profitiert ohne Auszahlung kaum.', 'offen', null, 'bund', null, true, 'blind'),
  (8617, 21, 'Elterngeld-Mindestbetrag und Ersatzrate für geringe Einkommen anheben (Bund)', 'Erhöht das Einkommen von Familien mit kleinen Einkommen im ersten Lebensjahr. Dagegen: zeitlich begrenzt und bei Grundsicherungsbezug weitgehend angerechnet.', 'offen', null, 'bund', null, true, 'blind'),
  (8618, 21, 'Kindergeld an die Entwicklung des Kinderfreibetrags koppeln bzw. angleichen (Bund)', 'Höheres Kindergeld erreicht alle Familien. Dagegen: Es wird auf die Grundsicherung angerechnet und senkt Armutsrisiken laut Evaluationen daher nur wenig; teuer bei geringer Zielgenauigkeit.', 'gemischt', null, 'bund', null, true, 'blind'),
  (8619, 21, 'Unterhaltsvorschuss: Kindergeld nur teilweise anrechnen, Bezugsdauer ausweiten (Bund)', 'Erhöht die Leistung für Alleinerziehende ohne Unterhalt. Dagegen: Im Grundsicherungsbezug wird der Unterhaltsvorschuss angerechnet, der Zugewinn kommt nur Haushalten oberhalb davon zugute.', 'offen', null, 'bund', null, true, 'blind'),
  (8620, 21, 'Existenzminimum und Umgangsmehrbedarf von Kindern in Trennungsfamilien absichern (Bund)', 'Deckt Mehrkosten, wenn Kinder in zwei Haushalten leben, und schließt so eine Lücke für Trennungsfamilien. Dagegen: betrifft eine begrenzte Gruppe, Ausgestaltung offen.', 'offen', null, 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 21 and id not in (8613, 8614, 8615, 8616, 8617, 8618, 8619, 8620);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (8621, 21, 11, null, 'Kindergeld künftig nach der Geburt automatisch auszahlen', '{2103}', 8613, 2, 2, null, 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=63', 'https://www.nber.org/papers/w10488', 'belegt', '2026-10-10', false, true, 'blind'),
  (8622, 21, 11, null, 'Steuerlichen Entlastungsbetrag für Alleinerziehende erhöhen', '{2102}', 8616, 1, 3, null, 'Entlastet erwerbstätige Alleinerziehende, als Abzug von der Steuerschuld stärker bei kleinen Einkommen. Dagegen: Wer kaum Steuern zahlt, etwa im Grundsicherungsbezug, profitiert ohne Auszahlung kaum.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=63', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8623, 21, 12, null, 'Familien mit niedrigem Lohneinkommen sollen durch Kindergeld, Kinderzuschlag und Wohngeld nicht auf Bürgergeld angewiesen sein.', '{2102}', null, 2, 2, null, 'Kinderzuschlag und Wohngeld gelten als zielgenau gegen Armutsrisiken erwerbstätiger Eltern. Dagegen: geringe Inanspruchnahme und Schnittstellenprobleme, Ausgestaltung und Höhe offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8624, 21, 12, null, 'Entlastungsbetrag für Alleinerziehende in einen Abzug von der Steuerschuld umwandeln.', '{2102}', 8616, 1, 3, null, 'Entlastet erwerbstätige Alleinerziehende, als Abzug von der Steuerschuld stärker bei kleinen Einkommen. Dagegen: Wer kaum Steuern zahlt, etwa im Grundsicherungsbezug, profitiert ohne Auszahlung kaum.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8625, 21, 12, null, 'Anträge bei Sozialleistungen vereinfachen, Leistungen zusammenfassen; Kindergeld soll automatisch gewährt werden.', '{2103}', 8613, 2, 2, null, 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=37', 'https://www.nber.org/papers/w10488', 'belegt', '2026-10-10', false, true, 'blind'),
  (8626, 21, 12, null, 'Digitalen Datenaustausch zwischen Behörden ausbauen, damit Leistungen ohne mühsame Antragsprozesse ankommen.', '{2103}', 8613, 2, 2, null, 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=38', 'https://www.nber.org/papers/w10488', 'belegt', '2026-10-10', false, true, 'blind'),
  (8627, 21, 13, null, 'Bürgergeld-Regelsatz darf nicht sinken; Bürgergeld wird regelmäßig angepasst, damit das soziokulturelle Existenzminimum garantiert ist.', '{2101}', 8615, 1, 3, null, 'Sichert die Kaufkraft und verhindert, dass Regelsätze hinter der Inflation zurückbleiben. Dagegen: Eine Fortschreibung besteht bereits; die Lücke durch die Bemessung selbst bleibt unberührt.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=99', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8628, 21, 13, null, 'Grundsicherungsleistungen sollen perspektivisch individualisiert werden.', '{2101}', null, 1, 2, null, 'Individuelle Ansprüche könnten Lücken durch Partnereinkommen schließen. Dagegen: nur perspektivisch angekündigt, Wirkung auf die Versorgungslücke unklar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=99', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8629, 21, 13, null, 'Neuberechnung des soziokulturellen Existenzminimums für Kinder, armutsfest.', '{2101}', null, 2, 2, null, 'Eine Neubemessung setzt direkt an zu niedrig berechneten Kinderbedarfen an, die Fachgutachten kritisieren. Dagegen: Methode und Zielhöhe offen, Bemessung bleibt umstritten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8630, 21, 13, null, 'Kindergeld soll gesetzlich an die regelmäßige Erhöhung des Kinderfreibetrags gekoppelt werden.', '{2102}', 8618, 1, 2, null, 'Höheres Kindergeld erreicht alle Familien. Dagegen: Es wird auf die Grundsicherung angerechnet und senkt Armutsrisiken laut Evaluationen daher nur wenig; teuer bei geringer Zielgenauigkeit.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=81', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8631, 21, 13, null, 'Freibetrag für Alleinerziehende wird zu einer Steuergutschrift ausgebaut, die kleine und mittlere Einkommen stärker entlastet.', '{2102}', 8616, 1, 3, null, 'Entlastet erwerbstätige Alleinerziehende, als Abzug von der Steuerschuld stärker bei kleinen Einkommen. Dagegen: Wer kaum Steuern zahlt, etwa im Grundsicherungsbezug, profitiert ohne Auszahlung kaum.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8632, 21, 13, null, 'Kindergeld wird bei Alleinerziehenden nur noch zur Hälfte auf den Unterhaltsvorschuss angerechnet.', '{2102}', 8619, 1, 2, null, 'Erhöht die Leistung für Alleinerziehende ohne Unterhalt. Dagegen: Im Grundsicherungsbezug wird der Unterhaltsvorschuss angerechnet, der Zugewinn kommt nur Haushalten oberhalb davon zugute.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8633, 21, 13, null, 'Steuergutschriften für niedrige Einkommen, Alleinerziehende und Menschen, die mit Bürgergeld aufstocken, zur unbürokratischen Entlastung.', '{2102}', null, 2, 2, null, 'Auszahlbare Steuergutschriften senkten in den USA Kinderarmut deutlich, kaum Beschäftigungseffekte. Dagegen: Höhe offen, Abstimmung mit Grundsicherung und Steuerverfahren aufwendig.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=74', 'https://www.nationalacademies.org/news/2025/09/federal-tax-credits-in-2021-lifted-more-than-2-million-children-out-of-poverty-says-new-report', 'belegt', '2026-10-10', false, true, 'blind'),
  (8634, 21, 13, null, 'Bessere Unterstützung und Entlastung von Alleinerziehenden bei der Anrechnung von Unterhalt und Einkommen.', '{2102}', null, 1, 3, null, 'Geringere Anrechnung kann Alleinerziehenden mehr Einkommen lassen. Dagegen: unbestimmt, welche Anrechnung in welchem Umfang geändert wird.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8635, 21, 13, null, 'Elterngeld-Mindest- und Höchstbetrag werden erhöht; Ersatzrate für geringe Einkommen wird angehoben.', '{2102}', 8617, 1, 3, null, 'Erhöht das Einkommen von Familien mit kleinen Einkommen im ersten Lebensjahr. Dagegen: zeitlich begrenzt und bei Grundsicherungsbezug weitgehend angerechnet.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=82', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8636, 21, 13, null, 'Einführung einer Kindergrundsicherung; Antragsverfahren sollen verschlankt und stetig automatisiert werden.', '{2102,2103}', null, 2, 2, null, 'Simulationen erwarten durch Bündelung und bessere Inanspruchnahme weniger Kinderarmut. Dagegen: Leistungshöhe nicht genannt, Umsetzung verwaltungsaufwendig.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', 'https://www.diw.de/de/diw_01.c.926528.de/s_14695.html', 'belegt', '2026-10-10', false, true, 'blind'),
  (8637, 21, 13, null, 'Kindergrundsicherungs-Check informiert Eltern ab der Geburt aktiv über die Ansprüche ihrer Kinder.', '{2103}', 8614, 2, 3, null, 'Experimente zeigen: Information erhöht die Inanspruchnahme, mit Antragshilfe noch stärker. Dagegen: Effekte bleiben begrenzt und erreichen die Bedürftigsten schlechter.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', 'https://www.nber.org/papers/w24652', 'belegt', '2026-10-10', false, true, 'blind'),
  (8638, 21, 13, null, 'Grundsicherungsleistungen sollen direkt und ohne kompliziertes Beantragen nach klaren Regeln ausgezahlt werden.', '{2103}', 8613, 2, 2, null, 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=100', 'https://www.nber.org/papers/w10488', 'belegt', '2026-10-10', false, true, 'blind'),
  (8639, 21, 13, null, 'Mutterschaftsgeld auch für Selbstständige, finanziert über Umlage, auf die Selbstständige einzahlen.', '{2102}', null, 1, 2, null, 'Schließt eine Einkommenslücke selbstständiger Mütter rund um die Geburt. Dagegen: kleine Gruppe, kurze Dauer, Umlage muss erst aufgebaut werden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=82', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8640, 21, 13, null, 'Umgangsmehrbedarf bei Kindern in Trennungsfamilien im Steuer- und Sozialrecht berücksichtigen.', '{2102}', 8620, 1, 2, null, 'Deckt Mehrkosten, wenn Kinder in zwei Haushalten leben, und schließt so eine Lücke für Trennungsfamilien. Dagegen: betrifft eine begrenzte Gruppe, Ausgestaltung offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8641, 21, 13, null, 'Nationaler Aktionsplan für benachteiligte Kinder wird finanziell unterlegt.', '{2102}', null, 1, 3, null, 'Mehr Geld für Angebote benachteiligter Kinder kann Teilhabe stärken. Dagegen: Umfang und Maßnahmen unbestimmt.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8642, 21, 14, null, 'Familienleistungen einschließlich Elterngeld entbürokratisieren, digitalisieren und automatisieren, etwa mit KI-basierter Beantragung', '{2103}', 8613, 2, 2, null, 'Automatische Gewährung erhöht die Inanspruchnahme laut Forschung deutlich, Verwaltungshürden senken sie. Dagegen: Datenaustausch und IT brauchen mehrere Jahre, bei bereits hoch genutzten Leistungen wie Kindergeld ist der Zugewinn klein.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=30', 'https://www.nber.org/papers/w10488', 'belegt', '2026-10-10', false, true, 'blind'),
  (8643, 21, 14, null, 'Sozialleistungen wie Bürgergeld und Wohngeld in einer Leistung an einer staatlichen Stelle zusammenfassen', '{2103}', null, 2, 2, null, 'Eine Leistung an einer Stelle baut mehrere Zugangshürden zugleich ab, was die Inanspruchnahme fördert. Dagegen: großer Umbau über Zuständigkeiten hinweg, Dauer und Höhe offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=20', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8644, 21, 14, null, 'Steuerliche Absetzbarkeit von Betreuungskosten und Unterhaltsleistungen verbessern, um Familien und Alleinerziehende zu entlasten', '{2102}', null, 1, 3, null, 'Entlastet Familien und Alleinerziehende mit Betreuungs- und Unterhaltskosten. Dagegen: Steuerabzüge helfen kaum, wer wenig oder keine Steuern zahlt.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=14', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8645, 21, 15, null, 'Regelbedarfssätze der Grundsicherung an die tatsächliche Inflationsentwicklung anpassen', '{2101}', 8615, 1, 3, null, 'Sichert die Kaufkraft und verhindert, dass Regelsätze hinter der Inflation zurückbleiben. Dagegen: Eine Fortschreibung besteht bereits; die Lücke durch die Bemessung selbst bleibt unberührt.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=26', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8646, 21, 15, null, 'Nebenregeln (Schonvermögen, Autobesitz) der Grundsicherung im Alter gegenüber dem Bürgergeld ändern', '{2101}', null, 1, 3, null, 'Großzügigere Vermögensregeln verbessern die Lage älterer Grundsicherungsbeziehender. Dagegen: ändert die Höhe der Leistung nicht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=23', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8647, 21, 15, null, 'Betreuungsgehalt für Eltern, damit sie ihre Kinder bis zum 3. Geburtstag selbst betreuen können', '{2102}', null, 1, 1, null, 'Zahlung erhöht das Einkommen von Familien mit Kleinkindern. Dagegen: Studien zum früheren Betreuungsgeld zeigen weniger Kita-Nutzung und Müttererwerbstätigkeit; Höhe und Finanzierung offen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=148', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8648, 21, 15, null, 'Ehe-Start-Kredit für Erstanschaffungen bei Familiengründung, mit jedem Kind ein Teil erlassen', '{2102}', null, 1, 2, null, 'Hilft jungen Familien bei Anschaffungskosten. Dagegen: Kredit statt Zuschuss, an Ehe gebunden, arme Familien und Alleinerziehende kaum erreicht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=149', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8649, 21, 15, null, 'Bei jeder Geburt 20.000 Euro Rückzahlung aus Rentenbeiträgen oder entsprechende Freistellung von künftigen Zahlungen', '{2102}', null, 1, 1, null, 'Bringt Familien bei Geburt einen großen Betrag. Dagegen: Wer kaum Beiträge zahlt, etwa arme Haushalte, profitiert wenig; sehr hohe Kosten ohne Finanzierung.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=148', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8650, 21, 15, null, 'Beim Wechselmodell das Existenzminimum von Eltern und Kindern in beiden Haushalten sichern', '{2102}', 8620, 1, 2, null, 'Deckt Mehrkosten, wenn Kinder in zwei Haushalten leben, und schließt so eine Lücke für Trennungsfamilien. Dagegen: betrifft eine begrenzte Gruppe, Ausgestaltung offen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=155', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8651, 21, 16, null, 'Bürgergeld zu einer individuellen Mindestsicherung umbauen, Höhe an der Armutsgefährdungsgrenze ausrichten', '{2101}', null, 2, 1, null, 'Eine Mindestsicherung an der Armutsgefährdungsgrenze schließt die Einkommenslücke rechnerisch. Dagegen: sehr hohe Kosten ohne geklärte Finanzierung, Erwerbsanreize umstritten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8652, 21, 16, null, 'Kosten für Internetzugang und Geräte in der Grundsicherung berücksichtigen', '{2101}', null, 1, 3, null, 'Schließt eine konkrete Bedarfslücke (Internet, Geräte) in der Grundsicherung. Dagegen: deckt nur einen Teilbedarf, die übrige Bemessung bleibt gleich.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=57', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8653, 21, 16, null, 'Geldleistungen für Geflüchtete auf Höhe der Mindestsicherung statt Sachleistungen und Bezahlkarten', '{2101}', null, 1, 1, null, 'Höhere Geldleistungen schließen die Versorgungslücke für Geflüchtete. Dagegen: begrenzte Gruppe, Höhe an eine teure Mindestsicherung gekoppelt, Finanzierung offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=52', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8654, 21, 16, null, 'Eigenständige Kindergrundsicherung mit Kindergeld, Kinderzuschlag, Unterkunftskosten und einmaligen Bedarfen', '{2102}', null, 3, 1, null, 'Höhere gebündelte Kinderleistungen senkten etwa in Kanada Kinderarmut ohne Beschäftigungsverluste; Simulationen für Deutschland ähnlich. Dagegen: sehr hohe Kosten ohne geklärte Finanzierung.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', 'https://crdcn.ca/publication/evaluating-the-canada-child-benefit/', 'belegt', '2026-10-10', false, true, 'blind'),
  (8655, 21, 16, null, 'Unterhaltsvorschuss gerechter gestalten: Kindergeld weniger anrechnen, Bezugsalter erhöhen', '{2102}', 8619, 1, 2, null, 'Erhöht die Leistung für Alleinerziehende ohne Unterhalt. Dagegen: Im Grundsicherungsbezug wird der Unterhaltsvorschuss angerechnet, der Zugewinn kommt nur Haushalten oberhalb davon zugute.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8656, 21, 16, null, 'Steuergutschrift für Alleinerziehende, mindestens in Höhe des heutigen Entlastungsbetrags', '{2102}', 8616, 1, 3, null, 'Entlastet erwerbstätige Alleinerziehende, als Abzug von der Steuerschuld stärker bei kleinen Einkommen. Dagegen: Wer kaum Steuern zahlt, etwa im Grundsicherungsbezug, profitiert ohne Auszahlung kaum.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8657, 21, 16, null, 'Mindestbetrag beim Elterngeld anheben und an den Verbraucherpreisindex koppeln', '{2102}', 8617, 1, 3, null, 'Erhöht das Einkommen von Familien mit kleinen Einkommen im ersten Lebensjahr. Dagegen: zeitlich begrenzt und bei Grundsicherungsbezug weitgehend angerechnet.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8658, 21, 16, null, 'Freizeit- und Bildungseinrichtungen für Kinder und Jugendliche gebührenfrei stellen', '{2102}', null, 1, 1, null, 'Gebührenfreiheit erleichtert Kindern die Teilhabe. Dagegen: sichert den Lebensunterhalt nicht, Einrichtungen sind Sache von Ländern und Kommunen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8659, 21, 16, null, 'Rundfunkbeitrag für Berechtigte automatisch befreien', '{2103}', null, 1, 1, null, 'Automatische Befreiung erreicht Berechtigte, die sie nicht beantragen. Dagegen: kleiner Betrag, und der Rundfunkbeitrag ist Ländersache (Staatsvertrag).', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=55', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8660, 21, 16, null, 'Öffentliche Stellen sollen vor Ort beim Ausfüllen von Onlineanträgen helfen', '{2103}', 8614, 2, 3, null, 'Experimente zeigen: Information erhöht die Inanspruchnahme, mit Antragshilfe noch stärker. Dagegen: Effekte bleiben begrenzt und erreichen die Bedürftigsten schlechter.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=57', 'https://www.nber.org/papers/w24652', 'belegt', '2026-10-10', false, true, 'blind'),
  (8661, 21, 17, null, 'Bürokratische Hürden bei Leistungen abbauen, damit Hilfe ankommt.', '{2103}', null, 1, 3, null, 'Weniger Verwaltungshürden können die Inanspruchnahme erhöhen. Dagegen: ohne konkrete Schritte bleibt die Wirkung unbestimmt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=22', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8662, 21, 17, null, 'Steuerlichen Kinderfreibetrag an die Höhe des Kindergeldes angleichen.', '{2102}', 8618, 1, 2, null, 'Höheres Kindergeld erreicht alle Familien. Dagegen: Es wird auf die Grundsicherung angerechnet und senkt Armutsrisiken laut Evaluationen daher nur wenig; teuer bei geringer Zielgenauigkeit.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=32', null, 'gemischt', '2026-10-10', false, true, 'blind'),
  (8663, 21, 17, null, 'Der Bund soll Kindern das erste Jahr im Sportverein mit einem Zuschuss bezahlen.', '{2102}', null, 1, 3, null, 'Senkt Kosten der Teilhabe am Vereinssport für Kinder. Dagegen: kleiner, befristeter Betrag ohne Bezug zum Einkommen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'offen', '2026-10-10', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (8613, 21),
  (8614, 21),
  (8615, 21),
  (8616, 21),
  (8617, 21),
  (8618, 21),
  (8619, 21),
  (8620, 21),
  (8623, 21),
  (8628, 21),
  (8629, 21),
  (8633, 21),
  (8634, 21),
  (8636, 21),
  (8639, 21),
  (8641, 21),
  (8643, 21),
  (8644, 21),
  (8646, 21),
  (8647, 21),
  (8648, 21),
  (8649, 21),
  (8651, 21),
  (8652, 21),
  (8653, 21),
  (8654, 21),
  (8658, 21),
  (8659, 21),
  (8661, 21),
  (8663, 21);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (21, 11, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 12, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 13, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 14, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 15, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 16, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}'),
  (21, 17, null, 'massnahmen', null, '2026-10-10', true, '{2101,2102,2103}');

commit;
