-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 5 „Arbeitsplätze“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 5;
delete from public.abdeckung where thema_id = 5;
delete from public.pruef_einheiten where thema_id = 5;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (6089, 5, 'Stromsteuer und Netzentgelte senken', 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'belegt', null, 'bund', null, true, null),
  (6090, 5, 'Unternehmenssteuern senken', 'Niedrigere Unternehmenssteuern können Investitionen anregen, setzen aber nicht an den vom Sachverständigenrat genannten Gründen (Energiepreise, Lohnstückkosten) an; Studien zur Wirkung sind gemischt. Die Gegenfinanzierung ist offen.', 'gemischt', null, 'bund', null, true, null),
  (6091, 5, 'Bürokratie im nationalen Recht abbauen', 'Systematischer Abbau von Pflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Umsetzbar im nationalen Recht.', 'gemischt', null, 'bund', null, true, null),
  (6092, 5, 'Hinzuverdienst in Grundsicherung und Wohngeld weniger anrechnen', 'Geringere Anrechnung von Hinzuverdienst setzt direkt an der Ursache an; das ifo/ZEW-Gutachten für das Arbeitsministerium erwartet mehr Beschäftigung. Die Reform ist Bundesrecht, Kosten und Ausgestaltung sind offen.', 'belegt', null, 'bund', null, true, null),
  (6093, 5, 'Investitionsprämie für Unternehmen', 'Eine Investitionsprämie kann Investitionen vorziehen, setzt aber nicht an den vom Sachverständigenrat genannten Gründen an; Studien finden teils Mitnahmeeffekte. Umsetzbar per Bundesgesetz, Finanzierung offen.', 'gemischt', null, 'bund', null, true, null),
  (6094, 5, 'Mindestlohn auf 15 Euro anheben', 'Ein höherer Mindestlohn hebt die unteren Löhne, von denen im Osten mehr Menschen betroffen sind; Studien zur Erhöhung auf 12 Euro fanden kaum Beschäftigungsverluste. Den Abstand oberhalb des Mindestlohns schließt er nicht. Per Bundesgesetz umsetzbar.', 'belegt', null, 'bund', null, true, null),
  (6095, 5, 'Allgemeinverbindlicherklärung von Tarifverträgen erleichtern', 'Eine erleichterte Allgemeinverbindlicherklärung kann die Tarifbindung ganzer Branchen erhöhen, Tariftreue wirkt nur bei öffentlichen Aufträgen; die Wirkung auf die Tarifquote ist in Studien begrenzt belegt. Per Bundesgesetz umsetzbar.', 'gemischt', null, 'bund', null, true, null),
  (6096, 5, 'Geförderte Weiterbildung beim Wechsel von Beruf oder Branche', 'Geförderte Weiterbildung hilft Beschäftigten beim Wechsel in neue Branchen; Studien zeigen positive, aber je nach Maßnahme sehr unterschiedliche Effekte. Umsetzbar über die Arbeitsförderung, Finanzierung offen.', 'gemischt', null, 'bund', null, true, null),
  (6097, 5, 'Berichtspflichten mit EU-rechtlicher Grundlage abschaffen', 'Wegfall von Berichtspflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Ein Teil der genannten Pflichten beruht auf EU-Recht, das Deutschland nicht allein ändern kann.', 'gemischt', null, 'bund', null, true, null),
  (6098, 5, 'Schuldenbremse für Investitionen lockern oder abschaffen', 'Mehr Spielraum für öffentliche Investitionen setzt direkt an der Investitionslücke an. Eine Änderung der Schuldenbremse erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'belegt', null, 'bund', null, true, null)
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 5 and id not in (6089, 6090, 6091, 6092, 6093, 6094, 6095, 6096, 6097, 6098);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (5001, 5, 11, null, 'Stromsteuer für alle senken und Netzentgelte reduzieren', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'belegt', '2026-09-29', false, true, null),
  (5002, 5, 11, null, 'Unternehmensbesteuerung schrittweise auf höchstens 25 Prozent auf einbehaltene Gewinne senken', '{501}', 6090, 1, 2, null, 'Niedrigere Unternehmenssteuern können Investitionen anregen, setzen aber nicht an den vom Sachverständigenrat genannten Gründen (Energiepreise, Lohnstückkosten) an; Studien zur Wirkung sind gemischt. Die Gegenfinanzierung ist offen.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=16', null, 'gemischt', '2026-09-29', false, true, null),
  (5003, 5, 11, null, 'Menschen in Helfertätigkeiten auf dem Weg zur Fachkraft fördern; Anreize für berufliche Qualifikation', '{502}', null, 1, 2, null, 'Qualifizierung von Geringqualifizierten verbessert ihre Chancen im Strukturwandel; das Programm nennt aber kein konkretes Instrument. Umsetzbar über die Arbeitsförderung.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (5004, 5, 11, null, 'Jährliche Gesetze zum Bürokratieabbau, Bürokratiebremse „One in, two out“, Lieferkettengesetz abschaffen', '{505}', 6091, 2, 2, null, 'Systematischer Abbau von Pflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Umsetzbar im nationalen Recht.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=17', null, 'gemischt', '2026-09-29', false, true, null),
  (5005, 5, 11, null, 'Hinzuverdienstgrenzen und Transferentzugsraten reformieren, damit sich Arbeit mehr lohnt', '{506}', 6092, 2, 2, null, 'Geringere Anrechnung von Hinzuverdienst setzt direkt an der Ursache an; das ifo/ZEW-Gutachten für das Arbeitsministerium erwartet mehr Beschäftigung. Die Reform ist Bundesrecht, Kosten und Ausgestaltung sind offen.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=31', null, 'belegt', '2026-09-29', false, true, null),
  (5011, 5, 12, null, 'Übertragungsnetzentgelte auf 3 Cent pro Kilowattstunde deckeln; abgesenkte Stromsteuer entfristen', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=7', null, 'belegt', '2026-09-29', false, true, null),
  (5012, 5, 12, null, '„Made in Germany“-Investitionsprämie für bestehende Unternehmen und Neuansiedlungen', '{501}', 6093, 1, 2, null, 'Eine Investitionsprämie kann Investitionen vorziehen, setzt aber nicht an den vom Sachverständigenrat genannten Gründen an; Studien finden teils Mitnahmeeffekte. Umsetzbar per Bundesgesetz, Finanzierung offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=8', null, 'gemischt', '2026-09-29', false, true, null),
  (5013, 5, 12, null, 'Echte Mitbestimmung der Betriebsräte bei Personalplanung und betrieblicher Weiterbildung', '{502}', null, 1, 3, null, 'Mehr Mitsprache bei Weiterbildung kann Qualifizierung im Betrieb voranbringen, schafft aber selbst keine Weiterbildungsangebote. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=13', null, 'gemischt', '2026-09-29', false, true, null),
  (5014, 5, 12, null, 'Mindestlohn spätestens ab 2026 auf 15 Euro; Tarifbindung besonders in Ostdeutschland stärken', '{503}', 6094, 2, 3, null, 'Ein höherer Mindestlohn hebt die unteren Löhne, von denen im Osten mehr Menschen betroffen sind; Studien zur Erhöhung auf 12 Euro fanden kaum Beschäftigungsverluste. Den Abstand oberhalb des Mindestlohns schließt er nicht. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'belegt', '2026-09-29', false, true, null),
  (5015, 5, 12, null, 'Deutschlandfonds mit anfangs 100 Milliarden Euro für öffentliche und private Investitionen, im Rahmen der Schuldenregel', '{504}', null, 2, 2, null, 'Ein Investitionsfonds setzt an der Investitionslücke an; wie viel privates Kapital er tatsächlich mobilisiert, ist offen. Über finanzielle Transaktionen ohne Grundgesetzänderung umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=8', null, 'gemischt', '2026-09-29', false, true, null),
  (5016, 5, 12, null, 'Dokumentations- und Berichtspflichten zusammenführen, vereinfachen und digitalisieren; Praxischeck für neue Gesetze', '{505}', 6091, 2, 2, null, 'Systematischer Abbau von Pflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Umsetzbar im nationalen Recht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=9', null, 'gemischt', '2026-09-29', false, true, null),
  (5017, 5, 12, null, 'Bundestariftreuegesetz; Allgemeinverbindlicherklärung erleichtern; Verbandsklagerecht für Gewerkschaften', '{507}', 6095, 2, 3, null, 'Eine erleichterte Allgemeinverbindlicherklärung kann die Tarifbindung ganzer Branchen erhöhen, Tariftreue wirkt nur bei öffentlichen Aufträgen; die Wirkung auf die Tarifquote ist in Studien begrenzt belegt. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'gemischt', '2026-09-29', false, true, null),
  (5021, 5, 13, null, 'Netzentgelte für überregionale Stromleitungen aus dem Deutschlandfonds zahlen; Stromsteuer auf EU-Minimum senken', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=17', null, 'belegt', '2026-09-29', false, true, null),
  (5022, 5, 13, null, 'Befristete Investitionsprämie von 10 Prozent für alle Unternehmen', '{501}', 6093, 1, 2, null, 'Eine Investitionsprämie kann Investitionen vorziehen, setzt aber nicht an den vom Sachverständigenrat genannten Gründen an; Studien finden teils Mitnahmeeffekte. Umsetzbar per Bundesgesetz, Finanzierung offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=18', null, 'gemischt', '2026-09-29', false, true, null),
  (5023, 5, 13, null, 'Qualifizierungsgeld weiterentwickeln; selbst gewählte berufliche Weiterbildung sozial absichern', '{502}', 6096, 2, 2, null, 'Geförderte Weiterbildung hilft Beschäftigten beim Wechsel in neue Branchen; Studien zeigen positive, aber je nach Maßnahme sehr unterschiedliche Effekte. Umsetzbar über die Arbeitsförderung, Finanzierung offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=19', null, 'gemischt', '2026-09-29', false, true, null),
  (5024, 5, 13, null, 'Mindestlohn schrittweise erhöhen, zunächst 15 Euro, auch für unter 18-Jährige', '{503}', 6094, 2, 3, null, 'Ein höherer Mindestlohn hebt die unteren Löhne, von denen im Osten mehr Menschen betroffen sind; Studien zur Erhöhung auf 12 Euro fanden kaum Beschäftigungsverluste. Den Abstand oberhalb des Mindestlohns schließt er nicht. Per Bundesgesetz umsetzbar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=67', null, 'belegt', '2026-09-29', false, true, null),
  (5025, 5, 13, null, 'Deutschlandfonds für Investitionen von Bund, Ländern und Kommunen; Reform der Schuldenbremse', '{504}', null, 2, 2, null, 'Ein Investitionsfonds setzt an der Investitionslücke an; Umfang und Mobilisierung privaten Kapitals sind offen. Der Fonds ist ohne Grundgesetzänderung möglich, die Reform der Schuldenbremse nicht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=10', null, 'gemischt', '2026-09-29', false, true, null),
  (5026, 5, 13, null, 'Praxischeck ausweiten; Verwaltungsleistungen für Unternehmen bündeln, Daten nur einmal einreichen (Once-Only)', '{505}', 6091, 2, 2, null, 'Systematischer Abbau von Pflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Umsetzbar im nationalen Recht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=18', null, 'gemischt', '2026-09-29', false, true, null),
  (5027, 5, 13, null, 'Steuergutschriften für niedrige Einkommen, auch für Menschen, die mit Bürgergeld aufstocken', '{506}', null, 1, 2, null, 'Steuergutschriften auf Arbeitseinkommen können Arbeit lohnender machen; wie sie mit der Anrechnung im Bürgergeld zusammenspielen, lässt das Programm offen. Umsetzbar per Bundesgesetz, Finanzierung offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=74', null, 'gemischt', '2026-09-29', false, true, null),
  (5028, 5, 13, null, 'Allgemeinverbindlicherklärung von Tarifverträgen erleichtern', '{507}', 6095, 2, 3, null, 'Eine erleichterte Allgemeinverbindlicherklärung kann die Tarifbindung ganzer Branchen erhöhen, Tariftreue wirkt nur bei öffentlichen Aufträgen; die Wirkung auf die Tarifquote ist in Studien begrenzt belegt. Per Bundesgesetz umsetzbar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=67', null, 'gemischt', '2026-09-29', false, true, null),
  (5031, 5, 14, null, 'Stromsteuer auf EU-Mindestmaß senken; Netzentgelte umfassend reformieren', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=17', null, 'belegt', '2026-09-29', false, true, null),
  (5032, 5, 14, null, 'Unternehmenssteuerbelastung unter 25 Prozent: Solidaritätszuschlag abschaffen, Körperschaftsteuer senken', '{501}', 6090, 1, 2, null, 'Niedrigere Unternehmenssteuern können Investitionen anregen, setzen aber nicht an den vom Sachverständigenrat genannten Gründen (Energiepreise, Lohnstückkosten) an; Studien zur Wirkung sind gemischt. Die Gegenfinanzierung ist offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (5033, 5, 14, null, '„Lebenschancen-BAföG“ für Kursgebühren und bildungsbedingte Auszeiten; Freiraumkonto für Weiterbildung', '{502}', 6096, 2, 2, null, 'Geförderte Weiterbildung hilft Beschäftigten beim Wechsel in neue Branchen; Studien zeigen positive, aber je nach Maßnahme sehr unterschiedliche Effekte. Umsetzbar über die Arbeitsförderung, Finanzierung offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=10', null, 'gemischt', '2026-09-29', false, true, null),
  (5034, 5, 14, null, 'Steuersenkungen, Bürokratieabbau, Reallabore und Wirtschaftsförderung für kleine und mittlere Unternehmen in Ostdeutschland', '{503}', null, 1, 2, null, 'Stärkere Unternehmen im Osten können langfristig höhere Löhne ermöglichen; ob allgemeine Entlastungen die Lohnlücke verringern, ist offen. Umsetzbar, Finanzierung offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=12', null, 'gemischt', '2026-09-29', false, true, null),
  (5035, 5, 14, null, 'Infrastruktur im Rahmen der Schuldenbremse finanzieren, etwa über einen Finanzierungskreislauf Straße', '{504}', null, 1, 2, null, 'Das Programm erkennt den Investitionsbedarf an, nennt aber weder Umfang noch ein Instrument jenseits der Straße. Im Rahmen der Schuldenbremse umsetzbar.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=42', null, 'gemischt', '2026-09-29', false, true, null),
  (5036, 5, 14, null, 'Dreijähriges Bürokratie-Moratorium; ein bürokratiefreies Jahr ohne Berichtspflichten für Betriebe', '{505}', 6091, 2, 2, null, 'Systematischer Abbau von Pflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Umsetzbar im nationalen Recht.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=12', null, 'gemischt', '2026-09-29', false, true, null),
  (5037, 5, 14, null, 'Hinzuverdienstregeln in Grundsicherung und Wohngeld so reformieren, dass sich Arbeit spürbar mehr lohnt', '{506}', 6092, 2, 2, null, 'Geringere Anrechnung von Hinzuverdienst setzt direkt an der Ursache an; das ifo/ZEW-Gutachten für das Arbeitsministerium erwartet mehr Beschäftigung. Die Reform ist Bundesrecht, Kosten und Ausgestaltung sind offen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=20', null, 'belegt', '2026-09-29', false, true, null),
  (5041, 5, 15, null, 'CO₂-Abgabe abschaffen, Energiesteuer reduzieren, Stromsteuer auf das Minimum senken', '{501}', null, 2, 2, null, 'Niedrigere Steuern und Abgaben senken die Energiekosten; die Industrie zahlt ihren CO₂-Preis aber vor allem im EU-Emissionshandel, den Deutschland nicht allein abschaffen kann. Die Gegenfinanzierung ist offen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-29', false, true, null),
  (5042, 5, 15, null, 'Kohlekraftwerke länger laufen lassen, Wiedereinstieg in die Kernenergie, Nord-Stream-Pipelines reparieren und nutzen', '{501}', null, 2, 1, null, 'Mehr Angebot und günstigeres Gas könnten Energiekosten senken; neue Kernkraftwerke wirken erst nach vielen Jahren. EU-Sanktionen, die EU-Regeln zum Ausstieg aus russischem Gas und lange Bauzeiten stehen entgegen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-29', false, true, null),
  (5043, 5, 15, null, 'Unternehmenssteuern auf ein international konkurrenzfähiges Niveau senken', '{501}', 6090, 1, 2, null, 'Niedrigere Unternehmenssteuern können Investitionen anregen, setzen aber nicht an den vom Sachverständigenrat genannten Gründen (Energiepreise, Lohnstückkosten) an; Studien zur Wirkung sind gemischt. Die Gegenfinanzierung ist offen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (5044, 5, 15, null, 'Intensive Beratung, Weiterbildung und Vermittlung schon während des Arbeitslosengeldbezugs', '{502}', null, 1, 2, null, 'Frühe Beratung und Weiterbildung verbessern die Chancen nach einem Stellenverlust; das Programm nennt aber kein neues Instrument. Umsetzbar über die Arbeitsförderung.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=22', null, 'gemischt', '2026-09-29', false, true, null),
  (5045, 5, 15, null, 'Straßen, Schienen und Brücken planvoll sanieren; Planungs- und Genehmigungsverfahren vereinfachen', '{504}', null, 1, 2, null, 'Schnellere Verfahren und Sanierung setzen an der Investitionslücke an; das Programm nennt aber keinen Umfang und keine Finanzierung. Umsetzbar per Bundesgesetz.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (5046, 5, 15, null, 'Lieferkettengesetz, EU-Lieferkettenrichtlinie und Verpackungsgesetz abschaffen, Nachhaltigkeitsberichte abbauen, Pflichten drastisch reduzieren', '{505}', 6097, 2, 1, null, 'Wegfall von Berichtspflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Ein Teil der genannten Pflichten beruht auf EU-Recht, das Deutschland nicht allein ändern kann.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-29', false, true, null),
  (5047, 5, 15, null, 'Bürgergeldempfänger nach sechs Monaten zu gemeinnütziger Arbeit heranziehen („Aktivierende Grundsicherung“)', '{506}', null, 1, 2, null, 'Arbeitspflichten erhöhen den Druck, machen zusätzliche Arbeit aber nicht lohnender; Studien zu Arbeitsgelegenheiten finden kaum Effekte auf reguläre Beschäftigung. Umsetzbar per Bundesgesetz.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=26', null, 'gemischt', '2026-09-29', false, true, null),
  (5051, 5, 16, null, 'Neue Netzentgeltstruktur; Stromsteuer auf europäischen Mindeststeuersatz senken', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', null, 'belegt', '2026-09-29', false, true, null),
  (5052, 5, 16, null, 'Industriestrompreis für energieintensive Betriebe aus einem auf 65 Milliarden Euro jährlich ausgebauten Klima- und Transformationsfonds', '{501}', null, 2, 2, null, 'Ein Industriestrompreis senkt die Energiekosten energieintensiver Betriebe direkt; Ökonominnen und Ökonomen streiten über Kosten und Fehlanreize. Braucht eine beihilferechtliche Genehmigung der EU.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=30', null, 'gemischt', '2026-09-29', false, true, null),
  (5053, 5, 16, null, 'Weiterqualifizierungsgeld von 90 Prozent des letzten Gehalts beim Wechsel von Beruf oder Branche', '{502}', 6096, 2, 2, null, 'Geförderte Weiterbildung hilft Beschäftigten beim Wechsel in neue Branchen; Studien zeigen positive, aber je nach Maßnahme sehr unterschiedliche Effekte. Umsetzbar über die Arbeitsförderung, Finanzierung offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=31', null, 'gemischt', '2026-09-29', false, true, null),
  (5054, 5, 16, null, 'Mindestlohn auf mindestens 15 Euro, spätestens 2026 auf 16 Euro; Tarifbindung stärken – gleicher Lohn in Ost und West', '{503}', 6094, 2, 3, null, 'Ein höherer Mindestlohn hebt die unteren Löhne, von denen im Osten mehr Menschen betroffen sind; Studien zur Erhöhung auf 12 Euro fanden kaum Beschäftigungsverluste. Den Abstand oberhalb des Mindestlohns schließt er nicht. Per Bundesgesetz umsetzbar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=45', null, 'belegt', '2026-09-29', false, true, null),
  (5055, 5, 16, null, 'Schuldenbremse abschaffen, um in Bildung, Brücken, Bus und Bahn und die Wirtschaft zu investieren', '{504}', 6098, 2, 1, null, 'Mehr Spielraum für öffentliche Investitionen setzt direkt an der Investitionslücke an. Eine Änderung der Schuldenbremse erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=4', null, 'belegt', '2026-09-29', false, true, null),
  (5056, 5, 16, null, 'Aktionsplan für Tarifbindung, Bundestariftreuegesetz, Allgemeinverbindlicherklärung auch ohne Zustimmung der Arbeitgeberseite', '{507}', null, 2, 2, null, 'Eine erleichterte Allgemeinverbindlicherklärung kann die Tarifbindung ganzer Branchen erhöhen; die Wirkung ist in Studien begrenzt belegt. Eine Erklärung gegen den Willen der Arbeitgeberseite ist verfassungsrechtlich umstritten (Tarifautonomie).', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=26', null, 'gemischt', '2026-09-29', false, true, null),
  (5061, 5, 17, null, 'Mit Russland über günstiges Erdgas durch den verbliebenen Nord-Stream-Strang verhandeln', '{501}', null, 2, 1, null, 'Günstigeres Pipelinegas aus Russland würde Energiekosten senken; die Versorgung wäre aber von einem einzelnen Lieferanten abhängig. EU-Sanktionen, die EU-Regeln zum Ausstieg aus russischem Gas und die fehlende Zertifizierung der Leitung stehen entgegen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-29', false, true, null),
  (5062, 5, 17, null, 'CO₂-Preis abschaffen', '{501}', null, 1, 1, null, 'Die Industrie zahlt ihren CO₂-Preis vor allem im EU-Emissionshandel, den Deutschland nicht allein abschaffen kann; die Wirkung auf die Industriekosten ist deshalb gering.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-29', false, true, null),
  (5063, 5, 17, null, 'Instandhaltung und Ausbau der Energienetze aus öffentlichen Mitteln statt über den Strompreis finanzieren', '{501}', null, 2, 1, null, 'Netzentgelte aus dem Strompreis zu nehmen senkt die Energiekosten direkt und deutlich. Die Netzkosten liegen bei vielen Milliarden Euro im Jahr; die Finanzierung ist offen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', null, 'belegt', '2026-09-29', false, true, null),
  (5064, 5, 17, null, 'Gesetzlichen Mindestlohn unverzüglich auf 15 Euro anheben', '{503}', 6094, 2, 3, null, 'Ein höherer Mindestlohn hebt die unteren Löhne, von denen im Osten mehr Menschen betroffen sind; Studien zur Erhöhung auf 12 Euro fanden kaum Beschäftigungsverluste. Den Abstand oberhalb des Mindestlohns schließt er nicht. Per Bundesgesetz umsetzbar.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'belegt', '2026-09-29', false, true, null),
  (5065, 5, 17, null, 'Investitionen in Infrastruktur aus der Schuldenbremse ausklammern; großes Investitionsprogramm', '{504}', 6098, 2, 1, null, 'Mehr Spielraum für öffentliche Investitionen setzt direkt an der Investitionslücke an. Eine Änderung der Schuldenbremse erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=15', null, 'belegt', '2026-09-29', false, true, null),
  (5066, 5, 17, null, 'Nachhaltigkeitsberichterstattung aussetzen, Lieferkettengesetz reformieren, kleine und mittlere Unternehmen von Berichtspflichten befreien', '{505}', 6097, 2, 1, null, 'Wegfall von Berichtspflichten setzt an den Bürokratiekosten an; bisherige Programme haben die Kosten laut Normenkontrollrat nur langsam gesenkt. Ein Teil der genannten Pflichten beruht auf EU-Recht, das Deutschland nicht allein ändern kann.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=18', null, 'gemischt', '2026-09-29', false, true, null),
  (5067, 5, 17, null, 'Öffentliche Aufträge und Subventionen nur an Unternehmen mit Tariflohn; Allgemeinverbindlicherklärung erleichtern', '{507}', 6095, 2, 3, null, 'Eine erleichterte Allgemeinverbindlicherklärung kann die Tarifbindung ganzer Branchen erhöhen, Tariftreue wirkt nur bei öffentlichen Aufträgen; die Wirkung auf die Tarifquote ist in Studien begrenzt belegt. Per Bundesgesetz umsetzbar.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (8479, 5, 18, null, 'Effektive Unternehmenssteuerbelastung auf den OECD-Durchschnitt senken', '{501}', 6090, 1, 2, null, 'Niedrigere Unternehmenssteuern können Investitionen anregen, setzen aber nicht an den vom Sachverständigenrat genannten Gründen (Energiepreise, Lohnstückkosten) an; Studien zur Wirkung sind gemischt. Die Gegenfinanzierung ist offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=54', null, 'gemischt', '2026-10-07', false, true, null),
  (8480, 5, 18, null, 'Energiesteuer auf das EU-rechtliche Minimum senken', '{501}', null, 1, 2, null, 'Senkt Kosten für Gas und Kraftstoffe; das Produzierende Gewerbe erhält aber schon Ermäßigungen, der Großteil der Entlastung ginge an Verkehr und Haushalte. Steuer ist im EU-Rahmen national gestaltbar, die Einnahmeausfälle sind hoch und ungedeckt.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', null, 'gemischt', '2026-10-07', false, true, 'blind'),
  (8481, 5, 18, null, 'Teil der Netzentgelte aus dem Bundeshaushalt finanzieren', '{501}', 6089, 2, 2, null, 'Niedrigere Stromsteuer und Netzentgelte senken direkt die Energiekosten, die der Sachverständigenrat als Grund der Industrieschwäche nennt; allein gleichen sie den Kostenabstand aber nicht aus. Die Gegenfinanzierung ist offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', null, 'belegt', '2026-10-07', false, true, null),
  (8482, 5, 18, null, 'Pflicht für Großunternehmen, bei betriebsbedingten Kündigungen Weiterbildung in zukunftsfähigen Berufen zu finanzieren', '{502}', null, 2, 2, null, 'Weiterbildung nach Entlassung erleichtert den Wechsel in wachsende Branchen; das IAB fand für Transfergesellschaften höhere Beschäftigung nach fünf Jahren, aber keinen Lohneffekt. Per Bundesgesetz möglich, belastet aber Unternehmen im Abbau zusätzlich.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=52', 'https://iab.de/publication/?id=1410534', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8483, 5, 18, null, 'Recht auf Freistellung für Weiterbildung in zukunftsorientierten Berufen', '{502}', null, 1, 2, null, 'Freistellung erleichtert Weiterbildung, doch Bildungsurlaub wird in den Ländern nur von etwa 1-3 % genutzt; die WIFO-Evaluation der österreichischen Bildungskarenz fand gemischte Beschäftigungseffekte. Bundesgesetz möglich, Kostenträger offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=52', 'https://ideas.repec.org/b/wfo/wstudy/71089.html', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8484, 5, 18, null, 'Umschulungsprogramme für den Wechsel in Berufe mit Fachkräftemangel', '{502}', 6096, 2, 2, null, 'Geförderte Weiterbildung hilft Beschäftigten beim Wechsel in neue Branchen; Studien zeigen positive, aber je nach Maßnahme sehr unterschiedliche Effekte. Umsetzbar über die Arbeitsförderung, Finanzierung offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=120', null, 'gemischt', '2026-10-07', false, true, null),
  (8485, 5, 18, null, 'Investitionen aus der Schuldenbremse ausnehmen (Goldene Regel Plus)', '{504}', 6098, 2, 1, null, 'Mehr Spielraum für öffentliche Investitionen setzt direkt an der Investitionslücke an. Eine Änderung der Schuldenbremse erfordert eine Grundgesetzänderung mit Zweidrittelmehrheit.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=22', null, 'belegt', '2026-10-07', false, true, null),
  (8486, 5, 18, null, 'Infrastrukturfonds für private Investitionen und massive Infrastrukturinvestitionen', '{504}', null, 1, 2, null, 'Ein Fonds kann privates Kapital für Infrastruktur mobilisieren, ersetzt aber kaum fehlende öffentliche Investitionen; der Bundesrechnungshof fand privat finanzierte Autobahnprojekte teurer als Haushaltsfinanzierung. Ausgestaltung und Volumen offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=65', null, 'gemischt', '2026-10-07', false, true, 'blind'),
  (8487, 5, 18, null, 'Berichtspflichten des Lieferkettengesetzes streichen und an EU-Recht angleichen', '{505}', null, 1, 3, null, 'Streichung setzt an Berichtspflichten an, laut Gesetzentwurf der Bundesregierung entlastet sie aber nur um rund 4 Mio. Euro jährlich, gemessen an rund 64 Mrd. Euro Bürokratiekosten sehr wenig. Nationales Recht, per Bundesgesetz rasch umsetzbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', null, 'belegt', '2026-10-07', false, true, 'blind'),
  (8488, 5, 18, null, 'Genehmigungsverfahren für Industrieanlagen vereinfachen und auf drei Monate begrenzen', '{505}', null, 2, 1, null, 'Einfachere Verfahren senken Aufwand für Unternehmen; laut Normenkontrollrat bremsen Prüfumfang, Personalmangel und fehlende Digitalisierung. Eine Frist von drei Monaten ist bei EU-Vorgaben zu UVP und Beteiligung und knappem Personal kaum erreichbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', 'https://www.normenkontrollrat.bund.de/Webs/NKR/SharedDocs/Kurzmeldungen/DE/Presse/2025-07-bimsch-projekt.html', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8489, 5, 18, null, 'Tarifbindung stärken', '{507}', null, 1, 2, null, 'Setzt an der geringen Tarifbindung an, nennt aber keinen Weg (etwa Allgemeinverbindlichkeit, Tariftreue); ohne Instrument ist keine deutliche Wirkung abschätzbar. Umsetzbarkeit hängt vom gewählten Weg ab.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=89', null, 'offen', '2026-10-07', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (5003, 5),
  (5013, 5),
  (5015, 5),
  (5025, 5),
  (5027, 5),
  (5034, 5),
  (5035, 5),
  (5041, 5),
  (5042, 5),
  (5044, 5),
  (5045, 5),
  (5047, 5),
  (5052, 5),
  (5056, 5),
  (5061, 5),
  (5062, 5),
  (5063, 5),
  (6089, 5),
  (6090, 5),
  (6091, 5),
  (6092, 5),
  (6093, 5),
  (6094, 5),
  (6095, 5),
  (6096, 5),
  (6097, 5),
  (6098, 5),
  (8480, 5),
  (8482, 5),
  (8483, 5),
  (8486, 5),
  (8487, 5),
  (8488, 5),
  (8489, 5);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (5, 11, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 12, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 13, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 14, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 15, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 16, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 17, null, 'massnahmen', null, '2026-09-29', true, null),
  (5, 18, null, 'massnahmen', null, '2026-10-07', true, '{501,502,503,504,505,506,507}');

commit;
