-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 1 „Arzttermine“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 1;
delete from public.abdeckung where thema_id = 1;
delete from public.pruef_einheiten where thema_id = 1;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (6677, 1, 'Hausarztpraxis als erste Anlaufstelle (Primärarztsystem)', 'Lenkt Patientinnen und Patienten gezielter und kann unnötige Facharztbesuche vermeiden; die Erfahrungen aus Ländern mit Primärarztsystem sind überwiegend positiv. Es setzt aber voraus, dass genug Hausarztpraxen da sind, die schon heute knapp sind.', 'gemischt', null, 'bund', null, true, null),
  (6678, 1, 'Andere Gesundheitsberufe übernehmen mehr Aufgaben (z. B. Advanced Practice Nurses, Gemeindeschwestern)', 'Entlastet Ärztinnen und Ärzte, sodass mehr Termine frei werden; internationale Studien zeigen gute Qualität bei übertragenen Aufgaben. Braucht neue Ausbildungswege und Änderungen im Berufsrecht, das dauert.', 'belegt', null, 'bund', null, true, null),
  (6679, 1, 'Kommunale MVZ und Gesundheitszentren fördern', 'Angestelltenverhältnisse und Teamarbeit entsprechen den Wünschen vieler junger Ärztinnen und Ärzte und können Praxissitze in unterversorgten Regionen besetzen; wie viele Zentren tatsächlich entstehen, hängt von Kommunen und Finanzierung ab.', 'gemischt', null, 'bund', null, true, null),
  (6680, 1, 'Budgetierung ärztlicher Leistungen aufheben', 'Voll bezahlte Leistungen machen Kassenpatienten für Praxen attraktiver und verringern den Vergütungsabstand zu Privatversicherten; ob dadurch spürbar mehr Termine entstehen, ist nicht belegt, und die Mehrkosten tragen die Beitragszahlenden.', 'gemischt', null, 'bund', null, true, null),
  (6681, 1, 'Einheitliche Vergütung für gesetzlich und privat Versicherte (Bürgerversicherung)', 'Nimmt Praxen den finanziellen Anreiz, Privatversicherte bei Terminen vorzuziehen; ob die Wartezeiten insgesamt sinken, hängt von der Höhe der neuen Vergütung ab. Der Umbau der privaten Krankenversicherung ist rechtlich und praktisch sehr aufwendig.', 'gemischt', null, 'bund', null, true, null),
  (6824, 1, 'Mehr Studienplätze in der Medizin', 'Mehr Absolventinnen und Absolventen setzen am Nachwuchsmangel an, wirken aber erst nach etwa zwölf Jahren Studium und Weiterbildung; ob sie Hausärzte auf dem Land werden, ist offen. Studienplätze finanzieren die Länder, der Bund kann nur mitfinanzieren.', 'gemischt', null, 'bund', null, true, null)
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 1 and id not in (6677, 6678, 6679, 6680, 6681, 6824);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (6682, 1, 11, null, 'Hausarztpraxen sollen Patientinnen und Patienten stärker steuern, um Wartezeiten zu senken', '{102}', 6677, 2, 2, null, 'Lenkt Patientinnen und Patienten gezielter und kann unnötige Facharztbesuche vermeiden; die Erfahrungen aus Ländern mit Primärarztsystem sind überwiegend positiv. Es setzt aber voraus, dass genug Hausarztpraxen da sind, die schon heute knapp sind.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=70', null, 'gemischt', '2026-09-30', false, true, null),
  (6683, 1, 11, null, 'Andere Gesundheitsberufe sollen mehr Verantwortung für die Versorgung übernehmen', '{102}', 6678, 2, 2, null, 'Entlastet Ärztinnen und Ärzte, sodass mehr Termine frei werden; internationale Studien zeigen gute Qualität bei übertragenen Aufgaben. Braucht neue Ausbildungswege und Änderungen im Berufsrecht, das dauert.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', null, 'belegt', '2026-09-30', false, true, null),
  (6684, 1, 12, null, 'Gründung kommunaler MVZ erleichtern', '{101}', 6679, 2, 2, null, 'Angestelltenverhältnisse und Teamarbeit entsprechen den Wünschen vieler junger Ärztinnen und Ärzte und können Praxissitze in unterversorgten Regionen besetzen; wie viele Zentren tatsächlich entstehen, hängt von Kommunen und Finanzierung ab.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=29', null, 'gemischt', '2026-09-30', false, true, null),
  (6685, 1, 12, null, 'Advanced Practice Nurses und Gemeindeschwestern einführen', '{102}', 6678, 2, 2, null, 'Entlastet Ärztinnen und Ärzte, sodass mehr Termine frei werden; internationale Studien zeigen gute Qualität bei übertragenen Aufgaben. Braucht neue Ausbildungswege und Änderungen im Berufsrecht, das dauert.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=29', null, 'belegt', '2026-09-30', false, true, null),
  (6686, 1, 12, null, 'Termingarantie: Gesetzlich Versicherte sollen so schnell wie Privatversicherte einen Termin bekommen, sonst sinkt ihr Beitrag', '{102,103}', null, 1, 2, null, 'Setzt Krankenkassen und Kassenärztliche Vereinigungen unter Druck, Termine zu vermitteln, schafft aber selbst keine zusätzlichen Termine; Terminservicestellen gibt es bereits.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=29', null, 'offen', '2026-09-30', false, true, null),
  (6687, 1, 12, null, 'Bürgerversicherung mit einheitlichem Vergütungssystem', '{103}', 6681, 2, 1, null, 'Nimmt Praxen den finanziellen Anreiz, Privatversicherte bei Terminen vorzuziehen; ob die Wartezeiten insgesamt sinken, hängt von der Höhe der neuen Vergütung ab. Der Umbau der privaten Krankenversicherung ist rechtlich und praktisch sehr aufwendig.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=29', null, 'gemischt', '2026-09-30', false, true, null),
  (6688, 1, 13, null, 'Hausärztlich-zentrierte Primärversorgung stärken', '{102}', 6677, 2, 2, null, 'Lenkt Patientinnen und Patienten gezielter und kann unnötige Facharztbesuche vermeiden; die Erfahrungen aus Ländern mit Primärarztsystem sind überwiegend positiv. Es setzt aber voraus, dass genug Hausarztpraxen da sind, die schon heute knapp sind.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=88', null, 'gemischt', '2026-09-30', false, true, null),
  (6689, 1, 13, null, 'Zusammenarbeit mit anderen Gesundheitsberufen wie Community Health Nurses ausbauen', '{102}', 6678, 2, 2, null, 'Entlastet Ärztinnen und Ärzte, sodass mehr Termine frei werden; internationale Studien zeigen gute Qualität bei übertragenen Aufgaben. Braucht neue Ausbildungswege und Änderungen im Berufsrecht, das dauert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=88', null, 'belegt', '2026-09-30', false, true, null),
  (6690, 1, 13, null, 'Gründung kommunaler MVZ und Primärversorgungszentren fördern', '{101}', 6679, 2, 2, null, 'Angestelltenverhältnisse und Teamarbeit entsprechen den Wünschen vieler junger Ärztinnen und Ärzte und können Praxissitze in unterversorgten Regionen besetzen; wie viele Zentren tatsächlich entstehen, hängt von Kommunen und Finanzierung ab.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=88', null, 'gemischt', '2026-09-30', false, true, null),
  (6691, 1, 13, null, 'Mehr Sprechstunden für gesetzlich Versicherte', '{103}', null, 1, 3, null, 'Verschiebt Termine zu gesetzlich Versicherten; Mindestsprechstunden gibt es schon, und ohne mehr Ärztinnen und Ärzte entstehen insgesamt kaum zusätzliche Termine.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=88', null, 'offen', '2026-09-30', false, true, null),
  (6692, 1, 13, null, 'Anspruch auf Patientenlotsen', '{102}', null, 1, 2, null, 'Lotsen können Wege durch das System verkürzen, vor allem für chronisch Kranke; für die Terminlage insgesamt ist die Wirkung klein, und es braucht zusätzliches Personal.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=89', null, 'offen', '2026-09-30', false, true, null),
  (6693, 1, 14, null, 'Primärarztsystem: Haus- und Kinderärzte als erste Anlaufstelle', '{102}', 6677, 2, 2, null, 'Lenkt Patientinnen und Patienten gezielter und kann unnötige Facharztbesuche vermeiden; die Erfahrungen aus Ländern mit Primärarztsystem sind überwiegend positiv. Es setzt aber voraus, dass genug Hausarztpraxen da sind, die schon heute knapp sind.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=33', null, 'gemischt', '2026-09-30', false, true, null),
  (6694, 1, 14, null, 'Ungekürzte Vergütung, Behandlung ohne Budgetierung', '{101,103}', 6680, 1, 2, null, 'Voll bezahlte Leistungen machen Kassenpatienten für Praxen attraktiver und verringern den Vergütungsabstand zu Privatversicherten; ob dadurch spürbar mehr Termine entstehen, ist nicht belegt, und die Mehrkosten tragen die Beitragszahlenden.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=33', null, 'gemischt', '2026-09-30', false, true, null),
  (6695, 1, 15, null, 'Budgetierung ärztlicher Leistungen beenden', '{101,103}', 6680, 1, 2, null, 'Voll bezahlte Leistungen machen Kassenpatienten für Praxen attraktiver und verringern den Vergütungsabstand zu Privatversicherten; ob dadurch spürbar mehr Termine entstehen, ist nicht belegt, und die Mehrkosten tragen die Beitragszahlenden.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=28', null, 'gemischt', '2026-09-30', false, true, null),
  (6696, 1, 15, null, 'Gestaffelte Bonus- und Rückvergütungssysteme gegen Bagatellbehandlungen', '{102}', null, 1, 2, null, 'Finanzielle Anreize können Arztbesuche etwas senken; die Praxisgebühr von 2004 bis 2012 hatte nur kurz Wirkung und belastete vor allem Menschen mit geringem Einkommen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=28', null, 'gemischt', '2026-09-30', false, true, null),
  (6697, 1, 15, null, 'Finanzielle und organisatorische Niederlassungshilfen für Ärzte auf dem Land', '{101}', null, 1, 3, null, 'Zuschüsse für die Niederlassung gibt es bereits bei Kassenärztlichen Vereinigungen und Ländern; sie wirken bisher nur begrenzt, weil viele junge Ärztinnen und Ärzte eine Anstellung bevorzugen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=28', null, 'gemischt', '2026-09-30', false, true, null),
  (6698, 1, 15, null, 'Mehr Studienplätze in Human- und Zahnmedizin', '{101}', 6824, 2, 2, null, 'Mehr Absolventinnen und Absolventen setzen am Nachwuchsmangel an, wirken aber erst nach etwa zwölf Jahren Studium und Weiterbildung; ob sie Hausärzte auf dem Land werden, ist offen. Studienplätze finanzieren die Länder, der Bund kann nur mitfinanzieren.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (6699, 1, 16, null, 'Kommunale Versorgungszentren als Rückgrat der wohnortnahen Versorgung fördern', '{101}', 6679, 2, 2, null, 'Angestelltenverhältnisse und Teamarbeit entsprechen den Wünschen vieler junger Ärztinnen und Ärzte und können Praxissitze in unterversorgten Regionen besetzen; wie viele Zentren tatsächlich entstehen, hängt von Kommunen und Finanzierung ab.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=19', null, 'gemischt', '2026-09-30', false, true, null),
  (6700, 1, 16, null, 'Kleinere Versorgungsbezirke, von Ländern und Kommunen bestimmt', '{101}', null, 1, 2, null, 'Kleinere Planungsbereiche machen Unterversorgung in einzelnen Stadtteilen und Dörfern sichtbar und können Niederlassungen dorthin lenken; zusätzliche Ärztinnen und Ärzte entstehen dadurch nicht.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=19', null, 'offen', '2026-09-30', false, true, null),
  (6701, 1, 16, null, 'Befugnisse der Heilberufe ausweiten', '{102}', 6678, 2, 2, null, 'Entlastet Ärztinnen und Ärzte, sodass mehr Termine frei werden; internationale Studien zeigen gute Qualität bei übertragenen Aufgaben. Braucht neue Ausbildungswege und Änderungen im Berufsrecht, das dauert.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=19', null, 'belegt', '2026-09-30', false, true, null),
  (6702, 1, 16, null, 'Privatversicherte in die gesetzliche Krankenversicherung übernehmen', '{103}', 6681, 2, 1, null, 'Nimmt Praxen den finanziellen Anreiz, Privatversicherte bei Terminen vorzuziehen; ob die Wartezeiten insgesamt sinken, hängt von der Höhe der neuen Vergütung ab. Der Umbau der privaten Krankenversicherung ist rechtlich und praktisch sehr aufwendig.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=18', null, 'gemischt', '2026-09-30', false, true, null),
  (6825, 1, 17, null, 'Bürgerversicherung statt Zwei-Klassen-Medizin', '{103}', 6681, 2, 1, null, 'Nimmt Praxen den finanziellen Anreiz, Privatversicherte bei Terminen vorzuziehen; ob die Wartezeiten insgesamt sinken, hängt von der Höhe der neuen Vergütung ab. Der Umbau der privaten Krankenversicherung ist rechtlich und praktisch sehr aufwendig.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=26', null, 'gemischt', '2026-09-30', false, true, null),
  (6826, 1, 17, null, 'Hausärzte höher vergüten', '{101}', null, 1, 2, null, 'Macht die Niederlassung als Hausarzt attraktiver; ob das allein genug Nachwuchs bringt, ist offen, denn viele junge Ärztinnen und Ärzte wünschen sich vor allem Anstellung und Teilzeit. Die Mehrkosten tragen die Beitragszahlenden.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=27', null, 'gemischt', '2026-09-30', false, true, null),
  (6827, 1, 17, null, 'Mehr Medizinstudienplätze', '{101}', 6824, 2, 2, null, 'Mehr Absolventinnen und Absolventen setzen am Nachwuchsmangel an, wirken aber erst nach etwa zwölf Jahren Studium und Weiterbildung; ob sie Hausärzte auf dem Land werden, ist offen. Studienplätze finanzieren die Länder, der Bund kann nur mitfinanzieren.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=27', null, 'gemischt', '2026-09-30', false, true, null),
  (8453, 1, 18, null, 'Für Fachpraxisbesuche ohne Überweisung wird eine Selbstbeteiligung eingeführt (Hausarztzentrierung), um Fachpraxen zu entlasten.', '{102}', null, 1, 3, null, 'Hausarztsteuerung kann Facharztbesuche verringern (Studien zum Gatekeeping); die Praxisgebühr mit Ausnahme bei Überweisung zeigte aber kaum Steuerungswirkung und schreckte eher Ärmere ab. Per Bundesgesetz rasch umsetzbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=125', 'https://ideas.repec.org/p/zbw/rwipos/16.html', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8454, 1, 18, null, 'Multiprofessionelle regionale Versorgungszentren mit Gesundheitsfachberufen werden eingerichtet.', '{101}', 6679, 2, 2, null, 'Angestelltenverhältnisse und Teamarbeit entsprechen den Wünschen vieler junger Ärztinnen und Ärzte und können Praxissitze in unterversorgten Regionen besetzen; wie viele Zentren tatsächlich entstehen, hängt von Kommunen und Finanzierung ab.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=125', null, 'gemischt', '2026-10-07', false, true, null),
  (8455, 1, 18, null, 'Mobile Gesundheitseinheiten mit regelmäßigen Sprechstunden kommen in entlegene Gebiete.', '{101}', null, 1, 2, null, 'Bringt Sprechstunden zu wenig mobilen Menschen in entlegenen Orten; Studien und Pilotprojekte zeigen gute Auslastung. Ersetzt aber keine fehlenden Praxen, braucht selbst ärztliches Personal und ist teuer; die Sicherstellung liegt bei den KVen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=126', 'https://nnphi.org/resources/the-scope-and-impact-of-mobile-health-clinics-in-the-united-states-a-literature-review/', 'gemischt', '2026-10-07', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (6677, 1),
  (6678, 1),
  (6679, 1),
  (6680, 1),
  (6681, 1),
  (6686, 1),
  (6691, 1),
  (6692, 1),
  (6696, 1),
  (6697, 1),
  (6700, 1),
  (6824, 1),
  (6826, 1),
  (8453, 1),
  (8455, 1);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (1, 11, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 12, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 13, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 14, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 15, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 16, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 17, null, 'massnahmen', null, '2026-09-30', true, null),
  (1, 18, null, 'massnahmen', null, '2026-10-07', true, '{101,102,103}');

commit;
