-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 21 „Armut und Kinderarmut“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 21;
delete from public.abdeckung where thema_id = 21;
delete from public.pruef_einheiten where thema_id = 21;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (8821, 21, 'Regelsatz der Grundsicherung regelmäßig an Preisentwicklung anpassen (Bund)', 'Zeitnahe Anpassung verhindert reale Kaufkraftverluste wie 2022/23. Die Fortschreibung mit Mischindex und Besitzschutz besteht aber schon; eine Lücke durch zu knappe Bemessung schließt sie nicht.', 'belegt', 'https://www.bundesregierung.de/breg-de/suche/buergergeld-2025-2248000', 'bund', null, true, 'blind'),
  (8822, 21, 'Anstieg des Regelsatzes begrenzen oder Regelsatz absenken (Bund)', 'Ein niedrigerer oder langsamer steigender Regelsatz vergrößert eine Versorgungslücke eher. Für die Absenkung spricht der Inflationsüberschuss 2024; Studien sehen die Bemessung dagegen eher als zu knapp.', 'gemischt', 'https://www.boeckler.de/de/pressemitteilungen-2675-kindergrundsicherung-niveau-muesste-je-nach-alter-6-bis-30-prozent-hoeher-sein-59625.htm', 'bund', null, true, 'blind'),
  (8823, 21, 'Kindergrundsicherung einführen, die kindbezogene Leistungen bündelt (Bund)', 'Simulationen erwarten rund 2 Prozentpunkte weniger Kinderarmut, vor allem weil mehr Berechtigte Leistungen erhalten. Ohne festgelegtes Niveau bleibt die Wirkung begrenzt; Kosten und Verwaltungsumbau sind erheblich.', 'belegt', 'https://www.boeckler.de/de/boeckler-impuls-kindergrundsicherung-besser-als-nichts-58539.htm', 'bund', null, true, 'blind'),
  (8824, 21, 'Kindergeld anheben bzw. an den Kinderfreibetrag angleichen (Bund)', 'Kindergeld senkt das Armutsrisiko von Familien nachweislich, besonders bei Alleinerziehenden. Bei Grundsicherungsbezug wird es aber angerechnet, die ärmsten Familien gewinnen daher wenig; die Kosten sind hoch.', 'belegt', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'bund', null, true, 'blind'),
  (8825, 21, 'Steuerliche Abzüge für Alleinerziehende und Familien ausweiten (Bund)', 'Entlastet Alleinerziehende mit Steuerschuld und ist leicht umsetzbar. Haushalte mit geringem Einkommen zahlen kaum Steuern und profitieren von Abzügen wenig; Steuervorteile wachsen meist mit dem Einkommen.', 'belegt', 'https://www.diw.de/de/diw_01.c.426860.de/unionsreformvorschlag_zur_familienbesteuerung__einkommensschwache_profitieren_am_wenigsten.html', 'bund', null, true, 'blind'),
  (8826, 21, 'Unterhaltsvorschuss ausweiten, Kindergeld nur teilweise anrechnen (Bund)', 'Mehr Geld für Kinder Alleinerziehender ohne Unterhalt; die Ausweitung 2017 erreichte 300.000 Kinder mehr. Dagegen: Anrechnung auf Kinderzuschlag und Bürgergeld mindert den Nettoeffekt; Bund, Länder und Kommunen tragen Kosten.', 'gemischt', 'https://www.bundesregierung.de/Content/DE/Artikel/2018/08/2018-08-22-bericht-unterhaltsvorschuss.html', 'bund', null, true, 'blind'),
  (8827, 21, 'Familienleistungen digital bündeln, Antrag vereinfachen und automatisch auszahlen (Bund)', 'Vereinfachte, vorausgefüllte oder antragslose Verfahren erhöhen die Inanspruchnahme (Studien, antraglose Familienbeihilfe in Österreich). Dagegen: Datenverknüpfung und Digitalisierung der Verwaltung brauchen Jahre.', 'belegt', 'https://www.diw.de/de/diw_01.c.699957.de/publikationen/wochenberichte/2019_49/starke_nichtinanspruchnahme_von_grundsicherung_deutet_auf_hohe_verdeckte_altersarmut.html', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 21 and id not in (8821, 8822, 8823, 8824, 8825, 8826, 8827);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (8828, 21, 11, null, 'Die jährliche Anpassung der Grundsicherung soll so modernisiert werden, dass überproportionale Erhöhungen gegenüber der Lohnentwicklung künftig verhindert werden.', '{2101}', 8822, 0, 2, null, 'Ein niedrigerer oder langsamer steigender Regelsatz vergrößert eine Versorgungslücke eher. Für die Absenkung spricht der Inflationsüberschuss 2024; Studien sehen die Bemessung dagegen eher als zu knapp.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=32', 'https://www.boeckler.de/de/pressemitteilungen-2675-kindergrundsicherung-niveau-muesste-je-nach-alter-6-bis-30-prozent-hoeher-sein-59625.htm', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8829, 21, 11, null, 'Kinderfreibetrag in Richtung Grundfreibetrag der Eltern entwickeln, Kindergeld entsprechend anheben.', '{2102}', 8824, 2, 2, null, 'Kindergeld senkt das Armutsrisiko von Familien nachweislich, besonders bei Alleinerziehenden. Bei Grundsicherungsbezug wird es aber angerechnet, die ärmsten Familien gewinnen daher wenig; die Kosten sind hoch.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=63', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'belegt', '2026-10-08', false, true, 'blind'),
  (8830, 21, 11, null, 'Steuerlichen Entlastungsbetrag für Alleinerziehende erhöhen.', '{2102}', 8825, 1, 3, null, 'Entlastet Alleinerziehende mit Steuerschuld und ist leicht umsetzbar. Haushalte mit geringem Einkommen zahlen kaum Steuern und profitieren von Abzügen wenig; Steuervorteile wachsen meist mit dem Einkommen.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=63', 'https://www.diw.de/de/diw_01.c.426860.de/unionsreformvorschlag_zur_familienbesteuerung__einkommensschwache_profitieren_am_wenigsten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8831, 21, 11, null, 'Digitales Portal für alle Familienleistungen schaffen, Familienleistungen bündeln und einfacher zugänglich machen.', '{2103}', 8827, 2, 2, null, 'Vereinfachte, vorausgefüllte oder antragslose Verfahren erhöhen die Inanspruchnahme (Studien, antraglose Familienbeihilfe in Österreich). Dagegen: Datenverknüpfung und Digitalisierung der Verwaltung brauchen Jahre.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=63', 'https://www.diw.de/de/diw_01.c.699957.de/publikationen/wochenberichte/2019_49/starke_nichtinanspruchnahme_von_grundsicherung_deutet_auf_hohe_verdeckte_altersarmut.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8832, 21, 12, null, 'Familien mit niedrigem Erwerbseinkommen sollen durch Kindergeld, Kinderzuschlag und Wohngeld ohne ergänzendes Bürgergeld auskommen.', '{2102}', null, 2, 2, null, 'Kinderzuschlag senkt das Armutsrisiko der Empfänger deutlich; ein Ausbau mit Wohngeld hilft Geringverdienenden mit Kindern. Dagegen: geringe Inanspruchnahme und Schnittstellen bleiben, Höhe nicht genannt.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'belegt', '2026-10-08', false, true, 'blind'),
  (8833, 21, 12, null, 'Der Entlastungsbetrag für Alleinerziehende wird in einen Abzug von der Steuerschuld umgewandelt.', '{2102}', 8825, 1, 3, null, 'Entlastet Alleinerziehende mit Steuerschuld und ist leicht umsetzbar. Haushalte mit geringem Einkommen zahlen kaum Steuern und profitieren von Abzügen wenig; Steuervorteile wachsen meist mit dem Einkommen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', 'https://www.diw.de/de/diw_01.c.426860.de/unionsreformvorschlag_zur_familienbesteuerung__einkommensschwache_profitieren_am_wenigsten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8834, 21, 12, null, 'Zentrale Ansprechstelle, einfachere digitale Beantragung und möglichst automatische Auszahlung der Familienleistungen.', '{2103}', 8827, 2, 2, null, 'Vereinfachte, vorausgefüllte oder antragslose Verfahren erhöhen die Inanspruchnahme (Studien, antraglose Familienbeihilfe in Österreich). Dagegen: Datenverknüpfung und Digitalisierung der Verwaltung brauchen Jahre.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=27', 'https://www.diw.de/de/diw_01.c.699957.de/publikationen/wochenberichte/2019_49/starke_nichtinanspruchnahme_von_grundsicherung_deutet_auf_hohe_verdeckte_altersarmut.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8835, 21, 13, null, 'Bürgergeld-Regelsatz regelmäßig anpassen, damit das soziokulturelle Existenzminimum garantiert bleibt.', '{2101}', 8821, 1, 3, null, 'Zeitnahe Anpassung verhindert reale Kaufkraftverluste wie 2022/23. Die Fortschreibung mit Mischindex und Besitzschutz besteht aber schon; eine Lücke durch zu knappe Bemessung schließt sie nicht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=99', 'https://www.bundesregierung.de/breg-de/suche/buergergeld-2025-2248000', 'belegt', '2026-10-08', false, true, 'blind'),
  (8836, 21, 13, null, 'Kindergeld gesetzlich an die Erhöhung des Kinderfreibetrags koppeln, später die Entlastung angleichen.', '{2102}', 8824, 2, 2, null, 'Kindergeld senkt das Armutsrisiko von Familien nachweislich, besonders bei Alleinerziehenden. Bei Grundsicherungsbezug wird es aber angerechnet, die ärmsten Familien gewinnen daher wenig; die Kosten sind hoch.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=81', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'belegt', '2026-10-08', false, true, 'blind'),
  (8837, 21, 13, null, 'Freibetrag für Alleinerziehende zur Steuergutschrift ausbauen; Kindergeld nur zur Hälfte auf den Unterhaltsvorschuss anrechnen.', '{2102}', 8826, 2, 2, null, 'Mehr Geld für Kinder Alleinerziehender ohne Unterhalt; die Ausweitung 2017 erreichte 300.000 Kinder mehr. Dagegen: Anrechnung auf Kinderzuschlag und Bürgergeld mindert den Nettoeffekt; Bund, Länder und Kommunen tragen Kosten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', 'https://www.bundesregierung.de/Content/DE/Artikel/2018/08/2018-08-22-bericht-unterhaltsvorschuss.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8838, 21, 13, null, 'Kindergrundsicherung schnellstmöglich einführen, Anträge verschlanken und automatisieren.', '{2102,2103}', 8823, 2, 2, null, 'Simulationen erwarten rund 2 Prozentpunkte weniger Kinderarmut, vor allem weil mehr Berechtigte Leistungen erhalten. Ohne festgelegtes Niveau bleibt die Wirkung begrenzt; Kosten und Verwaltungsumbau sind erheblich.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=83', 'https://www.boeckler.de/de/boeckler-impuls-kindergrundsicherung-besser-als-nichts-58539.htm', 'belegt', '2026-10-08', false, true, 'blind'),
  (8839, 21, 13, null, 'Kindergrundsicherungs-Check: Familien werden ab der Geburt aktiv über ihre Ansprüche informiert.', '{2103}', null, 2, 2, null, 'Aktive, einfache Information über konkrete Ansprüche erhöht die Inanspruchnahme nachweislich (Feldexperimente). Allein schließt sie die Lücke nicht; nötig sind Daten zur Prüfung der Ansprüche.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', 'https://www.povertyactionlab.org/case-study/simplified-reminders-increase-take-tax-credits', 'belegt', '2026-10-08', false, true, 'blind'),
  (8840, 21, 13, null, 'Existenzminimum für Kinder armutsfest neu berechnen; Alleinerziehende bei Anrechnung von Unterhalt und Einkommen besser stellen.', '{2102}', null, 2, 2, null, 'Studien sehen das Kinderexistenzminimum als zu knapp bemessen; eine Neuberechnung und günstigere Anrechnung setzen direkt an. Dagegen: Ergebnis und Höhe offen, Mehrkosten nicht beziffert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', 'https://www.boeckler.de/de/pressemitteilungen-2675-kindergrundsicherung-niveau-muesste-je-nach-alter-6-bis-30-prozent-hoeher-sein-59625.htm', 'belegt', '2026-10-08', false, true, 'blind'),
  (8841, 21, 14, null, 'Regelsatz der Grundsicherung absenken, indem die Besitzstandsregelung abgeschafft wird.', '{2101}', 8822, 0, 2, null, 'Ein niedrigerer oder langsamer steigender Regelsatz vergrößert eine Versorgungslücke eher. Für die Absenkung spricht der Inflationsüberschuss 2024; Studien sehen die Bemessung dagegen eher als zu knapp.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=20', 'https://www.boeckler.de/de/pressemitteilungen-2675-kindergrundsicherung-niveau-muesste-je-nach-alter-6-bis-30-prozent-hoeher-sein-59625.htm', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8842, 21, 14, null, 'Bürgergeld und Wohngeld in einer Leistung an einer staatlichen Stelle zusammenfassen, um Bürokratie und Komplexität zu verringern.', '{2103}', null, 2, 2, null, 'Eine Leistung an einer Stelle senkt Antragshürden; Komplexität gilt als ein Grund für Nichtinanspruchnahme. Dagegen: Wirkung solcher Zusammenlegungen kaum untersucht, großer Umbau zwischen Bund und Kommunen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=20', null, 'offen', '2026-10-08', false, true, 'blind'),
  (8843, 21, 14, null, 'Steuerliche Absetzbarkeit von Betreuungskosten und gesetzlichen Unterhaltsleistungen verbessern, um Familien und Alleinerziehende zu entlasten.', '{2102}', 8825, 1, 3, null, 'Entlastet Alleinerziehende mit Steuerschuld und ist leicht umsetzbar. Haushalte mit geringem Einkommen zahlen kaum Steuern und profitieren von Abzügen wenig; Steuervorteile wachsen meist mit dem Einkommen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=14', 'https://www.diw.de/de/diw_01.c.426860.de/unionsreformvorschlag_zur_familienbesteuerung__einkommensschwache_profitieren_am_wenigsten.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8844, 21, 14, null, 'Elterngeld und weitere Familienleistungen entbürokratisieren, digitalisieren und automatisieren, etwa über KI-gestützte Beantragung und ein Kinderchancenportal.', '{2103}', 8827, 2, 2, null, 'Vereinfachte, vorausgefüllte oder antragslose Verfahren erhöhen die Inanspruchnahme (Studien, antraglose Familienbeihilfe in Österreich). Dagegen: Datenverknüpfung und Digitalisierung der Verwaltung brauchen Jahre.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=30', 'https://www.diw.de/de/diw_01.c.699957.de/publikationen/wochenberichte/2019_49/starke_nichtinanspruchnahme_von_grundsicherung_deutet_auf_hohe_verdeckte_altersarmut.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8845, 21, 15, null, 'Regelbedarfssätze der Grundsicherung (Bürgergeld) an die tatsächliche Preisentwicklung des Warenkorbs anpassen.', '{2101}', 8821, 1, 3, null, 'Zeitnahe Anpassung verhindert reale Kaufkraftverluste wie 2022/23. Die Fortschreibung mit Mischindex und Besitzschutz besteht aber schon; eine Lücke durch zu knappe Bemessung schließt sie nicht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=26', 'https://www.bundesregierung.de/breg-de/suche/buergergeld-2025-2248000', 'belegt', '2026-10-08', false, true, 'blind'),
  (8846, 21, 15, null, 'Familiensplitting und höherer Kinderfreibetrag, um Familien mit mittlerem Einkommen steuerlich zu entlasten.', '{2102}', null, 1, 2, null, 'Familiensplitting und höherer Kinderfreibetrag entlasten vor allem mittlere und hohe Einkommen; Familien mit geringem Einkommen oder Grundsicherung profitieren kaum. Hohe Steuerausfälle.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=149', 'https://www.diw.de/de/diw_01.c.60474.de/familiensplitting_beguenstigt_einkommensstarke_familien_und_ist_kein_arbeitsanreiz_fuer_ehefrauen.html', 'belegt', '2026-10-08', false, true, 'blind'),
  (8847, 21, 15, null, 'Mehrwertsteuer auf Artikel des Kinderbedarfs auf den ermäßigten Satz senken.', '{2102}', null, 1, 2, null, 'Senkt Preise für Kinderbedarf, wenn der Handel die Senkung weitergibt, was nur teilweise geschieht. Die Entlastung ist ungezielt und für arme Familien klein; EU-Recht lässt den ermäßigten Satz nur für gelistete Güter zu.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=149', null, 'gemischt', '2026-10-08', false, true, 'blind'),
  (8848, 21, 15, null, 'Beim Wechselmodell nach Trennung das Existenzminimum von Eltern und Kindern in beiden Haushalten sichern.', '{2102}', null, 1, 2, null, 'Berücksichtigt Mehrkosten getrennter Familien im Wechselmodell, die heute oft nicht gedeckt sind. Die Zusage nennt aber weder Instrument noch Betrag, die Wirkung bleibt unbestimmt.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=155', null, 'offen', '2026-10-08', false, true, 'blind'),
  (8849, 21, 16, null, 'Bürgergeld wird zu einer sanktionsfreien, individuellen Mindestsicherung umgebaut, die sich an der Armutsgefährdungsgrenze orientiert.', '{2101}', null, 3, 1, null, 'Eine Mindestsicherung an der Armutsgefährdungsgrenze setzt direkt an der Höhe an; Studien sehen die heutige Bemessung als zu knapp. Dagegen: sehr hohe, ungeklärte Kosten; Wirkung auf Arbeitsanreize ist umstritten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', 'https://www.boeckler.de/de/pressemitteilungen-2675-kindergrundsicherung-niveau-muesste-je-nach-alter-6-bis-30-prozent-hoeher-sein-59625.htm', 'belegt', '2026-10-08', false, true, 'blind'),
  (8850, 21, 16, null, 'Eigenständige Kindergrundsicherung, die Kindergeld, Kinderzuschlag, Unterkunftskosten und Sonderbedarfe bündelt.', '{2102}', 8823, 2, 2, null, 'Simulationen erwarten rund 2 Prozentpunkte weniger Kinderarmut, vor allem weil mehr Berechtigte Leistungen erhalten. Ohne festgelegtes Niveau bleibt die Wirkung begrenzt; Kosten und Verwaltungsumbau sind erheblich.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', 'https://www.boeckler.de/de/boeckler-impuls-kindergrundsicherung-besser-als-nichts-58539.htm', 'belegt', '2026-10-08', false, true, 'blind'),
  (8851, 21, 16, null, 'Unterhaltsvorschuss ausweiten: Kindergeld nicht mehr voll anrechnen, Bezug bis 25 Jahre.', '{2102}', 8826, 2, 2, null, 'Mehr Geld für Kinder Alleinerziehender ohne Unterhalt; die Ausweitung 2017 erreichte 300.000 Kinder mehr. Dagegen: Anrechnung auf Kinderzuschlag und Bürgergeld mindert den Nettoeffekt; Bund, Länder und Kommunen tragen Kosten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', 'https://www.bundesregierung.de/Content/DE/Artikel/2018/08/2018-08-22-bericht-unterhaltsvorschuss.html', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8852, 21, 17, null, 'Steuerlicher Kinderfreibetrag und Kindergeld sollen gleich hoch sein, damit jedes Kind dem Staat gleich viel wert ist.', '{2102}', 8824, 2, 2, null, 'Kindergeld senkt das Armutsrisiko von Familien nachweislich, besonders bei Alleinerziehenden. Bei Grundsicherungsbezug wird es aber angerechnet, die ärmsten Familien gewinnen daher wenig; die Kosten sind hoch.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=32', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'belegt', '2026-10-08', false, true, 'blind'),
  (8853, 21, 18, null, 'Existenzsicherndes Grundeinkommen als negative Einkommensteuer, bei fehlendem Einkommen automatisch ohne Antrag ausgezahlt; ersetzt Sozialleistungen bis zur Armutsgrenze.', '{2101,2103}', null, 2, 1, null, 'Automatische, antragslose Existenzsicherung würde Nichtinanspruchnahme und Lücken schließen; Experimente zeigen mehr Wohlbefinden, kaum Beschäftigungseffekte. Dagegen: Systemumbau mit ungeklärter Finanzierung.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=102', 'https://vatt.fi/en/-/perustulon-tyollisyysvaikutukset-jaivat-vahaisiksi', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8854, 21, 18, null, 'Kindergeld erhöhen, im Gegenzug Ehegattensplitting abschaffen.', '{2102}', 8824, 2, 2, null, 'Kindergeld senkt das Armutsrisiko von Familien nachweislich, besonders bei Alleinerziehenden. Bei Grundsicherungsbezug wird es aber angerechnet, die ärmsten Familien gewinnen daher wenig; die Kosten sind hoch.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=99', 'https://www.caritas.de/neue-caritas/heftarchiv/jahrgang2014/artikel/milliarden-nur-fuer-schmu--wie-familienpolitik-wirkt', 'belegt', '2026-10-08', false, true, 'blind'),
  (8855, 21, 18, null, 'Mehr Kinderkrankentage und volles Kinderkrankengeld für Alleinerziehende zur finanziellen Absicherung.', '{2102}', null, 1, 2, null, 'Mindert Einkommensausfälle erwerbstätiger Alleinerziehender bei Krankheit des Kindes. Wirkt nur am Rand auf die Sicherung des Lebensunterhalts; Mehrkosten für die Krankenkassen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=149', null, 'offen', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (8821, 21),
  (8822, 21),
  (8823, 21),
  (8824, 21),
  (8825, 21),
  (8826, 21),
  (8827, 21),
  (8832, 21),
  (8839, 21),
  (8840, 21),
  (8842, 21),
  (8846, 21),
  (8847, 21),
  (8848, 21),
  (8849, 21),
  (8853, 21),
  (8855, 21);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (21, 11, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 12, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 13, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 14, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 15, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 16, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 17, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}'),
  (21, 18, null, 'massnahmen', null, '2026-10-08', true, '{2101,2102,2103}');

commit;
