-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 31 „Kosten von Studium und Ausbildung“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 31;
delete from public.abdeckung where thema_id = 31;
delete from public.pruef_einheiten where thema_id = 31;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (8664, 31, 'Gesetzliche Mindestausbildungsvergütung anheben (Bund)', 'Hebt die Vergütung genau in den schwach bezahlten Bereichen direkt an; laut BIBB wird aber nur bei 3-4 % der Verträge genau der Mindestsatz vereinbart, und Simulationen warnten vor weniger Ausbildungsplätzen in einzelnen Segmenten.', 'gemischt', 'https://www.bibb.de/de/pressemitteilung_229684.php', 'bund', null, true, 'blind'),
  (8665, 31, 'Schulgeld in schulischen Ausbildungen abschaffen (Bund)', 'Entfällt eine direkte Kostenlast für Auszubildende ohne Vergütung; Länder wie NRW übernehmen Schulgeld bereits mit spürbarer Entlastung. Der Bund kann es nur teils über Berufsgesetze und Finanzierung regeln.', 'belegt', 'https://www.bra.nrw.de/foerderportal-wirtschaft/foerderportal/schultraegerinnen-und-schultraeger/einstieg-die-schulgeldfreiheit-den-gesundheitsfachberufen', 'bund', null, true, 'blind'),
  (8666, 31, 'BAföG-Sätze und Freibeträge regelmäßig an Lebenshaltungskosten anpassen (Bund)', 'Verhindert, dass die Förderung real an Wert verliert; Zuschüsse erhöhen nachweislich den Studienabschluss. Eine Indexierung hält aber nur das bestehende Niveau, ohne es anzuheben.', 'belegt', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'bund', null, true, 'blind'),
  (8667, 31, 'BAföG unabhängiger vom Elterneinkommen gestalten (Bund)', 'Erweitert den Kreis der Geförderten, deren Eltern faktisch nicht zahlen; Zuschüsse stärken den Abschluss. DIW fand bei BAföG-Reformen aber nur kleine Effekte auf die Studienaufnahme, zudem hohe Mehrkosten.', 'gemischt', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'bund', null, true, 'blind'),
  (8668, 31, 'Konditionen und Ausbau staatlicher Studien- und Bildungskredite (Bund)', 'Feste Zinsen und mehr Kreditvolumen erleichtern die Überbrückung, lösen aber nicht das Einkommensproblem und verlagern die Last als Schulden in die Zukunft; Wirkung auf Erwerbsarbeit kaum untersucht.', 'offen', null, 'bund', null, true, 'blind'),
  (8669, 31, 'Aufstiegs-BAföG ausweiten und vereinfachen (Bund)', 'Verbessert die Förderung für Fach- und Fortbildungsschüler über ein bestehendes Gesetz; erreicht aber nur eine kleine Gruppe, für Studierende kaum relevant, Wirkung wenig untersucht.', 'offen', null, 'bund', null, true, 'blind'),
  (8670, 31, 'Bundesmittel für Studierendenwerke und soziale Infrastruktur an Hochschulen (Bund)', 'Kann Mensapreise, Beiträge und Wohnkosten senken; der Effekt je Person ist klein und hängt von der Ausgestaltung ab. Hochschulen sind Ländersache, der Bund kann nur über einen Pakt mitfinanzieren.', 'offen', null, 'bund', null, true, 'blind'),
  (8671, 31, 'Förderung von Wohnheimplätzen für Studierende und Auszubildende (Bund)', 'Wohnheimmieten liegen meist deutlich unter Marktmieten, das Bundesprogramm läuft bereits und hat die geförderten Plätze verdoppelt; die Wirkung bleibt aber auf die Bewohner begrenzt und ist kaum evaluiert.', 'offen', 'https://www.bundestag.de/presse/hib/kurzmeldungen-1166126', 'bund', null, true, 'blind'),
  (8672, 31, 'Vergünstigte Mobilität für Auszubildende (Ticket, Führerschein) (Bund)', 'Günstige Tickets entlasten laut DIW vor allem Junge, Auszubildende und Geringverdienende; es bleibt aber eine Entlastung bei einem Kostenposten, und der ÖPNV ist Ländersache mit Bundesmitfinanzierung.', 'belegt', 'https://www.diw.de/de/diw_01.c.869729.de/publikationen/wochenberichte/2023_14_1/9-euro-ticket__niedrigere_preise_allein_staerken_alltagsmobilitaet_mit_oeffentlichen_verkehrsmitteln_nicht.html', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 31 and id not in (8664, 8665, 8666, 8667, 8668, 8669, 8670, 8671, 8672);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (8673, 31, 11, null, 'BAföG-Empfängern ermöglichen, mehr hinzuzuverdienen', '{3102}', null, 1, 3, null, 'Höhere Hinzuverdienstgrenzen verbessern das Einkommen von BAföG-Beziehenden, verstärken aber eher die Erwerbsarbeit neben dem Studium, statt sie zu verringern.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8674, 31, 11, null, 'Festen Zinssatz für Studienkredite sicherstellen und faire Konditionen vereinbaren', '{3102}', 8668, 1, 3, null, 'Feste Zinsen und mehr Kreditvolumen erleichtern die Überbrückung, lösen aber nicht das Einkommensproblem und verlagern die Last als Schulden in die Zukunft; Wirkung auf Erwerbsarbeit kaum untersucht.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=69', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8675, 31, 12, null, 'Mindestausbildungsvergütung anheben.', '{3101}', 8664, 2, 3, null, 'Hebt die Vergütung genau in den schwach bezahlten Bereichen direkt an; laut BIBB wird aber nur bei 3-4 % der Verträge genau der Mindestsatz vereinbart, und Simulationen warnten vor weniger Ausbildungsplätzen in einzelnen Segmenten.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', 'https://www.bibb.de/de/pressemitteilung_229684.php', 'gemischt', '2026-10-10', false, true, 'blind'),
  (8676, 31, 12, null, 'BAföG-Förderhöhe regelmäßig an die Lebenshaltungskosten anpassen.', '{3102}', 8666, 2, 3, null, 'Verhindert, dass die Förderung real an Wert verliert; Zuschüsse erhöhen nachweislich den Studienabschluss. Eine Indexierung hält aber nur das bestehende Niveau, ohne es anzuheben.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=15', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'belegt', '2026-10-10', false, true, 'blind'),
  (8677, 31, 12, null, 'Mittel für den Neubau von Wohnheimen für Studierende und Azubis verstetigen und erhöhen.', '{3101,3102}', 8671, 2, 3, null, 'Wohnheimmieten liegen meist deutlich unter Marktmieten, das Bundesprogramm läuft bereits und hat die geförderten Plätze verdoppelt; die Wirkung bleibt aber auf die Bewohner begrenzt und ist kaum evaluiert.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=21', 'https://www.bundestag.de/presse/hib/kurzmeldungen-1166126', 'offen', '2026-10-10', false, true, 'blind'),
  (8678, 31, 12, null, 'Bundeseinheitlich vergünstigtes Deutschlandticket für bestimmte soziale Gruppen, darunter Auszubildende und Studierende.', '{3101}', 8672, 1, 2, null, 'Günstige Tickets entlasten laut DIW vor allem Junge, Auszubildende und Geringverdienende; es bleibt aber eine Entlastung bei einem Kostenposten, und der ÖPNV ist Ländersache mit Bundesmitfinanzierung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=35', 'https://www.diw.de/de/diw_01.c.869729.de/publikationen/wochenberichte/2023_14_1/9-euro-ticket__niedrigere_preise_allein_staerken_alltagsmobilitaet_mit_oeffentlichen_verkehrsmitteln_nicht.html', 'belegt', '2026-10-10', false, true, 'blind'),
  (8679, 31, 12, null, 'Arbeitgeber sollen einen Führerscheinzuschuss bis zu 2.000 Euro steuer- und abgabenfrei an Azubis und junge Beschäftigte zahlen können.', '{3101}', null, 1, 3, null, 'Ein steuerfreier Führerscheinzuschuss senkt einen konkreten Kostenposten, hängt aber von der Zahlungsbereitschaft des Betriebs ab und ist eine einmalige Entlastung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=36', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8680, 31, 12, null, 'Praxisnahe und kostenfreie Ausbildungen in den Gesundheitsfachberufen.', '{3101}', 8665, 2, 2, null, 'Entfällt eine direkte Kostenlast für Auszubildende ohne Vergütung; Länder wie NRW übernehmen Schulgeld bereits mit spürbarer Entlastung. Der Bund kann es nur teils über Berufsgesetze und Finanzierung regeln.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=32', 'https://www.bra.nrw.de/foerderportal-wirtschaft/foerderportal/schultraegerinnen-und-schultraeger/einstieg-die-schulgeldfreiheit-den-gesundheitsfachberufen', 'belegt', '2026-10-10', false, true, 'blind'),
  (8681, 31, 12, null, 'Duales Studium stärker fördern und Schutzrechte des Berufsbildungsgesetzes auf diesen Ausbildungsweg ausweiten.', '{3101}', null, 1, 3, null, 'BBiG-Schutzrechte brächten dual Studierenden u. a. Vergütungsanspruch und Mindestvergütung; betrifft aber eine kleine Gruppe, und viele erhalten bereits Vergütung. Wirkung kaum untersucht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8682, 31, 12, null, 'Bearbeitungszeiten für BAföG-Anträge durch Digitalisierung und Vereinfachung verkürzen.', '{3102}', null, 1, 3, null, 'Kürzere Bearbeitungszeiten vermeiden Finanzierungslücken zu Studienbeginn; die Förderhöhe bleibt unverändert, Wirkung auf den Lebensunterhalt gering.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=16', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8683, 31, 13, null, 'Mindestausbildungsvergütung wird deutlich angehoben.', '{3101}', 8664, 2, 3, null, 'Hebt die Vergütung genau in den schwach bezahlten Bereichen direkt an; laut BIBB wird aber nur bei 3-4 % der Verträge genau der Mindestsatz vereinbart, und Simulationen warnten vor weniger Ausbildungsplätzen in einzelnen Segmenten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', 'https://www.bibb.de/de/pressemitteilung_229684.php', 'gemischt', '2026-10-10', false, true, 'blind'),
  (8684, 31, 13, null, 'Führerscheinförderung, Lösung für ein Azubi-Ticket und attraktiverer ÖPNV für Auszubildende.', '{3101}', 8672, 1, 2, null, 'Günstige Tickets entlasten laut DIW vor allem Junge, Auszubildende und Geringverdienende; es bleibt aber eine Entlastung bei einem Kostenposten, und der ÖPNV ist Ländersache mit Bundesmitfinanzierung.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', 'https://www.diw.de/de/diw_01.c.869729.de/publikationen/wochenberichte/2023_14_1/9-euro-ticket__niedrigere_preise_allein_staerken_alltagsmobilitaet_mit_oeffentlichen_verkehrsmitteln_nicht.html', 'belegt', '2026-10-10', false, true, 'blind'),
  (8685, 31, 13, null, 'Auszubildendenwerke nach dem Vorbild der Studierendenwerke fördern, mit Wohnheimen und Beratung.', '{3101}', null, 2, 2, null, 'Auszubildendenwerke würden die fehlenden Trägerstrukturen für Azubi-Wohnheime schaffen, die bisher Förderung abrufen bremsen; der Aufbau dauert und erfordert Länderbeteiligung.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=78', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8686, 31, 13, null, 'Bau und Sanierung von Wohnheimen über das Programm „Junges Wohnen“ verstetigen und weiter fördern, Auszubildende im Fokus.', '{3101,3102}', 8671, 2, 3, null, 'Wohnheimmieten liegen meist deutlich unter Marktmieten, das Bundesprogramm läuft bereits und hat die geförderten Plätze verdoppelt; die Wirkung bleibt aber auf die Bewohner begrenzt und ist kaum evaluiert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.bundestag.de/presse/hib/kurzmeldungen-1166126', 'offen', '2026-10-10', false, true, 'blind'),
  (8687, 31, 13, null, 'BAföG-Bedarfssätze und Freibeträge werden regelmäßig an die Lebenshaltungskosten angepasst.', '{3102}', 8666, 2, 3, null, 'Verhindert, dass die Förderung real an Wert verliert; Zuschüsse erhöhen nachweislich den Studienabschluss. Eine Indexierung hält aber nur das bestehende Niveau, ohne es anzuheben.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'belegt', '2026-10-10', false, true, 'blind'),
  (8688, 31, 13, null, 'BAföG elternunabhängiger gestalten; Einkommen der Geschwister wird aus der Berechnung herausgenommen.', '{3102}', 8667, 2, 2, null, 'Erweitert den Kreis der Geförderten, deren Eltern faktisch nicht zahlen; Zuschüsse stärken den Abschluss. DIW fand bei BAföG-Reformen aber nur kleine Effekte auf die Studienaufnahme, zudem hohe Mehrkosten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'gemischt', '2026-10-10', false, true, 'blind'),
  (8689, 31, 13, null, 'BAföG-Wohnkostenpauschale wird an die ortsüblichen Mieten angepasst.', '{3102}', null, 2, 3, null, 'Miete ist der größte Ausgabenposten; eine ortsübliche Pauschale schließt die Lücke in teuren Städten gezielt. Erreicht nur BAföG-Beziehende und kann Mieten an Hochschulorten mittragen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'belegt', '2026-10-10', false, true, 'blind'),
  (8690, 31, 13, null, 'Aufstiegs-BAföG wird reformiert; Unterhaltszuschuss auch in Teilzeit und digitales Antragsverfahren.', '{3102}', 8669, 1, 3, null, 'Verbessert die Förderung für Fach- und Fortbildungsschüler über ein bestehendes Gesetz; erreicht aber nur eine kleine Gruppe, für Studierende kaum relevant, Wirkung wenig untersucht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=79', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8691, 31, 14, null, 'Stipendien für Auszubildende (SBB- und Azubi-Stipendien) ausbauen', '{3101}', null, 1, 3, null, 'Stipendien entlasten einzelne leistungsstarke Auszubildende und Fachkräfte; sie erreichen nur wenige und setzen nicht an der Vergütungshöhe an. Wirkung kaum untersucht.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=9', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8692, 31, 14, null, 'BAföG zu einem elternunabhängigen Baukasten-System weiterentwickeln', '{3102}', 8667, 2, 2, null, 'Erweitert den Kreis der Geförderten, deren Eltern faktisch nicht zahlen; Zuschüsse stärken den Abschluss. DIW fand bei BAföG-Reformen aber nur kleine Effekte auf die Studienaufnahme, zudem hohe Mehrkosten.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=10', 'https://www.diw.de/de/diw_01.c.87747.de/bafoeg-reform_hat_kaum_auswirkungen_auf_die_studienaufnahme.html', 'gemischt', '2026-10-10', false, true, 'blind'),
  (8693, 31, 14, null, 'Bildungskreditprogramm stärken und ausbauen', '{3102}', 8668, 1, 3, null, 'Feste Zinsen und mehr Kreditvolumen erleichtern die Überbrückung, lösen aber nicht das Einkommensproblem und verlagern die Last als Schulden in die Zukunft; Wirkung auf Erwerbsarbeit kaum untersucht.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=10', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8694, 31, 15, null, 'BAföG-Rückzahlung bei Geburt eines Kindes während Ausbildung oder Studium erlassen', '{3102}', null, 1, 3, null, 'Ein Rückzahlungserlass entlastet Eltern unter den Geförderten nach dem Abschluss, ändert aber nichts am laufenden Lebensunterhalt während des Studiums.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=149', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8695, 31, 16, null, 'Mindestausbildungsvergütung von 80 Prozent der tariflichen Vergütung der Branchen', '{3101}', null, 2, 2, null, 'Ein Mindestsatz von 80 % des tariflichen Durchschnitts würde schwach bezahlte Bereiche deutlich anheben und Schulgeld entfallen lassen; Simulationen warnen bei starken Anhebungen vor weniger Ausbildungsplätzen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', 'https://www.bibb.de/de/pressemitteilung_229684.php', 'gemischt', '2026-10-10', false, true, 'blind'),
  (8696, 31, 16, null, 'Unternehmen sollen sich an bezahlbaren Wohnheimplätzen für Auszubildende finanziell beteiligen', '{3101}', null, 1, 1, null, 'Mehr günstige Wohnheimplätze würden Auszubildende entlasten; eine Pflichtabgabe für Unternehmen ist rechtlich aufwendig und in Ausgestaltung und Wirkung unklar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8697, 31, 16, null, 'Schulgeld abschaffen, Ausbildung gebührenfrei machen', '{3101}', 8665, 2, 2, null, 'Entfällt eine direkte Kostenlast für Auszubildende ohne Vergütung; Länder wie NRW übernehmen Schulgeld bereits mit spürbarer Entlastung. Der Bund kann es nur teils über Berufsgesetze und Finanzierung regeln.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', 'https://www.bra.nrw.de/foerderportal-wirtschaft/foerderportal/schultraegerinnen-und-schultraeger/einstieg-die-schulgeldfreiheit-den-gesundheitsfachberufen', 'belegt', '2026-10-10', false, true, 'blind'),
  (8698, 31, 16, null, 'Kostenloses 0-Euro-Ticket für Auszubildende und Studierende im Nahverkehr', '{3101}', null, 1, 1, null, 'Kostenloser Nahverkehr entlastet Auszubildende bei einem Kostenposten, günstige Tickets erreichen laut DIW gerade Junge; die dauerhafte Finanzierung durch Bund und Länder ist aber ungeklärt.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=36', 'https://www.diw.de/de/diw_01.c.869729.de/publikationen/wochenberichte/2023_14_1/9-euro-ticket__niedrigere_preise_allein_staerken_alltagsmobilitaet_mit_oeffentlichen_verkehrsmitteln_nicht.html', 'belegt', '2026-10-10', false, true, 'blind'),
  (8699, 31, 16, null, 'Ausbildungskosten für Psychotherapeut*innen deckeln, Beschäftigungsstatus in Ausbildung', '{3101}', null, 2, 2, null, 'Gedeckelte Kosten und ein tariffähiger Beschäftigungsstatus würden die hohe Belastung in der Psychotherapie-Ausbildung spürbar senken; betrifft nur eine Berufsgruppe, Finanzierung über Kassen offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=19', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8700, 31, 16, null, 'BAföG für alle: elternunabhängig, existenzsichernd, Höhe an Lebenshaltungskosten und Armutsgrenze', '{3102}', null, 3, 1, null, 'Ein existenzsichernder Vollzuschuss für alle setzt direkt am Erwerbszwang an; Zuschüsse senken Erwerbsarbeit und erhöhen den Abschluss nachweislich. Die Kosten wären aber sehr hoch und die Finanzierung ist offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=40', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'belegt', '2026-10-10', false, true, 'blind'),
  (8701, 31, 16, null, 'Anspruch auf Aufstiegs-BAföG für dreijährige schulische Fachschulausbildungen ohne Sanktionen', '{3102}', 8669, 1, 3, null, 'Verbessert die Förderung für Fach- und Fortbildungsschüler über ein bestehendes Gesetz; erreicht aber nur eine kleine Gruppe, für Studierende kaum relevant, Wirkung wenig untersucht.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8702, 31, 16, null, 'Studierendenwerke so finanzieren, dass sie Semesterbeiträge, Mensapreise und Wohnkosten senken können', '{3102}', 8670, 1, 2, null, 'Kann Mensapreise, Beiträge und Wohnkosten senken; der Effekt je Person ist klein und hängt von der Ausgestaltung ab. Hochschulen sind Ländersache, der Bund kann nur über einen Pakt mitfinanzieren.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=40', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8703, 31, 16, null, 'Studentische Beschäftigte tarifvertraglich absichern', '{3102}', null, 1, 1, null, 'Bessere Bezahlung studentischer Hilfskräfte senkt die nötige Arbeitszeit für einen Teil der Jobbenden; Tarifverträge schließen aber Länder und Tarifparteien, der Bund kann das kaum durchsetzen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=41', null, 'offen', '2026-10-10', false, true, 'blind'),
  (8704, 31, 17, null, 'BAföG reformieren, damit das Studium auskömmlich finanziert ist.', '{3102}', null, 2, 2, null, 'Eine auskömmliche Förderung setzt direkt am Zwang zur Erwerbsarbeit an, Zuschüsse stärken nachweislich den Abschluss; Höhe und Finanzierung bleiben aber unbestimmt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=25', 'https://www.aeaweb.org/doi/10.1257/app.20180100', 'belegt', '2026-10-10', false, true, 'blind'),
  (8705, 31, 17, null, 'Hochschulsozialpakt für gute soziale Infrastruktur an den Hochschulen.', '{3102}', 8670, 1, 2, null, 'Kann Mensapreise, Beiträge und Wohnkosten senken; der Effekt je Person ist klein und hängt von der Ausgestaltung ab. Hochschulen sind Ländersache, der Bund kann nur über einen Pakt mitfinanzieren.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=25', null, 'offen', '2026-10-10', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (8664, 31),
  (8665, 31),
  (8666, 31),
  (8667, 31),
  (8668, 31),
  (8669, 31),
  (8670, 31),
  (8671, 31),
  (8672, 31),
  (8673, 31),
  (8679, 31),
  (8681, 31),
  (8682, 31),
  (8685, 31),
  (8689, 31),
  (8691, 31),
  (8694, 31),
  (8695, 31),
  (8696, 31),
  (8698, 31),
  (8699, 31),
  (8700, 31),
  (8703, 31),
  (8704, 31);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (31, 11, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 12, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 13, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 14, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 15, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 16, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}'),
  (31, 17, null, 'massnahmen', null, '2026-10-10', true, '{3101,3102}');

commit;
