-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 20 „Freizeitangebote und Treffpunkte für Jugendliche“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 20;
delete from public.abdeckung where thema_id = 20;
delete from public.pruef_einheiten where thema_id = 20;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (9010, 20, 'Jugendtreffs und offene Jugendarbeit erhalten, ausbauen und verlässlich finanzieren (Land)', 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'belegt', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'land', null, true, 'blind'),
  (9011, 20, 'Jugendarbeit gesetzlich absichern: Rechtsanspruch, Pflichtaufgabe oder verbindliche Mindeststandards (Land)', 'Verbindliche Vorgaben schützen Angebote vor Kürzungen; Berlin setzt seit 2022 Mengen- und Qualitätsstandards, eine Wirkungsauswertung fehlt. Mehrkosten trägt das Land (Konnexität), Fachkräfte sind knapp.', 'offen', 'https://www.berlin.de/sen/jugend/jugend/jugendarbeit/', 'land', null, true, 'blind'),
  (9012, 20, 'Mobile Jugendarbeit und mobile Jugendzentren im ländlichen Raum fördern (Land)', 'Mobile Angebote erreichen Jugendliche, wo es keinen festen Treff gibt. Eine Wirkungsevaluation aus Österreich zeigt aber auf dem Land deutlich weniger Kontakte als in Städten und vor allem Jungen als Nutzer.', 'gemischt', 'https://austria-forum.org/web-books/jugendarbeit00de2017isds/000062', 'land', null, true, 'blind'),
  (9013, 20, 'Queere Jugendzentren und queere Jugendorte erhalten und ausbauen (Land)', 'Studien verbinden die Teilnahme an queeren Jugendangeboten mit weniger psychischer Belastung der Teilnehmenden. Sie erreichen aber nur einen kleinen Teil der Jugendlichen und schaffen kaum allgemeine Treffpunkte.', 'belegt', 'https://shine.lab.uconn.edu/wp-content/uploads/sites/3321/2021/06/eisenberg_lgbtq_orgs_2020_annals.pdf', 'land', null, true, 'blind'),
  (9014, 20, 'Jugendgerechte Treffpunkte im öffentlichen Raum und in Leerständen mit Jugendlichen gestalten (Land)', 'Setzt am häufig geäußerten Wunsch nach Treffpunkten im öffentlichen Raum an; Modellvorhaben des Bundes zeigen Nutzen von Beteiligung. Belastbare Wirkungsstudien fehlen, Konflikte mit Anwohnenden bleiben möglich.', 'offen', 'https://www.bbsr.bund.de/BBSR/DE/forschung/programme/exwost/Forschungsfelder/2009/JugendlicheImStadtquartier/01_Start.html', 'land', null, true, 'blind'),
  (9015, 20, 'Kulturpass mit Guthaben für junge Menschen fortführen (Bund)', 'Guthaben senkt Kosten kultureller Freizeit, der Bund hat es bereits umgesetzt. Beim französischen Vorbild prüfte der Rechnungshof: Es verstärkt vor allem bestehende Gewohnheiten und erreicht Jugendliche aus ärmeren Familien seltener.', 'gemischt', 'https://www.livreshebdo.fr/article/pass-culture-la-cour-des-comptes-epingle-le-dispositif', 'bund', null, true, 'blind'),
  (9016, 20, 'Bund finanziert kommunale Jugendzentren und Jugendfreizeitinfrastruktur mit (Bund)', 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'belegt', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 20 and id not in (9010, 9011, 9012, 9013, 9014, 9015, 9016);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (9017, 20, 11, 'BE', 'Jugendfreizeiteinrichtungen in den Kiezen weiter ausbauen und modernisieren, auch digital besser ausstatten.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=109', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9018, 20, 11, 'BE', 'Calisthenikanlagen in Parks ausbauen und ungenutzte öffentliche Räume so umgestalten, dass Kinder und Jugendliche sie nutzen können.', '{2001}', 9014, 2, 3, null, 'Setzt am häufig geäußerten Wunsch nach Treffpunkten im öffentlichen Raum an; Modellvorhaben des Bundes zeigen Nutzen von Beteiligung. Belastbare Wirkungsstudien fehlen, Konflikte mit Anwohnenden bleiben möglich.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=109', 'https://www.bbsr.bund.de/BBSR/DE/forschung/programme/exwost/Forschungsfelder/2009/JugendlicheImStadtquartier/01_Start.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9019, 20, 11, 'BE', 'Jugendclubs als Orte der Begegnung und Demokratiebildung fördern, getragen von freien und öffentlichen Trägern.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=64', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9020, 20, 11, 'MV', 'Modellprojekt für mobile Kinder- und Jugendzentren im ländlichen Raum, um Jugendangebote besser erreichbar zu machen', '{2001}', 9012, 2, 3, null, 'Mobile Angebote erreichen Jugendliche, wo es keinen festen Treff gibt. Eine Wirkungsevaluation aus Österreich zeigt aber auf dem Land deutlich weniger Kontakte als in Städten und vor allem Jungen als Nutzer.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=97', 'https://austria-forum.org/web-books/jugendarbeit00de2017isds/000062', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9021, 20, 11, 'MV', 'Lokale Kulturorte und Einrichtungen, darunter Jugendclubs und mobile Clubs, flächendeckend und verlässlich fördern', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=129', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9022, 20, 11, 'ST', 'Offene Jugendarbeit und Jugendverbände dauerhaft unterstützen; Masterplan für Jugendbildungsstätten und Weiterentwicklung der Jugendpauschale für Planungssicherheit.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf#page=32', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9023, 20, 12, 'BE', 'Kinder- und Jugendfreizeitangebote ausbauen', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=38', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9024, 20, 12, 'BE', 'Mehr kostenfreie Treffpunkte („JugendOrte“) im öffentlichen Raum, nach Wünschen der Jugendlichen gestaltet und in den Bezirken dauerhaft finanziert', '{2001}', 9014, 2, 3, null, 'Setzt am häufig geäußerten Wunsch nach Treffpunkten im öffentlichen Raum an; Modellvorhaben des Bundes zeigen Nutzen von Beteiligung. Belastbare Wirkungsstudien fehlen, Konflikte mit Anwohnenden bleiben möglich.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=38', 'https://www.bbsr.bund.de/BBSR/DE/forschung/programme/exwost/Forschungsfelder/2009/JugendlicheImStadtquartier/01_Start.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9025, 20, 12, 'BE', 'Gesetzliche Lärmschutzvorgaben anpassen, damit junge Menschen nicht aus dem öffentlichen Raum verdrängt werden', '{2003}', null, 2, 2, null, 'Setzt direkt an der rechtlichen Verdrängung durch Lärmbeschwerden an; verhaltensbezogener Lärm ist seit 2006 Ländersache. Die Wirkung auf Konflikte ist kaum untersucht, der Schutz der Anwohnenden muss abgewogen werden.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=38', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9026, 20, 12, 'BE', 'Queere Jugendzentren erhalten und ausbauen', '{2001}', 9013, 1, 3, null, 'Studien verbinden die Teilnahme an queeren Jugendangeboten mit weniger psychischer Belastung der Teilnehmenden. Sie erreichen aber nur einen kleinen Teil der Jugendlichen und schaffen kaum allgemeine Treffpunkte.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=49', 'https://shine.lab.uconn.edu/wp-content/uploads/sites/3321/2021/06/eisenberg_lgbtq_orgs_2020_annals.pdf', 'belegt', '2026-10-08', false, true, 'blind'),
  (9027, 20, 12, 'MV', 'Jugendclubs, soziokulturelle Zentren und offene Dritte Orte stärken und neu schaffen, besonders im ländlichen Raum sichern und ausbauen.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf#page=36', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9028, 20, 12, 'ST', 'Jugendclubs, pädagogisch begleitete Freiräume und selbstorganisierte Räume weiter stärken; Bundesmittel für die Instandsetzung von Jugendclubs umsetzen.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=26', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9029, 20, 12, 'ST', 'Jugendbegegnungsorte mit attraktiven, bezahlbaren Freizeit- und Kulturangeboten, auch abends und außerhalb der Städte.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=26', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9030, 20, 12, 'ST', 'Verbindlicher Jugendförderplan mit Mindeststandards für Landesangebote und einfacherer Förderung.', '{2001}', 9011, 2, 2, null, 'Verbindliche Vorgaben schützen Angebote vor Kürzungen; Berlin setzt seit 2022 Mengen- und Qualitätsstandards, eine Wirkungsauswertung fehlt. Mehrkosten trägt das Land (Konnexität), Fachkräfte sind knapp.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=25', 'https://www.berlin.de/sen/jugend/jugend/jugendarbeit/', 'offen', '2026-10-08', false, true, 'blind'),
  (9031, 20, 12, 'ST', 'Kommunen mit Jugendgremien erhalten Unterstützung für Jugendbudgets und Angebote von und für Jugendliche.', '{2001}', null, 1, 3, null, 'Jugendbudgets lassen Jugendliche eigene Angebote umsetzen und stärken Beteiligung; die Summen sind meist klein und hängen davon ab, ob Kommunen Gremien einrichten. Wirkung kaum untersucht.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=25', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9032, 20, 13, null, 'Zehnjähriges Sonderprogramm für Kommunen, um Strukturen der Kinder- und Jugendarbeit aufzubauen; Mittel des Kinder- und Jugendplans aufstocken.', '{2001}', 9016, 2, 2, null, 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9033, 20, 13, null, 'Sichere, selbst gestaltete Aufenthaltsorte für Jugendliche im öffentlichen Raum schaffen.', '{2001}', null, 2, 2, null, 'Selbst gestaltete Orte im öffentlichen Raum entsprechen dem Wunsch vieler Jugendlicher; Wirkung kaum untersucht. Der Bund kann nur über Städtebauförderung beitragen, Planung liegt bei Ländern und Kommunen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=84', 'https://www.bbsr.bund.de/BBSR/DE/forschung/programme/exwost/Forschungsfelder/2009/JugendlicheImStadtquartier/01_Start.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9034, 20, 13, null, 'Kulturpass mit Guthaben für Jugendliche dauerhaft fortführen.', '{2002}', 9015, 1, 3, null, 'Guthaben senkt Kosten kultureller Freizeit, der Bund hat es bereits umgesetzt. Beim französischen Vorbild prüfte der Rechnungshof: Es verstärkt vor allem bestehende Gewohnheiten und erreicht Jugendliche aus ärmeren Familien seltener.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=125', 'https://www.livreshebdo.fr/article/pass-culture-la-cour-des-comptes-epingle-le-dispositif', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9035, 20, 13, 'BE', 'Offene Jugendarbeit und Jugendfreizeiteinrichtungen als Alternativangebot angemessen und langfristig finanziell ausstatten.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=157', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9036, 20, 13, 'BE', 'Angebote für Kinder und Jugendliche sichern und rechte Kader aus Jugendclubs fernhalten.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=181', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9037, 20, 13, 'BE', 'In jedem Bezirk mindestens einen queeren Ort (Zentrum, Jugendclub oder Familienzentrum) schaffen.', '{2001}', 9013, 1, 3, null, 'Studien verbinden die Teilnahme an queeren Jugendangeboten mit weniger psychischer Belastung der Teilnehmenden. Sie erreichen aber nur einen kleinen Teil der Jugendlichen und schaffen kaum allgemeine Treffpunkte.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=150', 'https://shine.lab.uconn.edu/wp-content/uploads/sites/3321/2021/06/eisenberg_lgbtq_orgs_2020_annals.pdf', 'belegt', '2026-10-08', false, true, 'blind'),
  (9038, 20, 13, 'BE', 'Leerstehende Erdgeschossflächen zu gedeckelten Mieten unter anderem an Jugendeinrichtungen vergeben.', '{2001}', null, 1, 2, null, 'Günstige Räume können Jugendeinrichtungen ermöglichen, Jugendliche sind aber nur eine von mehreren Zielgruppen; ob Leerstand verfügbar ist, hängt von den Eigentümern ab.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=56', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9039, 20, 13, 'MV', 'Flächendeckendes, niedrigschwelliges Angebot an Jugendclubs und weiteren Orten für junge Menschen unterstützen; offene Kinder- und Jugendarbeit fördern.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://gruene-mv.de/?wpdmdl=33772#page=64', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9040, 20, 13, 'MV', 'Jugendkultur stärken: Stabsstelle in der Staatskanzlei, Landesliegenschaften auf Doppelnutzung prüfen, ausreichende Finanzierung.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://gruene-mv.de/?wpdmdl=33772#page=64', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9041, 20, 13, 'MV', 'Soziale Präventionsarbeit der Kommunen wie Streetwork und Jugendclubs finanziell stärken.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://gruene-mv.de/?wpdmdl=33772#page=76', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9042, 20, 13, 'ST', 'Jugendorte schaffen und ausbauen, vor allem unbeplante Räume und selbstverwaltete Jugendzentren in kleineren Städten und Gemeinden.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=56', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9043, 20, 14, 'BE', 'Finanzierung des Parkläufer-Projekts dauerhaft sichern, um Nutzungskonflikte in Grünanlagen niedrigschwellig zu entschärfen.', '{2003}', null, 1, 3, null, 'Parkläufer entschärfen Nutzungskonflikte in Grünanlagen niedrigschwellig; sie richten sich nicht gezielt an Jugendliche und setzen auch Parkordnungen gegen sie durch. Wirkung kaum ausgewertet.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=70', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9044, 20, 14, 'ST', 'Landesmittel der Kinder- und Jugendhilfe werden an die Preisentwicklung gekoppelt, damit die Jugendarbeit Planungssicherheit hat.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://www.fdp-lsa.de/sites/default/files/2026-07/fdpwahlprogrammltw2026.pdf#page=35', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9045, 20, 15, 'BE', 'Jugendhäuser und Jugendfreizeiteinrichtungen sollen sichere, für alle einladende Orte sein; Jugendzentren erhalten ein neues Konzept.', '{2001}', null, 1, 3, null, 'Sichere, einladende Jugendhäuser können mehr Jugendliche anziehen; die Zusage bleibt unbestimmt und schafft keine zusätzlichen Orte.', 'https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf#page=63', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9046, 20, 16, null, 'Freizeit-, Musik- und Sporteinrichtungen für Kinder und Jugendliche wohnortnah und gebührenfrei machen; Kommunen und Kinder- und Jugendplan des Bundes dafür besser finanzieren.', '{2001,2002}', null, 2, 1, null, 'Gebührenfreie, wohnortnahe Angebote senken die Kostenhürde direkt; Gutscheinprogramme erhöhten Teilnahme, ein Teil nutzte Angebote aber schon vorher. Der Bund kann kommunale Gebühren nicht abschaffen, die Kosten sind hoch.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=16', 'https://hfjc.library.ubc.ca/index.php/HFJC/article/view/383', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9047, 20, 16, null, 'Jugendzentren als Teil der Daseinsvorsorge ausreichend über die Kommunen finanzieren (Infrastrukturgarantie).', '{2001}', 9016, 2, 2, null, 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=44', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9048, 20, 16, null, 'Queere Jugendzentren schützen und queere Jugendarbeit zur kommunalen Pflichtaufgabe machen.', '{2001}', null, 1, 1, null, 'Sichert Angebote für eine kleine Gruppe Jugendlicher. Der Bund darf Gemeinden keine Aufgaben übertragen (Art. 84 GG), eine kommunale Pflichtaufgabe müssten die Länder festlegen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=47', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9049, 20, 16, 'BE', 'Jugendclubs, Abenteuerspielplätze und selbstverwaltete Treffpunkte als Räume für Jugendliche sichern und ausbauen.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=177', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9050, 20, 16, 'BE', 'Mindestens ein selbstverwalteter Jugendort in jedem Bezirk.', '{2001}', null, 1, 3, null, 'Jugendorte wirken nachweislich, ein selbstverwalteter Ort je Bezirk ist aber nur eine kleine Zahl zusätzlicher Treffpunkte; mit überschaubaren Kosten umsetzbar.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=177', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9051, 20, 16, 'BE', 'Zweckbindung der Mittel für Jugendclubs, damit Bezirke sie nicht anderweitig ausgeben.', '{2001}', null, 1, 2, null, 'Zweckbindung verhindert, dass Mittel für Jugendclubs abfließen, schafft aber kein zusätzliches Geld oder Angebot; sie greift in die Haushaltsautonomie der Bezirke ein.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=181', null, 'offen', '2026-10-08', false, true, 'blind'),
  (9052, 20, 16, 'MV', 'Kinder- und Jugendarbeit als kommunale Pflichtaufgabe festschreiben und den Landesjugendplan bedarfsgerecht ausfinanzieren; Jugendverbände und Ferienfreizeiten gezielt fördern.', '{2001}', 9011, 2, 2, null, 'Verbindliche Vorgaben schützen Angebote vor Kürzungen; Berlin setzt seit 2022 Mengen- und Qualitätsstandards, eine Wirkungsauswertung fehlt. Mehrkosten trägt das Land (Konnexität), Fachkräfte sind knapp.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=11', 'https://www.berlin.de/sen/jugend/jugend/jugendarbeit/', 'offen', '2026-10-08', false, true, 'blind'),
  (9053, 20, 16, 'ST', 'Jugendarbeit wird gesetzlicher Anspruch für alle jungen Menschen, mit höherer Landesförderung besonders im ländlichen Raum.', '{2001}', 9011, 2, 2, null, 'Verbindliche Vorgaben schützen Angebote vor Kürzungen; Berlin setzt seit 2022 Mengen- und Qualitätsstandards, eine Wirkungsauswertung fehlt. Mehrkosten trägt das Land (Konnexität), Fachkräfte sind knapp.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=61', 'https://www.berlin.de/sen/jugend/jugend/jugendarbeit/', 'offen', '2026-10-08', false, true, 'blind'),
  (9054, 20, 16, 'ST', 'Leerstand soll zu Freiräumen für Jugendliche werden, gemeinsam mit ihnen gestaltet und genutzt.', '{2001}', 9014, 2, 3, null, 'Setzt am häufig geäußerten Wunsch nach Treffpunkten im öffentlichen Raum an; Modellvorhaben des Bundes zeigen Nutzen von Beteiligung. Belastbare Wirkungsstudien fehlen, Konflikte mit Anwohnenden bleiben möglich.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=63', 'https://www.bbsr.bund.de/BBSR/DE/forschung/programme/exwost/Forschungsfelder/2009/JugendlicheImStadtquartier/01_Start.html', 'offen', '2026-10-08', false, true, 'blind'),
  (9055, 20, 16, 'ST', 'In jedem Ortsteil soll ein Jugendort in etwa 15 Minuten erreichbar sein, wo er fehlt ein mobiles Angebot.', '{2001}', null, 3, 2, null, 'Ein Jugendort in 15 Minuten in jedem Ortsteil setzt mit klarer Zielgröße direkt am Mangel an Treffpunkten an; der Nutzen von Jugendclubs ist belegt. Flächendeckend braucht das Jahre, Geld und knappe Fachkräfte.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=64', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9056, 20, 17, null, 'Staat soll Freizeittreffs für Jugendliche (und Ältere) flächendeckend gewährleisten (Infrastruktur-Garantie).', '{2001}', 9016, 2, 2, null, 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=16', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9057, 20, 17, null, 'Investitionsprogramm für kinder- und jugendgerechte Infrastruktur mit wohnortnahem, niedrigschwelligem Zugang zu Jugendfreizeiteinrichtungen, Sportstätten und Musikschulen.', '{2001}', 9016, 2, 2, null, 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=32', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9058, 20, 17, null, 'Bund bezahlt allen Kindern das erste Jahr im Sportverein mit einem Zuschuss.', '{2002}', null, 1, 2, null, 'Ein Zuschuss für das erste Vereinsjahr senkt die Einstiegskosten; ein Gutscheinprogramm in Australien erhöhte die Aktivität, ohne Kontrollgruppe. Danach fallen die Kosten wieder an; Sportförderung ist überwiegend Ländersache.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', 'https://hfjc.library.ubc.ca/index.php/HFJC/article/view/383', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9059, 20, 17, 'BE', 'Angebote der Jugendarbeit ausbauen, zusammen mit Sprachkursen und Integrationsangeboten.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf#page=40', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9060, 20, 17, 'MV', 'Jugendclubs, Freizeithäuser und offene Treffpunkte langfristig absichern und verlässlich finanzieren', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf#page=13', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9061, 20, 17, 'MV', 'Selbstorganisierte, ehrenamtlich von jungen Menschen gestaltete Jugendarbeit stärken', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf#page=13', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9062, 20, 17, 'ST', 'Jugendclubs als soziale Räume für junge Menschen erhalten.', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://st.bsw-vg.de/wp-content/uploads/2026/04/BSW_Landtagswahlprogramm_SachsenAnhalt.pdf#page=74', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9063, 20, 18, null, 'Jugendtreffs, Clubs und Ateliers als Räume für Jugendliche schützen und gezielt fördern', '{2001}', 9016, 2, 2, null, 'Jugendclubs wirken nachweislich; mehr Geld für Kommunen kann Schließungen verhindern. Der Bund kann aber nur über Investitions- und Förderprogramme beitragen, laufende Jugendarbeit ist Sache von Ländern und Kommunen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=158', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9064, 20, 18, null, 'Kulturpass für junge Menschen über 2024 hinaus verlängern', '{2002}', 9015, 1, 3, null, 'Guthaben senkt Kosten kultureller Freizeit, der Bund hat es bereits umgesetzt. Beim französischen Vorbild prüfte der Rechnungshof: Es verstärkt vor allem bestehende Gewohnheiten und erreicht Jugendliche aus ärmeren Familien seltener.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=158', 'https://www.livreshebdo.fr/article/pass-culture-la-cour-des-comptes-epingle-le-dispositif', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9065, 20, 18, 'BE', 'Jugendzentren, Sport- und Kulturangebote sowie mobile Angebote in besonders belasteten Quartieren ausbauen', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=37', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9066, 20, 18, 'BE', 'Träger der Jugendarbeit durch dauerhafte Finanzierung statt kurzfristiger Projektförderung absichern', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=38', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9067, 20, 18, 'MV', 'Mobile Projekte und Jugendtreffs als soziale Angebote auch in abgelegenen ländlichen Regionen sichern, damit Jugendliche Zugang zu Freizeitangeboten haben.', '{2001}', 9012, 2, 3, null, 'Mobile Angebote erreichen Jugendliche, wo es keinen festen Treff gibt. Eine Wirkungsevaluation aus Österreich zeigt aber auf dem Land deutlich weniger Kontakte als in Städten und vor allem Jungen als Nutzer.', 'https://voltdeutschland.org/storage/assets-mv/pdf/haltungzeigen_wahlprogramm_voltmv_ltw26.pdf#page=14', 'https://austria-forum.org/web-books/jugendarbeit00de2017isds/000062', 'gemischt', '2026-10-08', false, true, 'blind'),
  (9068, 20, 18, 'ST', 'Jugendtreffs wieder aufbauen und langfristig sichern, besonders im ländlichen Raum', '{2001}', 9010, 2, 2, null, 'Schließungen von Jugendclubs (London 2010–2019) verschlechterten nachweislich Schulleistungen und erhöhten Jugendkriminalität. Ohne Zielgröße oder Betrag bleibt offen, wie viele Orte gesichert werden; Fachkräfte sind knapp.', 'https://voltdeutschland.org/storage/assets-sachsen-anhalt/pdf/landtagswahl-2026/wahlprogramm_volt_lv_lsa.pdf#page=27', 'https://www.iser.essex.ac.uk/research/publications/publication-588442', 'belegt', '2026-10-08', false, true, 'blind'),
  (9069, 20, 18, 'ST', 'Mobile Jugendarbeit und aufsuchende Angebote in strukturschwachen Regionen fördern', '{2001}', 9012, 2, 3, null, 'Mobile Angebote erreichen Jugendliche, wo es keinen festen Treff gibt. Eine Wirkungsevaluation aus Österreich zeigt aber auf dem Land deutlich weniger Kontakte als in Städten und vor allem Jungen als Nutzer.', 'https://voltdeutschland.org/storage/assets-sachsen-anhalt/pdf/landtagswahl-2026/wahlprogramm_volt_lv_lsa.pdf#page=27', 'https://austria-forum.org/web-books/jugendarbeit00de2017isds/000062', 'gemischt', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (9010, 20),
  (9011, 20),
  (9012, 20),
  (9013, 20),
  (9014, 20),
  (9015, 20),
  (9016, 20),
  (9025, 20),
  (9031, 20),
  (9033, 20),
  (9038, 20),
  (9043, 20),
  (9045, 20),
  (9046, 20),
  (9048, 20),
  (9050, 20),
  (9051, 20),
  (9055, 20),
  (9058, 20);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (20, 11, null, 'keine', 'Inhaltsverzeichnis, Kapitel Familie/Kinder und Jugendliche (S. 62-66), Sport (S. 60-61) und Fundstellen S. 26, 72, 79 gelesen; nichts zu Jugendtreffs, Teilhabekosten für Freizeit oder Nutzungskonflikten im öffentlichen Raum. Grep nach Freizeit, Jugend, Spielplatz, Lärm, Treffpunkt ohne passende Zusage.', '2026-10-08', true, '{2001,2002,2003}'),
  (20, 11, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 11, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 11, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 12, null, 'keine', 'Kapitel 9 (Familien, S. 25-28), Kapitel 18 (Kultur und Sport, S. 49-52), Kapitel 19 (S. 52-54) und Fundstellen S. 4, 7, 24, 26, 30, 32, 35, 53 gelesen; keine Zusage zu Jugendtreffs, Jugendarbeit, Freizeitkosten oder Nutzungskonflikten im öffentlichen Raum.', '2026-10-08', true, '{2001,2002,2003}'),
  (20, 12, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 12, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 12, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 13, null, 'massnahmen', null, '2026-10-08', true, '{2001,2002,2003}'),
  (20, 13, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 13, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 13, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 14, null, 'keine', 'Erfasste Stellen (S. 32) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-08', true, '{2001,2002,2003}'),
  (20, 14, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 14, 'MV', 'keine', 'Inhaltsverzeichnis, Kapitel Kommunen (S. 75-77), Kinder-/Jugendrechte (S. 109), kulturelle Bildung (S. 107-108), Ehrenamt (S. 121-122) und alle Fundstellen (S. 19, 35, 49, 75, 107, 108, 112) gelesen; keine konkrete Zusage zu Jugendtreffs, Freizeitangeboten für Jugendliche oder Nutzungsregeln im öffentlichen Raum.', '2026-10-08', true, '{2001,2003}'),
  (20, 14, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 15, null, 'keine', 'Kapitel ''Familie und Demografie'' (S. 145-156), ''Kultur und Medienpolitik'' (S. 171-177) und Volltextsuche nach Jugend, Freizeit, Treffpunkt, Sport, Lärm, Musikschul gelesen; alle Fundstellen S. 15, 68, 69, 92, 155, 175 sind Zufallstreffer (Umsatzsteuer, Bargeld, Bitcoin, Energie, Familienmediation, Rundfunk). Nichts zu Jugendtreffs, Teilhabekosten oder Nutzungskonflikten.', '2026-10-08', true, '{2001,2002,2003}'),
  (20, 15, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 15, 'MV', 'keine', 'Familien-/Jugendkapitel (S. 19-23), Schule/Sport (S. 32-33), ÖPNV (S. 70), Kultur (S. 91-92) und Fundstellen (S. 2, 8, 13, 82-84, 90) gelesen; nichts zu Jugendtreffs, Freizeitorten für Jugendliche oder Lärm-/Raumregeln. Fundstellen sind Fehltreffer (Inhaltsverzeichnis, Photovoltaik, Wirtschaft, Windkraft).', '2026-10-08', true, '{2001,2003}'),
  (20, 15, 'ST', 'keine', 'Kapitel ''Familie und Kinder'' (S. 10-22) und Fundstelle S. 112 gelesen, dazu Volltextsuche nach Jugendzentrum, Jugendarbeit, Jugendliche, Treffpunkt, Freizeit, Skate, Bolzplatz, Spielplatz, Lärm; nichts setzt an Jugendtreffpunkten (2001) oder Nutzungskonflikten im öffentlichen Raum (2003) an.', '2026-10-08', true, '{2001,2003}'),
  (20, 16, null, 'massnahmen', null, '2026-10-08', true, '{2001,2002,2003}'),
  (20, 16, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 16, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 16, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 17, null, 'massnahmen', null, '2026-10-08', true, '{2001,2002,2003}'),
  (20, 17, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 17, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 17, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 18, null, 'massnahmen', null, '2026-10-08', true, '{2001,2002,2003}'),
  (20, 18, 'BE', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 18, 'MV', 'massnahmen', null, '2026-10-08', true, '{2001,2003}'),
  (20, 18, 'ST', 'massnahmen', null, '2026-10-08', true, '{2001,2003}');

commit;
