-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 33 „Mediennutzung von Kindern und Jugendlichen“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 33;
delete from public.abdeckung where thema_id = 33;
delete from public.pruef_einheiten where thema_id = 33;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (8387, 33, 'Verbindliches Handyverbot im Schulalltag bis zur Mittelstufe (Land)', 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'gemischt', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'land', null, true, 'blind'),
  (8388, 33, 'Handyverbot oder bildschirmfreie Klassen in der Grundschule (Land)', 'Weniger Ablenkung möglich, doch Effekte zeigten sich vor allem an weiterführenden Schulen mit hohem Smartphone-Besitz; in der Grundschule ist die Nutzung ohnehin geringer. Studien zu Handyregeln uneinheitlich.', 'gemischt', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'land', null, true, 'blind'),
  (8389, 33, 'Medienbildung in Schule und außerschulischen Angeboten stärken (Land)', 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'gemischt', 'https://europepmc.org/article/MED/40549948', 'land', null, true, 'blind'),
  (8390, 33, 'Schulische Prävention von Mediensucht und Mediengefahren (Land)', 'Gezielte schulische Prävention senkte problematische Nutzung deutlich (d = 1,47), Bildschirmzeit kaum (d = 0,15); Publikationsverzerrung möglich. Setzt bei den Kindern an, nicht direkt bei der Begleitung durch Eltern.', 'gemischt', 'https://europepmc.org/article/MED/40549948', 'land', null, true, 'blind'),
  (8391, 33, 'Fachkräfte in Medienbildung qualifizieren, Zentren und Teams ausbauen (Land)', 'Geschulte Fachkräfte und Zentren können Medienbildung tragen; die Wirkung auf die Mediennutzung der Kinder läuft nur über den Unterricht und ist kaum untersucht.', 'offen', null, 'land', null, true, 'blind'),
  (8392, 33, 'Eltern durch Beratung und Bildungsangebote in der Medienerziehung unterstützen (Land)', 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'gemischt', 'https://europepmc.org/article/MED/40549948', 'land', null, true, 'blind'),
  (8393, 33, 'Eltern mit Informationen zur Mediennutzung versorgen (Land)', 'Leicht und schnell umsetzbar; Information erreicht aber nur, wer sie nutzt, und die Wirkung auf die Begleitung durch Eltern ist kaum untersucht.', 'offen', null, 'land', null, true, 'blind'),
  (8394, 33, 'Digital Services Act umsetzen mit Schwerpunkt Jugendschutz (Bund)', 'Der DSA verpflichtet Plattformen zu Risikoprüfungen auch zu Minderjährigen; die Wirkung auf Likes- und Belohnungsdesign ist bisher kaum untersucht. Umsetzung durch den Bund ist möglich.', 'offen', null, 'bund', null, true, 'blind'),
  (8395, 33, 'Medienkompetenz in Schulen und Lehrplänen stärken (Bund)', 'Schulische Medienbildung wirkt gegen problematische Nutzung, aber kaum auf die Bildschirmzeit; Schulen und Lehrpläne sind Ländersache, der Bund kann nur Anreize setzen.', 'gemischt', 'https://europepmc.org/article/MED/40549948', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 33 and id not in (8387, 8388, 8389, 8390, 8391, 8392, 8393, 8394, 8395);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (8396, 33, 11, null, 'Kinder- und Jugendschutz im Netz einschließlich sozialer Medien gewährleisten; bei der Umsetzung des Digital Services Act Jugend- und Medienschutz betonen.', '{3301}', 8394, 1, 3, null, 'Der DSA verpflichtet Plattformen zu Risikoprüfungen auch zu Minderjährigen; die Wirkung auf Likes- und Belohnungsdesign ist bisher kaum untersucht. Umsetzung durch den Bund ist möglich.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=41', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8397, 33, 11, 'BE', 'Medienkompetenz wird an allen Schulen verbindlicher Bestandteil des Unterrichts; Schülerinnen und Schüler lernen kritischen und verantwortungsvollen Umgang mit Medien.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=63', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8398, 33, 11, 'BE', 'Lehrkräfte werden im Bereich Digitalisierung und Medienbildung verbindlich und systematisch qualifiziert.', '{3303}', 8391, 1, 3, null, 'Geschulte Fachkräfte und Zentren können Medienbildung tragen; die Wirkung auf die Mediennutzung der Kinder läuft nur über den Unterricht und ist kaum untersucht.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=60', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8399, 33, 11, 'MV', 'Landeseinheitliches Verbot privater Smartphone-Nutzung im Unterricht und auf dem Schulgelände bis Klasse zehn.', '{3302}', 8387, 2, 3, null, 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=53', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8400, 33, 11, 'MV', 'Altersgerechte Mediensensibilisierung über die Gefahren digitaler und sozialer Medien in Kindergarten und Grundschule.', '{3303}', 8390, 2, 3, null, 'Gezielte schulische Prävention senkte problematische Nutzung deutlich (d = 1,47), Bildschirmzeit kaum (d = 0,15); Publikationsverzerrung möglich. Setzt bei den Kindern an, nicht direkt bei der Begleitung durch Eltern.', 'https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf#page=53', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8401, 33, 11, 'ST', 'Medienpädagogische Angebote ausbauen und mit Schulen, Landesmedienanstalt und Trägern neue Bildungsformate für alle Generationen entwickeln.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf#page=36', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8402, 33, 11, 'ST', 'Medienbildung in der Kita altersgerecht und mit pädagogischer Begleitung einführen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf#page=49', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8403, 33, 11, 'ST', 'In Schulen Projekte und Unterrichtseinheiten, die die kritische Reflexionsfähigkeit im Umgang mit digitalen Medien stärken.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf#page=22', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8404, 33, 12, null, 'Jugendschutz im Netz stärken, unter anderem durch wirksame Möglichkeiten zur Altersverifikation.', '{3301}', null, 1, 2, null, 'Verifikation kann Altersgrenzen durchsetzen, ersetzt aber keine Designregeln; technische Umsetzung hängt an EU-Lösungen und Datenschutz.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=45', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8405, 33, 12, null, 'Plattformen müssen ihre Algorithmen zur Inhaltsdarstellung offenlegen und auf manipulative Praktiken prüfen lassen.', '{3301}', null, 1, 1, null, 'Transparenz und Prüfung machen Empfehlungsdesign sichtbar, verbieten es aber nicht; Wirkung auf Kinder kaum untersucht. Plattformregeln setzt weitgehend die EU (DSA).', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=50', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8406, 33, 12, 'BE', 'Handyverbot an allen Grundschulen durchsetzen, begründet mit Gesundheits- und Kinderschutz.', '{3302}', 8388, 1, 3, null, 'Weniger Ablenkung möglich, doch Effekte zeigten sich vor allem an weiterführenden Schulen mit hohem Smartphone-Besitz; in der Grundschule ist die Nutzung ohnehin geringer. Studien zu Handyregeln uneinheitlich.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=41', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8407, 33, 12, 'BE', 'Medienkompetenz, kritischen Umgang mit sozialen Medien und digitale Verantwortung fest in der schulischen Bildung verankern.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=41', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8408, 33, 12, 'MV', 'Medienkompetenz altersgerecht in allen Schularten stärken; Lehrkräfte durch Fortbildung und praxisnahe Materialien unterstützen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf#page=67', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8409, 33, 12, 'MV', 'Lehrkräfte, Erziehende und Bildungsstätten stärken, damit Medienkompetenz von Beginn an vermittelt wird; außerschulische Angebote für alle Altersgruppen ergänzen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf#page=44', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8410, 33, 12, 'ST', 'Medienbildung wird in allen Schulfächern fest verankert und weiter ausgebaut.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=19', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8411, 33, 13, null, 'Manipulative Algorithmen sozialer Plattformen strenger regulieren; Algorithmen, die Kinder gezielt süchtig machen, nicht dulden.', '{3301}', null, 2, 1, null, 'Regeln gegen suchtfördernde Algorithmen setzen direkt am Belohnungsdesign an, bleiben aber unbestimmt; Wirkung kaum untersucht, nationale Alleingänge begrenzt das EU-Recht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=85', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8412, 33, 13, null, 'Eltern mit sicheren Voreinstellungen für Dienste und Geräte sowie Datenschutzregeln für Kinder und Jugendliche unterstützen.', '{3303,3301}', null, 1, 2, null, 'Sichere Voreinstellungen entlasten Eltern und begrenzen riskante Funktionen von Beginn an; Wirkung auf die Nutzungsdauer kaum untersucht, Geräte- und Dienstregeln sind EU-geprägt.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=85', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8413, 33, 13, null, 'In den Schulen digitale Fähigkeiten und Medienkompetenz aufbauen.', '{3303}', 8395, 1, 1, null, 'Schulische Medienbildung wirkt gegen problematische Nutzung, aber kaum auf die Bildschirmzeit; Schulen und Lehrpläne sind Ländersache, der Bund kann nur Anreize setzen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=77', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8414, 33, 13, 'BE', 'Medienbildung als verbindlichen Teil des Unterrichts ab der 1. Klasse in allen Schulformen verankern.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=190', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8415, 33, 13, 'BE', 'Medienkompetenzzentren ausbauen und an jeder Schule Medienteams einrichten.', '{3303}', 8391, 1, 3, null, 'Geschulte Fachkräfte und Zentren können Medienbildung tragen; die Wirkung auf die Mediennutzung der Kinder läuft nur über den Unterricht und ist kaum untersucht.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=190', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8416, 33, 13, 'BE', 'Einschränkungen der privaten Handynutzung unterstützen, wenn die Schule sie für die beste Lösung hält.', '{3302}', null, 1, 3, null, 'Unterstützt nur freiwillige Entscheidungen der Schulen; ohne Verpflichtung geringere Wirkung als ein verbindliches Verbot. Studien zu Handyregeln uneinheitlich.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=190', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8417, 33, 13, 'BE', 'Medienkompetenz-Angebote für Jugendliche und Erwachsene fördern, um Sucht- und Extremismusgefahren durch Games vorzubeugen.', '{3303}', 8390, 2, 3, null, 'Gezielte schulische Prävention senkte problematische Nutzung deutlich (d = 1,47), Bildschirmzeit kaum (d = 0,15); Publikationsverzerrung möglich. Setzt bei den Kindern an, nicht direkt bei der Begleitung durch Eltern.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=103', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8418, 33, 13, 'MV', 'Medienkompetenz, auch zu Desinformation und digitaler Mündigkeit, verbindlich in Lehrerausbildung und Lehrplänen verankern.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://gruene-mv.de/?wpdmdl=33772#page=44', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8419, 33, 13, 'MV', 'Bibliotheken als Orte für Kinder und Jugendliche stärken und ihre Angebote zur Medienkompetenz ausweiten.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://gruene-mv.de/?wpdmdl=33772#page=98', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8420, 33, 13, 'ST', 'Pflichtfach Informatik und Medienbildung von Klasse 5 bis 10/11 an allen allgemeinbildenden Schulen, u. a. kritischer Umgang mit Inhalten in sozialen Medien.', '{3303}', null, 1, 2, null, 'Ein Pflichtfach verankert Medienbildung dauerhaft; Wirkung auf das Nutzungsverhalten wie bei Schulprogrammen gemischt, Lehrkräfte für ein neues Fach fehlen absehbar.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=64', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8421, 33, 13, 'ST', 'Digital- und Medienkompetenz fest in Bildung verankern, auch in Familienbildungsstätten, Jugendhilfe und Erwachsenenbildung.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=53', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8422, 33, 13, 'ST', 'Computer- und Videospiele als Thema an weiterführenden Schulen fächerübergreifend stärker behandeln und analysieren.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=85', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8423, 33, 14, null, 'Lehrpläne modernisieren und dabei mehr Raum für Medienkompetenz schaffen.', '{3303}', 8395, 1, 1, null, 'Schulische Medienbildung wirkt gegen problematische Nutzung, aber kaum auf die Bildschirmzeit; Schulen und Lehrpläne sind Ländersache, der Bund kann nur Anreize setzen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=9', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8424, 33, 14, 'BE', 'Medienkompetenz im Schulunterricht stärken, dazu Lehrkräfte und Schulsozialarbeitende aus- und weiterbilden.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=16', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8425, 33, 14, 'BE', 'Elternarbeit zur Aufklärung der Kinder über Medienkonsum und Gefahren im Netz stärken.', '{3303}', 8392, 2, 3, null, 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=17', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8426, 33, 14, 'BE', 'Eltern und Fachkräfte mit mehr Informationen zur Mediennutzung von Kindern und Jugendlichen versorgen.', '{3303}', 8393, 1, 3, null, 'Leicht und schnell umsetzbar; Information erreicht aber nur, wer sie nutzt, und die Wirkung auf die Begleitung durch Eltern ist kaum untersucht.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=17', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8427, 33, 14, 'MV', 'Eltern durch verständliche, freiwillige, wissenschaftsbasierte Informationen zu Mediennutzung, Bildschirmzeiten und digitaler Sicherheit stärken.', '{3303}', 8393, 1, 3, null, 'Leicht und schnell umsetzbar; Information erreicht aber nur, wer sie nutzt, und die Wirkung auf die Begleitung durch Eltern ist kaum untersucht.', 'https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf#page=84', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8428, 33, 14, 'MV', 'Medienbildung und kritischen, selbstbestimmten Umgang mit neuen Medien für alle Kinder und Jugendlichen als verbindlichen Lerninhalt festlegen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf#page=98', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8429, 33, 14, 'ST', 'Angebote der Medienbildung weiter ausbauen und Eltern bei der digitalen Erziehung durch Unterstützungsangebote helfen.', '{3303}', 8392, 2, 3, null, 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'https://www.fdp-lsa.de/sites/default/files/2026-07/fdpwahlprogrammltw2026.pdf#page=26', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8430, 33, 15, 'BE', 'Grundschulen bildschirmfrei halten und dort Smartphones verbieten; an weiterführenden Schulen das Mitführen von Smartphones restriktiver handhaben.', '{3302}', 8388, 1, 3, null, 'Weniger Ablenkung möglich, doch Effekte zeigten sich vor allem an weiterführenden Schulen mit hohem Smartphone-Besitz; in der Grundschule ist die Nutzung ohnehin geringer. Studien zu Handyregeln uneinheitlich.', 'https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf#page=30', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8431, 33, 15, 'MV', 'Private Handynutzung im Schulalltag bis zur 7. Klasse per Verordnung unterbinden, Ausnahmen nur bei Notfällen oder nach Rücksprache mit der Lehrkraft.', '{3302}', 8387, 2, 3, null, 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'https://afd-vg.de/wp-content/uploads/2026/06/AfD-Regierungsprogramm-Mecklenburg-Vorpommern-2026.pdf#page=31', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8432, 33, 15, 'ST', 'Smartphone-Nutzung an Schulen bis einschließlich Klasse 10 untersagen.', '{3302}', 8387, 2, 3, null, 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'https://afd-lsa.de/wp-content/uploads/2026/07/AfD_Sachsen-Anhalt_Regierungsprogramm_2026_230726-web.pdf#page=79', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8433, 33, 16, null, 'Medien- und Datenschutzkompetenz von Kindern und Jugendlichen möglichst früh fördern.', '{3303}', null, 1, 2, null, 'Frühe Förderung ist sinnvoll, nennt aber keinen Weg; Schulen sind Ländersache, der Bund kann mit Programmen und Geld beitragen. Wirkung auf die Bildschirmzeit gering.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=39', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8434, 33, 16, null, 'EU-Gesetz über digitale Dienste zügig in nationales Recht überführen.', '{3301}', 8394, 1, 3, null, 'Der DSA verpflichtet Plattformen zu Risikoprüfungen auch zu Minderjährigen; die Wirkung auf Likes- und Belohnungsdesign ist bisher kaum untersucht. Umsetzung durch den Bund ist möglich.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=57', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8435, 33, 16, 'BE', 'Medienbildung inklusive Mediensuchtprävention ab der Grundschule verbindlich in Rahmenlehrplänen und schulinternen Curricula verankern.', '{3303}', 8390, 2, 3, null, 'Gezielte schulische Prävention senkte problematische Nutzung deutlich (d = 1,47), Bildschirmzeit kaum (d = 0,15); Publikationsverzerrung möglich. Setzt bei den Kindern an, nicht direkt bei der Begleitung durch Eltern.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=165', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8436, 33, 16, 'BE', 'Schulgemeinschaften in Medienbildung schulen und Ressourcen für Elternarbeit ausbauen, um Eltern früh einzubeziehen.', '{3303}', 8392, 2, 3, null, 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=165', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8437, 33, 16, 'BE', 'Medienkompetenzzentren in allen Bezirken gut ausstatten, kostenfreie begleitete Angebote und regelmäßige Schulungen für Fachkräfte schaffen, für junge Menschen, Eltern und Fachkräfte.', '{3303}', 8392, 2, 3, null, 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=178', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8438, 33, 16, 'BE', 'Haushaltsmittel für Medienkompetenzbildung durch Freie Träger bereitstellen, entwickelt mit jungen Menschen für junge Menschen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=247', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8439, 33, 16, 'BE', 'Verbindliche Fort- und Weiterbildungsangebote für Schulbeschäftigte zu Medienbildung.', '{3303}', 8391, 1, 3, null, 'Geschulte Fachkräfte und Zentren können Medienbildung tragen; die Wirkung auf die Mediennutzung der Kinder läuft nur über den Unterricht und ist kaum untersucht.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=229', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8440, 33, 16, 'BE', 'Handyfreier Schultag bis Jahrgangsstufe 9 als Grundsatz, solange die Schulgemeinschaft keine andere Regelung beschließt.', '{3302}', 8387, 2, 3, null, 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=167', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8441, 33, 16, 'MV', 'Medienbildung auf allen Ebenen ausbauen: in der Schule, außerschulisch und für Erwachsene.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=27', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8442, 33, 16, 'MV', 'Das medienpädagogische Zentrum personell ausbauen, um Unterrichtsangebote zur Medienbildung zu stärken.', '{3303}', 8391, 1, 3, null, 'Geschulte Fachkräfte und Zentren können Medienbildung tragen; die Wirkung auf die Mediennutzung der Kinder läuft nur über den Unterricht und ist kaum untersucht.', 'https://wahlprogramm26.die-linke-mv.de/wp-content/uploads/sites/77/2026/08/LINKE-MV_LTW26_Langwahlprogramm_A4_web.pdf#page=5', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8443, 33, 16, 'ST', 'Landesprogramm zur Stärkung der Medienkompetenz und digitalen Bildung an Schulen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=74', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8444, 33, 17, null, 'Gesetz für soziale Medien nach australischem Vorbild, damit Kinder weniger in der virtuellen Welt verschwinden.', '{3301}', null, 2, 1, null, 'Altersgrenze setzt direkt am Zugang zu Likes- und Belohnungssystemen an; Erfahrungen aus Australien sind sehr jung, Umgehung möglich. Nationale Regelung stößt an EU-Recht und Länder-Jugendmedienschutz.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', null, 'offen', '2026-10-06', false, true, 'blind'),
  (8445, 33, 17, null, 'Handys und Tablets mindestens bis zum Ende der Grundschule aus den Klassenzimmern verbannen, danach möglichst wenig im Unterricht einsetzen.', '{3302}', null, 1, 1, null, 'Weniger Ablenkung im Unterricht, Abendnutzung und Schlaf bleiben unberührt; Studien uneinheitlich. Schulrecht ist Ländersache, der Bund kann nur Anreize setzen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=24', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8446, 33, 17, 'BE', 'Grundschulklassen ohne Bildschirme einrichten, um Aufmerksamkeit, Gedächtnis und Lesekompetenz zu fördern.', '{3302}', 8388, 1, 3, null, 'Weniger Ablenkung möglich, doch Effekte zeigten sich vor allem an weiterführenden Schulen mit hohem Smartphone-Besitz; in der Grundschule ist die Nutzung ohnehin geringer. Studien zu Handyregeln uneinheitlich.', 'https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf#page=16', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8447, 33, 17, 'BE', 'Smartphones im Unterricht grundsätzlich nicht nutzen und vor dem Unterricht wegschließen.', '{3302}', null, 1, 3, null, 'Wegschließen verringert Ablenkung in den Stunden, nicht aber die Nutzung in Pausen oder abends. Studien zu Handyregeln uneinheitlich.', 'https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf#page=16', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8448, 33, 17, 'BE', 'Verbindlichen digitalen Führerschein mit Nachweis von Medien-, Datenschutz- und Informationskenntnissen bis Ende Klasse 10 einführen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf#page=16', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8449, 33, 17, 'MV', 'Familienbildungs- und Beratungsangebote ausbauen, die Eltern in der Medienerziehung stärken und Orientierung im digitalen Alltag geben.', '{3303}', 8392, 2, 3, null, 'Setzt direkt bei den Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Belastbare Daten zu reinen Elternangeboten fehlen, und es erreichen vor allem interessierte Eltern.', 'https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf#page=12', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8450, 33, 17, 'MV', 'Präventionsangebote für Kinder und Jugendliche ausbauen, die auch Medienkompetenz stärken.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf#page=61', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8451, 33, 17, 'MV', 'Medienkompetenz an weiterführenden Schulen vermitteln, in der Grundschule ohne digitale Endgeräte lernen.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf#page=47', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8452, 33, 17, 'ST', 'Verbindliches Smartphone-Verbot im Schulalltag, um Ablenkung und digitale Abhängigkeiten zu verringern.', '{3302}', 8387, 2, 3, null, 'Dafür: In England, Florida und Indien stiegen die Noten leicht bis moderat, Ablenkung sank. Dagegen: In Florida, Schweden und England fanden Studien keine Effekte auf Noten oder Wohlbefinden; Abendnutzung bleibt unberührt.', 'https://st.bsw-vg.de/wp-content/uploads/2026/04/BSW_Landtagswahlprogramm_SachsenAnhalt.pdf#page=45', 'https://world-education-blog.org/2025/12/15/are-phone-bans-working/', 'gemischt', '2026-10-06', false, true, 'blind'),
  (8595, 33, 18, null, 'Manipulative Gestaltung digitaler Angebote (Dark Patterns) und algorithmische Beeinflussung werden gesetzlich geregelt.', '{3301}', null, 2, 1, null, 'Setzt direkt an belohnungs- und suchtfördernden Designs an, die eine Prüfung trotz DSA auf allen großen Plattformen fand. Dagegen: Wirkung auf die Nutzung kaum untersucht; DSA und Verbraucherrecht sind EU-weit harmonisiert, nationale Regeln kaum möglich.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=27', 'https://www.vzbv.de/en/social-media-platforms-failing-adequately-protect-minors', 'offen', '2026-10-07', false, true, 'blind'),
  (8596, 33, 18, null, 'Aufsicht über digitale Dienste einschließlich des digitalen Jugendschutzes wird bei der Bundesnetzagentur gebündelt.', '{3301}', 8394, 1, 3, null, 'Der DSA verpflichtet Plattformen zu Risikoprüfungen auch zu Minderjährigen; die Wirkung auf Likes- und Belohnungsdesign ist bisher kaum untersucht. Umsetzung durch den Bund ist möglich.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=25', null, 'offen', '2026-10-07', false, true, 'blind'),
  (8597, 33, 18, null, 'Schulungen für Eltern zu Chancen und Risiken der Digitalisierung.', '{3303}', null, 2, 2, null, 'Setzt direkt bei der Begleitung durch Eltern an; Programme mit Elternbeteiligung senkten problematische Nutzung stärker. Dagegen: reine Elternangebote kaum belegt, sie erreichen vor allem Interessierte; Elternbildung tragen Länder und Kommunen, der Bund kann fördern.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=113', 'https://real.mtak.hu/222946', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8599, 33, 18, 'BE', 'Medienkompetenz, reflektierter Umgang mit digitalen Technologien und Algorithmusverständnis werden fester Teil des Unterrichts.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=48', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8600, 33, 18, 'MV', 'Medien- und Demokratiebildung altersgerecht und fächerübergreifend ab der ersten Klasse im Unterricht verankern.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://voltdeutschland.org/storage/assets-mv/pdf/haltungzeigen_wahlprogramm_voltmv_ltw26.pdf#page=7', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8601, 33, 18, 'ST', 'Medien- und Demokratiebildung ab Klasse 1 fächerübergreifend verankern, mit Vermittlung von Plattformlogiken und kritischer Medienkompetenz.', '{3303}', 8389, 1, 3, null, 'Schulische Programme senkten problematische Nutzung deutlich, Bildschirmzeit kaum (Metaanalyse, 34 Studien, Verzerrung möglich). Allgemeine Medienbildung setzt nur indirekt an der Begleitung durch Eltern an.', 'https://voltdeutschland.org/storage/assets-sachsen-anhalt/pdf/landtagswahl-2026/wahlprogramm_volt_lv_lsa.pdf#page=30', 'https://europepmc.org/article/MED/40549948', 'gemischt', '2026-10-08', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (8387, 33),
  (8388, 33),
  (8389, 33),
  (8390, 33),
  (8391, 33),
  (8392, 33),
  (8393, 33),
  (8394, 33),
  (8395, 33),
  (8404, 33),
  (8405, 33),
  (8411, 33),
  (8412, 33),
  (8416, 33),
  (8420, 33),
  (8433, 33),
  (8444, 33),
  (8445, 33),
  (8447, 33),
  (8595, 33),
  (8597, 33);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (33, 11, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 11, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 11, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 11, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 12, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 12, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 12, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 12, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 13, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 13, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 13, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 13, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 14, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 14, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 14, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 14, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 15, null, 'keine', 'Erfasste Stellen (S. 50) setzen laut Bewertung ohne Parteinamen an keiner der Ursachen an.', '2026-10-06', true, '{3301,3302,3303}'),
  (33, 15, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 15, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 15, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 16, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 16, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 16, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 16, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 17, null, 'massnahmen', null, '2026-10-06', true, '{3301,3302,3303}'),
  (33, 17, 'BE', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 17, 'MV', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 17, 'ST', 'massnahmen', null, '2026-10-06', true, '{3302,3303}'),
  (33, 18, null, 'massnahmen', null, '2026-10-07', true, '{3301,3302,3303}'),
  (33, 18, 'BE', 'massnahmen', null, '2026-10-08', true, '{3302,3303}'),
  (33, 18, 'MV', 'massnahmen', null, '2026-10-08', true, '{3302,3303}'),
  (33, 18, 'ST', 'massnahmen', null, '2026-10-08', true, '{3302,3303}');

commit;
