-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 11 „Preise und Löhne“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 11;
delete from public.abdeckung where thema_id = 11;
delete from public.pruef_einheiten where thema_id = 11;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (6879, 11, 'Mehrwertsteuer auf Lebensmittel senken (von 7 auf 5 %)', 'Senkt die Preise einmalig um knapp 2 %, wenn der Handel die Senkung weitergibt; an den Ursachen der Preissteigerung ändert das nichts. Rechtlich und finanziell ohne große Hürden möglich.', 'gemischt', null, 'bund', null, true, null),
  (6880, 11, 'Mehrwertsteuer auf Grundnahrungsmittel abschaffen (0 %)', 'Senkt die Preise für Grundnahrungsmittel um bis zu 6,5 % und entlastet vor allem Haushalte mit wenig Geld, wenn die Senkung weitergegeben wird; seit 2022 erlaubt das EU-Recht einen Nullsatz. Dagegen spricht der hohe Steuerausfall, und ob der Handel die Senkung vollständig weitergibt, ist umstritten.', 'gemischt', null, 'bund', null, true, null),
  (6881, 11, 'Preisbeobachtung oder Preisüberwacher für Lebensmittel', 'Macht Preise und Margen entlang der Lieferkette sichtbar und kann Kartellverfahren anstoßen; ob Transparenz allein die Preise senkt, ist kaum untersucht.', 'offen', null, 'bund', null, true, null),
  (6882, 11, 'Marktbeherrschende Handelskonzerne entflechten', 'Setzt an der Konzentration im Lebensmittelhandel an; ob kleinere Händler niedrigere Preise bringen, ist offen. Eine Entflechtung ohne Rechtsverstoß ist verfassungsrechtlich umstritten und dauert Jahre.', 'gemischt', null, 'bund', null, true, null),
  (6883, 11, 'Fusionskontrolle und Wettbewerbsrecht stärken', 'Kann weitere Konzentration im Handel bremsen, wie es die Monopolkommission empfiehlt; auf die Preise wirkt das erst langfristig und nicht sicher.', 'gemischt', 'https://www.monopolkommission.de/publikationen/lebensmittel/s/wettbewerb-in-der-lebensmittellieferkette', 'bund', null, true, null),
  (6884, 11, 'Einkommensteuer für kleine und mittlere Einkommen senken, gegenfinanziert', 'Erhöht das Nettoeinkommen von Geringverdienenden und der Mitte direkt; die Gegenfinanzierung über höhere Steuern für hohe Einkommen oder Vermögen ist umsetzbar, aber politisch und rechtlich aufwendig.', 'belegt', null, 'bund', null, true, null),
  (6885, 11, 'Einkommensteuertarif abflachen und Grundfreibetrag erhöhen', 'Erhöht das Nettoeinkommen fast aller Steuerzahlenden, am stärksten in absoluten Beträgen bei höheren Einkommen; die Kosten sind hoch und die Finanzierung ist nicht geklärt.', 'belegt', null, 'bund', null, true, null),
  (6886, 11, 'Grundfreibetrag stark anheben (auf rund 15.000 Euro bzw. die Armutsgefährdungsschwelle)', 'Entlastet besonders kleine Einkommen spürbar; die Steuerausfälle lägen im hohen zweistelligen Milliardenbereich, eine Finanzierung ist nicht geklärt.', 'belegt', null, 'bund', null, true, null),
  (6887, 11, 'Sozialabgaben bei 40 % begrenzen', 'Verhindert weitere Beitragssteigerungen, senkt die Abgaben aber nicht; dafür wären Reformen in Rente, Gesundheit und Pflege nötig, die noch offen sind.', 'gemischt', null, 'bund', null, true, null),
  (6888, 11, 'Beiträge für Bürgergeldbeziehende aus Steuern statt aus Beiträgen finanzieren', 'Senkt die Kranken- und Pflegebeiträge etwas, weil der Bund die Kosten trägt; die Entlastung der Beschäftigten ist gering und belastet den Bundeshaushalt mit rund zehn Milliarden Euro im Jahr.', 'gemischt', null, 'bund', null, true, null),
  (6889, 11, 'Mindestlohn auf 15 Euro oder 60 % des Medianlohns anheben', 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'belegt', null, 'bund', null, true, null),
  (6890, 11, 'Tarifbindung stärken (Tariftreuegesetz, Allgemeinverbindlichkeit erleichtern)', 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'gemischt', null, 'bund', null, true, null),
  (6891, 11, 'Minijobs in sozialversicherungspflichtige Beschäftigung überführen', 'Minijobs sind überwiegend schlecht bezahlt; ob ihre Umwandlung zu höheren Stundenlöhnen führt oder nur zu mehr Sozialversicherung bei gleichem Netto, ist umstritten.', 'gemischt', null, 'bund', null, true, null),
  (6892, 11, 'Steuerermäßigung für Agrardiesel wieder einführen', 'Senkt die Energiekosten landwirtschaftlicher Betriebe um wenige Hundert Millionen Euro im Jahr; auf die Lebensmittelpreise wirkt das kaum.', 'offen', null, 'bund', null, true, null),
  (7228, 11, 'Geringqualifizierte zum Berufsabschluss führen (Bund)', 'Ein Berufsabschluss führt oft aus dem Niedriglohnbereich heraus, weil Fachkräfte deutlich mehr verdienen als Helfer; die Wirkung stellt sich erst über Jahre ein, und die Programme nennen kaum konkrete Instrumente.', 'gemischt', null, 'bund', null, true, null)
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 11 and id not in (6879, 6880, 6881, 6882, 6883, 6884, 6885, 6886, 6887, 6888, 6889, 6890, 6891, 6892, 7228);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (6893, 11, 11, null, 'Einkommensteuertarif schrittweise abflachen, Grundfreibetrag erhöhen', '{1104}', 6885, 2, 1, null, 'Erhöht das Nettoeinkommen fast aller Steuerzahlenden, am stärksten in absoluten Beträgen bei höheren Einkommen; die Kosten sind hoch und die Finanzierung ist nicht geklärt.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=14', null, 'belegt', '2026-09-30', false, true, null),
  (6894, 11, 11, null, 'Sozialversicherungsbeiträge wieder in Richtung 40 % senken', '{1104}', 6887, 1, 2, null, 'Verhindert weitere Beitragssteigerungen, senkt die Abgaben aber nicht; dafür wären Reformen in Rente, Gesundheit und Pflege nötig, die noch offen sind.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (6895, 11, 11, null, 'Agrardieselrückvergütung wieder vollständig einführen', '{1101}', 6892, 1, 3, null, 'Senkt die Energiekosten landwirtschaftlicher Betriebe um wenige Hundert Millionen Euro im Jahr; auf die Lebensmittelpreise wirkt das kaum.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=36', null, 'offen', '2026-09-30', false, true, null),
  (6896, 11, 12, null, 'Mehrwertsteuer auf Lebensmittel von 7 auf 5 % senken', '{1101}', 6879, 1, 3, null, 'Senkt die Preise einmalig um knapp 2 %, wenn der Handel die Senkung weitergibt; an den Ursachen der Preissteigerung ändert das nichts. Rechtlich und finanziell ohne große Hürden möglich.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=24', null, 'gemischt', '2026-09-30', false, true, null),
  (6897, 11, 12, null, 'Behörden stärken, die die Zusammensetzung von Lebensmittelpreisen öffentlich machen und Wettbewerbsverstöße prüfen', '{1102}', 6881, 1, 3, null, 'Macht Preise und Margen entlang der Lieferkette sichtbar und kann Kartellverfahren anstoßen; ob Transparenz allein die Preise senkt, ist kaum untersucht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=24', null, 'offen', '2026-09-30', false, true, null),
  (6898, 11, 12, null, 'Mindestlohn spätestens 2026 auf 15 Euro', '{1103,1105}', 6889, 2, 3, null, 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'belegt', '2026-09-30', false, true, null),
  (6899, 11, 12, null, 'Bundestariftreuegesetz, Allgemeinverbindlicherklärung erleichtern', '{1103,1105}', 6890, 1, 3, null, 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'gemischt', '2026-09-30', false, true, null),
  (6900, 11, 12, null, 'Rund 95 % der Steuerzahlenden entlasten, Spitzeneinkommen und Vermögen stärker beteiligen', '{1104}', 6884, 2, 2, null, 'Erhöht das Nettoeinkommen von Geringverdienenden und der Mitte direkt; die Gegenfinanzierung über höhere Steuern für hohe Einkommen oder Vermögen ist umsetzbar, aber politisch und rechtlich aufwendig.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'belegt', '2026-09-30', false, true, null),
  (6901, 11, 13, null, 'Wettbewerbsrecht weiterentwickeln, Verbraucher besser vor Monopolen schützen', '{1102}', 6883, 1, 3, null, 'Kann weitere Konzentration im Handel bremsen, wie es die Monopolkommission empfiehlt; auf die Preise wirkt das erst langfristig und nicht sicher.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=27', 'https://www.monopolkommission.de/publikationen/lebensmittel/s/wettbewerb-in-der-lebensmittellieferkette', 'gemischt', '2026-09-30', false, true, null),
  (6902, 11, 13, null, 'Mindestlohn zunächst 15 Euro, Referenzwert 60 % des Medianlohns', '{1103,1105}', 6889, 2, 3, null, 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=67', null, 'belegt', '2026-09-30', false, true, null),
  (6903, 11, 13, null, 'Allgemeinverbindlicherklärung erleichtern, Tariftreuegesetz', '{1103,1105}', 6890, 1, 3, null, 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=67', null, 'gemischt', '2026-09-30', false, true, null),
  (6904, 11, 13, null, 'Minijobs schrittweise in sozialversicherungspflichtige Beschäftigung überführen', '{1105}', 6891, 1, 3, null, 'Minijobs sind überwiegend schlecht bezahlt; ob ihre Umwandlung zu höheren Stundenlöhnen führt oder nur zu mehr Sozialversicherung bei gleichem Netto, ist umstritten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=69', null, 'gemischt', '2026-09-30', false, true, null),
  (6905, 11, 13, null, 'Steuergutschriften für niedrige Einkommen, Grundfreibetrag erhöhen', '{1104}', 6884, 2, 2, null, 'Erhöht das Nettoeinkommen von Geringverdienenden und der Mitte direkt; die Gegenfinanzierung über höhere Steuern für hohe Einkommen oder Vermögen ist umsetzbar, aber politisch und rechtlich aufwendig.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=74', null, 'belegt', '2026-09-30', false, true, null),
  (6906, 11, 14, null, 'Linear-progressiver Chancentarif ohne Mittelstandsbauch, Grundfreibetrag um mindestens 1.000 Euro anheben', '{1104}', 6885, 2, 1, null, 'Erhöht das Nettoeinkommen fast aller Steuerzahlenden, am stärksten in absoluten Beträgen bei höheren Einkommen; die Kosten sind hoch und die Finanzierung ist nicht geklärt.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=14', null, 'belegt', '2026-09-30', false, true, null),
  (6907, 11, 14, null, 'Sozialabgaben nicht über 40 % steigen lassen', '{1104}', 6887, 1, 2, null, 'Verhindert weitere Beitragssteigerungen, senkt die Abgaben aber nicht; dafür wären Reformen in Rente, Gesundheit und Pflege nötig, die noch offen sind.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=21', null, 'gemischt', '2026-09-30', false, true, null),
  (6908, 11, 15, null, 'Grundfreibetrag auf 15.000 Euro erhöhen und indexieren', '{1104}', 6886, 2, 1, null, 'Entlastet besonders kleine Einkommen spürbar; die Steuerausfälle lägen im hohen zweistelligen Milliardenbereich, eine Finanzierung ist nicht geklärt.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=59', null, 'belegt', '2026-09-30', false, true, null),
  (6909, 11, 15, null, 'Krankenversicherung der Bürgergeldbeziehenden vollständig aus dem Bundeshaushalt zahlen, um Beitragserhöhungen zu verhindern', '{1104}', 6888, 1, 2, null, 'Senkt die Kranken- und Pflegebeiträge etwas, weil der Bund die Kosten trägt; die Entlastung der Beschäftigten ist gering und belastet den Bundeshaushalt mit rund zehn Milliarden Euro im Jahr.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=22', null, 'gemischt', '2026-09-30', false, true, null),
  (6910, 11, 16, null, 'Grundnahrungsmittel von der Mehrwertsteuer befreien, Weitergabe gesetzlich sichern', '{1101}', 6880, 2, 2, null, 'Senkt die Preise für Grundnahrungsmittel um bis zu 6,5 % und entlastet vor allem Haushalte mit wenig Geld, wenn die Senkung weitergegeben wird; seit 2022 erlaubt das EU-Recht einen Nullsatz. Dagegen spricht der hohe Steuerausfall, und ob der Handel die Senkung vollständig weitergibt, ist umstritten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=6', null, 'gemischt', '2026-09-30', false, true, null),
  (6911, 11, 16, null, 'Monopole im Lebensmittelhandel zerschlagen, Preiswächter mit Durchgriffsrechten', '{1102}', 6882, 1, 1, null, 'Setzt an der Konzentration im Lebensmittelhandel an; ob kleinere Händler niedrigere Preise bringen, ist offen. Eine Entflechtung ohne Rechtsverstoß ist verfassungsrechtlich umstritten und dauert Jahre.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=6', null, 'gemischt', '2026-09-30', false, true, null),
  (6912, 11, 16, null, 'Neue Preisaufsicht als unabhängige Bundesbehörde', '{1102}', 6881, 1, 3, null, 'Macht Preise und Margen entlang der Lieferkette sichtbar und kann Kartellverfahren anstoßen; ob Transparenz allein die Preise senkt, ist kaum untersucht.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=7', null, 'offen', '2026-09-30', false, true, null),
  (6913, 11, 16, null, 'Übergewinnsteuer von 90 % auf Extragewinne in Krisen', '{1102}', null, 1, 1, null, 'Soll Anreize nehmen, Preise in Krisen über die Kosten hinaus zu erhöhen; ob das die Preise senkt, ist kaum untersucht. Die Abgrenzung von Übergewinnen ist rechtlich schwierig, ein Satz von 90 % verfassungsrechtlich umstritten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=7', null, 'offen', '2026-09-30', false, true, null),
  (6914, 11, 16, null, 'Steuern für die Mehrheit senken, Vermögensteuer für sehr große Vermögen', '{1104}', 6884, 2, 2, null, 'Erhöht das Nettoeinkommen von Geringverdienenden und der Mitte direkt; die Gegenfinanzierung über höhere Steuern für hohe Einkommen oder Vermögen ist umsetzbar, aber politisch und rechtlich aufwendig.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=10', null, 'belegt', '2026-09-30', false, true, null),
  (6915, 11, 16, null, 'Mindestlohn mindestens 15 Euro, spätestens 2026 16 Euro', '{1103,1105}', 6889, 2, 3, null, 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'belegt', '2026-09-30', false, true, null),
  (6916, 11, 16, null, 'Bundestariftreuegesetz und Aktionsplan für Tarifbindung', '{1103,1105}', 6890, 1, 3, null, 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=26', null, 'gemischt', '2026-09-30', false, true, null),
  (6917, 11, 16, null, 'Volle Sozialversicherung ab dem ersten Euro statt Minijobs', '{1105}', 6891, 1, 3, null, 'Minijobs sind überwiegend schlecht bezahlt; ob ihre Umwandlung zu höheren Stundenlöhnen führt oder nur zu mehr Sozialversicherung bei gleichem Netto, ist umstritten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=26', null, 'gemischt', '2026-09-30', false, true, null),
  (6918, 11, 17, null, 'Bundeskartellamt für wirksame Fusionskontrolle stärken', '{1102}', 6883, 1, 3, null, 'Kann weitere Konzentration im Handel bremsen, wie es die Monopolkommission empfiehlt; auf die Preise wirkt das erst langfristig und nicht sicher.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=15', 'https://www.monopolkommission.de/publikationen/lebensmittel/s/wettbewerb-in-der-lebensmittellieferkette', 'gemischt', '2026-09-30', false, true, null),
  (6919, 11, 17, null, 'Grundfreibetrag deutlich erhöhen, an der Armutsgefährdungsschwelle orientiert', '{1104}', 6886, 2, 1, null, 'Entlastet besonders kleine Einkommen spürbar; die Steuerausfälle lägen im hohen zweistelligen Milliardenbereich, eine Finanzierung ist nicht geklärt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=17', null, 'belegt', '2026-09-30', false, true, null),
  (6920, 11, 17, null, 'Freibetrag bei den Sozialabgaben, gegenfinanziert durch höhere Beitragsbemessungsgrenzen', '{1104}', null, 2, 2, null, 'Entlastet kleine Einkommen bei den Sozialabgaben, die für sie oft schwerer wiegen als die Einkommensteuer; gegenfinanziert durch höhere Beiträge besser Verdienender. Die Umsetzung in allen Sozialversicherungen ist aufwendig, Vorbilder gibt es nur bei Midijobs.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=17', null, 'offen', '2026-09-30', false, true, null),
  (6921, 11, 17, null, 'Streichung der Agrardiesel-Ermäßigung zurücknehmen', '{1101}', 6892, 1, 3, null, 'Senkt die Energiekosten landwirtschaftlicher Betriebe um wenige Hundert Millionen Euro im Jahr; auf die Lebensmittelpreise wirkt das kaum.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=19', null, 'offen', '2026-09-30', false, true, null),
  (6922, 11, 17, null, 'Mindestlohn unverzüglich auf 15 Euro', '{1103,1105}', 6889, 2, 3, null, 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'belegt', '2026-09-30', false, true, null),
  (6923, 11, 17, null, 'Minijobs in sozialversicherungspflichtige Beschäftigung überführen', '{1105}', 6891, 1, 3, null, 'Minijobs sind überwiegend schlecht bezahlt; ob ihre Umwandlung zu höheren Stundenlöhnen führt oder nur zu mehr Sozialversicherung bei gleichem Netto, ist umstritten.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'gemischt', '2026-09-30', false, true, null),
  (6924, 11, 17, null, 'Öffentliche Aufträge nur an Unternehmen mit Tariflohn, Allgemeinverbindlichkeit erleichtern', '{1103,1105}', 6890, 1, 3, null, 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'gemischt', '2026-09-30', false, true, null),
  (6925, 11, 17, null, 'Beiträge für Bürgergeldbeziehende aus Steuern finanzieren', '{1104}', 6888, 1, 2, null, 'Senkt die Kranken- und Pflegebeiträge etwas, weil der Bund die Kosten trägt; die Entlastung der Beschäftigten ist gering und belastet den Bundeshaushalt mit rund zehn Milliarden Euro im Jahr.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=26', null, 'gemischt', '2026-09-30', false, true, null),
  (6926, 11, 17, null, 'Starkes Kartellrecht, marktbeherrschende Konzerne entflechten', '{1102}', 6882, 1, 1, null, 'Setzt an der Konzentration im Lebensmittelhandel an; ob kleinere Händler niedrigere Preise bringen, ist offen. Eine Entflechtung ohne Rechtsverstoß ist verfassungsrechtlich umstritten und dauert Jahre.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=31', null, 'gemischt', '2026-09-30', false, true, null),
  (6927, 11, 17, null, 'Preisüberwacher nach Schweizer Vorbild', '{1102}', 6881, 1, 3, null, 'Macht Preise und Margen entlang der Lieferkette sichtbar und kann Kartellverfahren anstoßen; ob Transparenz allein die Preise senkt, ist kaum untersucht.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=31', null, 'offen', '2026-09-30', false, true, null),
  (6928, 11, 17, null, 'Mehrwertsteuer auf Grundnahrungsmittel auf 0 %', '{1101}', 6880, 2, 2, null, 'Senkt die Preise für Grundnahrungsmittel um bis zu 6,5 % und entlastet vor allem Haushalte mit wenig Geld, wenn die Senkung weitergegeben wird; seit 2022 erlaubt das EU-Recht einen Nullsatz. Dagegen spricht der hohe Steuerausfall, und ob der Handel die Senkung vollständig weitergibt, ist umstritten.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=31', null, 'gemischt', '2026-09-30', false, true, null),
  (7229, 11, 11, null, 'Menschen in Helfertätigkeiten auf dem Weg zur Fachkraft fördern', '{1105}', 7228, 1, 2, null, 'Ein Berufsabschluss führt oft aus dem Niedriglohnbereich heraus, weil Fachkräfte deutlich mehr verdienen als Helfer; die Wirkung stellt sich erst über Jahre ein, und die Programme nennen kaum konkrete Instrumente.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=15', null, 'gemischt', '2026-09-30', false, true, null),
  (7230, 11, 16, null, 'Anspruch auf verlängerte Umschulung und erleichterte Externenprüfung für Menschen ohne Ausbildung', '{1105}', 7228, 1, 2, null, 'Ein Berufsabschluss führt oft aus dem Niedriglohnbereich heraus, weil Fachkräfte deutlich mehr verdienen als Helfer; die Wirkung stellt sich erst über Jahre ein, und die Programme nennen kaum konkrete Instrumente.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=40', null, 'gemischt', '2026-09-30', false, true, null),
  (8533, 11, 18, null, 'Energiesteuer auf das nach EU-Recht zulässige Minimum senken, langfristig auf EU-Ebene abschaffen', '{1101}', null, 1, 1, null, 'Steuersenkungen auf Kraftstoff wurden 2022 zu knapp 90 % weitergegeben; auf Lebensmittelpreise wirkt Energiesteuer nur indirekt und gering. Der Steuerausfall läge im zweistelligen Milliardenbereich ohne Finanzierung, die Abschaffung hängt an der EU.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', 'https://www.leuphana.de/institute/ivwl/aktuell/ansicht/2024/08/27/neue-publikation-von-mats-kahl-in-energy-economics.html', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8534, 11, 18, null, 'Grundnahrungsmittel wie Brot, Obst und Gemüse von der Mehrwertsteuer befreien, gegenfinanziert über die Erbschaftsteuer', '{1101}', 6880, 2, 2, null, 'Senkt die Preise für Grundnahrungsmittel um bis zu 6,5 % und entlastet vor allem Haushalte mit wenig Geld, wenn die Senkung weitergegeben wird; seit 2022 erlaubt das EU-Recht einen Nullsatz. Dagegen spricht der hohe Steuerausfall, und ob der Handel die Senkung vollständig weitergibt, ist umstritten.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=101', null, 'gemischt', '2026-10-07', false, true, null),
  (8535, 11, 18, null, 'Mindestlohn auf 60 % des Medianbruttolohns anheben und regelmäßig anpassen', '{1103,1105}', 6889, 2, 3, null, 'Erhöht die Löhne im Niedriglohnbereich direkt; Studien zur Einführung 2015 und zur Erhöhung 2022 fanden kaum Jobverluste. Der Bundestag kann die Höhe per Gesetz festlegen, wie 2022 geschehen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=89', null, 'belegt', '2026-10-07', false, true, null),
  (8536, 11, 18, null, 'Tarifbindung stärken', '{1103,1105}', 6890, 1, 3, null, 'Wer nach Tarif arbeitet, verdient im Schnitt mehr; Tariftreue greift aber nur bei öffentlichen Aufträgen, und wie stark die Tarifbindung dadurch steigt, ist offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=89', null, 'gemischt', '2026-10-07', false, true, null),
  (8537, 11, 18, null, 'Grundfreibetrag moderat anheben, um kleine und mittlere Einkommen zu entlasten', '{1104}', null, 1, 3, null, 'Erhöht das Nettoeinkommen aller Steuerpflichtigen, die Entlastung bleibt bei moderater Anhebung aber klein (eher zweistellige Euro im Monat). Der Grundfreibetrag wird regelmäßig per Gesetz angehoben, die Kosten von einigen Milliarden Euro sind tragbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=99', null, 'belegt', '2026-10-07', false, true, 'blind'),
  (8538, 11, 18, null, 'Umschulungen und maßgeschneiderte Weiterbildung mit Lohnkostenzuschüssen für Langzeitarbeitslose', '{1105}', 7228, 1, 2, null, 'Ein Berufsabschluss führt oft aus dem Niedriglohnbereich heraus, weil Fachkräfte deutlich mehr verdienen als Helfer; die Wirkung stellt sich erst über Jahre ein, und die Programme nennen kaum konkrete Instrumente.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=120', null, 'gemischt', '2026-10-07', false, true, null);

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (6879, 11),
  (6880, 11),
  (6881, 11),
  (6882, 11),
  (6883, 11),
  (6884, 11),
  (6885, 11),
  (6886, 11),
  (6887, 11),
  (6888, 11),
  (6889, 11),
  (6890, 11),
  (6891, 11),
  (6892, 11),
  (6913, 11),
  (6920, 11),
  (7228, 11),
  (8533, 11),
  (8537, 11);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (11, 11, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 12, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 13, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 14, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 15, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 16, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 17, null, 'massnahmen', null, '2026-09-30', true, null),
  (11, 18, null, 'massnahmen', null, '2026-10-07', true, '{1101,1102,1103,1104,1105}');

commit;
