-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 15 „Autofahren“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 15;
delete from public.abdeckung where thema_id = 15;
delete from public.pruef_einheiten where thema_id = 15;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (7011, 15, 'CO₂-Preis auf Kraftstoffe abschaffen', 'Senkt den Spritpreis 2026 um rund 15 bis 18 Cent je Liter; ab 2028 gilt aber der europäische Emissionshandel für Verkehr, den Deutschland nicht allein abschaffen kann. Die Einnahmen fehlen für Entlastungen an anderer Stelle.', 'belegt', null, 'bund', null, true, null),
  (7012, 15, 'CO₂-Einnahmen als Klimageld oder Klimabonus zurückzahlen', 'Gleicht die Mehrkosten durch den CO₂-Preis für viele Haushalte aus, senkt den Spritpreis aber nicht; wer viel fahren muss, wird nur teilweise entlastet. Ein Auszahlungsweg an alle Haushalte muss erst aufgebaut werden.', 'gemischt', null, 'bund', null, true, null),
  (7013, 15, 'Pendlerpauschale erhöhen', 'Entlastet Pendelnde über die Steuer; wer wenig verdient und kaum Steuern zahlt, hat wenig davon.', 'gemischt', null, 'bund', null, true, null),
  (7014, 15, 'Kaufförderung für Elektroautos für kleine und mittlere Einkommen (Prämie, Steuerabzug, Leasing)', 'Setzt direkt am Preis an, den Haushalte als größtes Hindernis nennen; soziales Leasing hat in Frankreich viele Haushalte mit kleinem Einkommen erreicht. Frühere Prämien in Deutschland wurden zum Teil mitgenommen und kamen vor allem besser Verdienenden zugute.', 'gemischt', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'bund', null, true, null),
  (7015, 15, 'Öffentliche Ladeinfrastruktur ausbauen und Ladepreise senken', 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'gemischt', null, 'bund', null, true, null),
  (7258, 15, 'Elektro- und verbrauchsarme Fahrzeuge fördern, um weniger Kraftstoff zu brauchen (Bund, Ölabhängigkeit)', 'Jedes ersetzte Verbrennerfahrzeug braucht kein Benzin oder Diesel mehr. Bei 4,1 % Elektroanteil im Pkw-Bestand (1. 1. 2026) und langer Erneuerungszeit wirkt das erst über Jahre und schützt nicht vor einem Preisschock im laufenden Jahr.', 'gemischt', 'https://www.kba.de/DE/Presse/Pressemitteilungen/Fahrzeugbestand/2026/pm09_fz_bestand_pm_komplett.html', 'bund', null, true, null),
  (7259, 15, 'Alternative Kraftstoffe wie E-Fuels zulassen und gleichstellen (Bund, Ölabhängigkeit)', 'Strombasierte Kraftstoffe entkoppeln den Preis vom Rohöl, sind aber nicht kommerziell verfügbar und würden zunächst etwa 2 Euro je Liter kosten (Benzin im Großhandel 0,50). Bis 2035 deckt es höchstens die Hälfte des Bedarfs von Luft-, Schifffahrt und Chemie. Das Verbrennerverbot ist EU-Recht.', 'offen', 'https://www.pik-potsdam.de/members/Ueckerdt/E-Fuels_Stand-und-Projektionen_PIK-Potsdam.pdf', 'bund', null, true, null),
  (7260, 15, 'Energie- und Umsatzsteuer in Preiskrisen schnell senken (Bund)', 'Senkt den Preis sofort, aber nur befristet; der Tankrabatt 2026 kam laut Monopolkommission zu einem großen Teil, aber nicht vollständig an. Die schnelle Senkung der Umsatzsteuer braucht EU-Zustimmung. Das Programm nennt Güter des täglichen Bedarfs, nicht nur Kraftstoff.', 'gemischt', 'https://www.monopolkommission.de/fileadmin/monopolkommission/Indexierte_Dateien/PDFs/Policy_Briefs/Monopolkommission-Policy-Brief-16-2026-Tankrabatt.pdf#page=1', 'bund', null, true, null),
  (8554, 15, 'Energiesteuer auf Kraftstoffe dauerhaft auf den EU-Mindestsatz senken (Bund)', 'Senkt Benzin um rund 30 Cent, Diesel um 14 Cent je Liter vor Mehrwertsteuer; 2022 kam die Senkung bei Benzin voll, bei Diesel nur teilweise an. Dauerhaft fehlen rund 12 Mrd. Euro im Jahr; die Abschaffung auf EU-Ebene braucht Einstimmigkeit.', 'belegt', 'https://www.zew.de/PU84325', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 15 and id not in (7011, 7012, 7013, 7014, 7015, 7258, 7259, 7260, 8554);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (7016, 15, 11, null, 'Pendlerpauschale erhöhen', '{1502}', 7013, 1, 3, null, 'Entlastet Pendelnde über die Steuer; wer wenig verdient und kaum Steuern zahlt, hat wenig davon.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (7017, 15, 11, null, 'Klimabonus aus den CO₂-Einnahmen', '{1502}', 7012, 1, 2, null, 'Gleicht die Mehrkosten durch den CO₂-Preis für viele Haushalte aus, senkt den Spritpreis aber nicht; wer viel fahren muss, wird nur teilweise entlastet. Ein Auszahlungsweg an alle Haushalte muss erst aufgebaut werden.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', null, 'gemischt', '2026-09-30', false, true, null),
  (7018, 15, 11, null, 'Ladeinfrastruktur angemessen ausbauen', '{1505}', 7015, 1, 3, null, 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=74', null, 'gemischt', '2026-09-30', false, true, null),
  (7019, 15, 12, null, 'Befristeter Steuerabzugsbetrag für in Deutschland produzierte E-Autos, auch Gebrauchte und Leasing', '{1504}', 7014, 2, 3, null, 'Setzt direkt am Preis an, den Haushalte als größtes Hindernis nennen; soziales Leasing hat in Frankreich viele Haushalte mit kleinem Einkommen erreicht. Frühere Prämien in Deutschland wurden zum Teil mitgenommen und kamen vor allem besser Verdienenden zugute.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=7', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7020, 15, 12, null, 'Laden an öffentlichen Ladesäulen günstiger als Tanken, Schnellladepflicht für Tankstellen', '{1505}', 7015, 1, 3, null, 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=7', null, 'gemischt', '2026-09-30', false, true, null),
  (7021, 15, 12, null, 'Klimageld, wenn ab 2027 der europäische CO₂-Preis gilt', '{1502}', 7012, 1, 2, null, 'Gleicht die Mehrkosten durch den CO₂-Preis für viele Haushalte aus, senkt den Spritpreis aber nicht; wer viel fahren muss, wird nur teilweise entlastet. Ein Auszahlungsweg an alle Haushalte muss erst aufgebaut werden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (7022, 15, 13, null, 'Staatliche Unterstützung beim Kauf verbrauchsarmer E-Autos, Social Leasing, Ladekarte', '{1504}', 7014, 2, 3, null, 'Setzt direkt am Preis an, den Haushalte als größtes Hindernis nennen; soziales Leasing hat in Frankreich viele Haushalte mit kleinem Einkommen erreicht. Frühere Prämien in Deutschland wurden zum Teil mitgenommen und kamen vor allem besser Verdienenden zugute.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=40', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7023, 15, 13, null, 'Überzogene Preise an Ladesäulen beenden', '{1505}', 7015, 1, 3, null, 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=40', null, 'gemischt', '2026-09-30', false, true, null),
  (7024, 15, 13, null, 'Sozial gestaffeltes Klimageld aus den CO₂-Einnahmen', '{1502}', 7012, 1, 2, null, 'Gleicht die Mehrkosten durch den CO₂-Preis für viele Haushalte aus, senkt den Spritpreis aber nicht; wer viel fahren muss, wird nur teilweise entlastet. Ein Auszahlungsweg an alle Haushalte muss erst aufgebaut werden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=40', null, 'gemischt', '2026-09-30', false, true, null),
  (7025, 15, 14, null, 'Energiesteuer auf Kraftstoffe bis auf null abschmelzen, CO₂-Preis soll sie ersetzen, Kfz-Steuer abschaffen', '{1502}', null, 1, 1, null, 'Ersetzt eine Steuer durch den CO₂-Preis; ob Sprit dadurch billiger wird, hängt von dessen Höhe ab. Die EU-Mindestsätze kann Deutschland nicht allein ändern.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=17', null, 'offen', '2026-09-30', false, true, null),
  (7026, 15, 15, null, 'Energiesteuer senken', '{1502}', null, 2, 2, null, 'Senkt den Spritpreis direkt; die Tankrabatte 2022 und 2026 wurden laut Monopolkommission großteils weitergegeben. Eine dauerhafte Senkung kostet je 10 Cent mehrere Milliarden Euro im Jahr, eine Gegenfinanzierung nennt das Programm nicht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', 'https://www.monopolkommission.de/fileadmin/monopolkommission/Indexierte_Dateien/PDFs/Policy_Briefs/Monopolkommission-Policy-Brief-16-2026-Tankrabatt.pdf', 'belegt', '2026-09-30', false, true, null),
  (7027, 15, 15, null, 'CO₂-Abgaben ersatzlos abschaffen', '{1502}', 7011, 2, 1, null, 'Senkt den Spritpreis 2026 um rund 15 bis 18 Cent je Liter; ab 2028 gilt aber der europäische Emissionshandel für Verkehr, den Deutschland nicht allein abschaffen kann. Die Einnahmen fehlen für Entlastungen an anderer Stelle.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=58', null, 'belegt', '2026-09-30', false, true, null),
  (7028, 15, 16, null, 'Soziales Klimageld von 320 Euro im Jahr pro Person', '{1502}', 7012, 1, 2, null, 'Gleicht die Mehrkosten durch den CO₂-Preis für viele Haushalte aus, senkt den Spritpreis aber nicht; wer viel fahren muss, wird nur teilweise entlastet. Ein Auszahlungsweg an alle Haushalte muss erst aufgebaut werden.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=7', null, 'gemischt', '2026-09-30', false, true, null),
  (7029, 15, 16, null, 'Sozial gestaffelte Förderung kleiner E-Fahrzeuge für Pendelnde auf dem Land', '{1504}', 7014, 2, 3, null, 'Setzt direkt am Preis an, den Haushalte als größtes Hindernis nennen; soziales Leasing hat in Frankreich viele Haushalte mit kleinem Einkommen erreicht. Frühere Prämien in Deutschland wurden zum Teil mitgenommen und kamen vor allem besser Verdienenden zugute.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7030, 15, 16, null, 'Investitionen in öffentliche Ladeinfrastruktur mit günstigen Tarifen', '{1505}', 7015, 1, 3, null, 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', null, 'gemischt', '2026-09-30', false, true, null),
  (7031, 15, 16, null, 'Pendlerpauschale durch ein Mobilitätsgeld ersetzen', '{1502}', null, 1, 3, null, 'Ein fester Betrag je Kilometer entlastet Pendelnde mit kleinem Einkommen stärker als die Pauschale, besser Verdienende weniger; der Spritpreis selbst ändert sich nicht.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=36', null, 'offen', '2026-09-30', false, true, null),
  (7032, 15, 17, null, 'CO₂-Preis abschaffen', '{1502}', 7011, 2, 1, null, 'Senkt den Spritpreis 2026 um rund 15 bis 18 Cent je Liter; ab 2028 gilt aber der europäische Emissionshandel für Verkehr, den Deutschland nicht allein abschaffen kann. Die Einnahmen fehlen für Entlastungen an anderer Stelle.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'belegt', '2026-09-30', false, true, null),
  (7033, 15, 17, null, 'Volksleasing für umweltfreundliche Fahrzeuge aus europäischer Produktion, Kaufprämien im niedrigen Preissegment', '{1504}', 7014, 2, 3, null, 'Setzt direkt am Preis an, den Haushalte als größtes Hindernis nennen; soziales Leasing hat in Frankreich viele Haushalte mit kleinem Einkommen erreicht. Frühere Prämien in Deutschland wurden zum Teil mitgenommen und kamen vor allem besser Verdienenden zugute.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=29', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7261, 15, 12, null, 'Befristeter Steuerabzugsbetrag für in Deutschland produzierte E-Autos, auch Gebrauchte und Leasing', '{1501}', 7258, 1, 3, null, 'Jedes ersetzte Verbrennerfahrzeug braucht kein Benzin oder Diesel mehr. Bei 4,1 % Elektroanteil im Pkw-Bestand (1. 1. 2026) und langer Erneuerungszeit wirkt das erst über Jahre und schützt nicht vor einem Preisschock im laufenden Jahr.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=7', 'https://www.kba.de/DE/Presse/Pressemitteilungen/Fahrzeugbestand/2026/pm09_fz_bestand_pm_komplett.html', 'gemischt', '2026-10-01', false, true, null),
  (7262, 15, 13, null, 'Staatliche Unterstützung beim Kauf verbrauchsarmer E-Autos, Social Leasing, Ladekarte', '{1501}', 7258, 1, 3, null, 'Jedes ersetzte Verbrennerfahrzeug braucht kein Benzin oder Diesel mehr. Bei 4,1 % Elektroanteil im Pkw-Bestand (1. 1. 2026) und langer Erneuerungszeit wirkt das erst über Jahre und schützt nicht vor einem Preisschock im laufenden Jahr.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=40', 'https://www.kba.de/DE/Presse/Pressemitteilungen/Fahrzeugbestand/2026/pm09_fz_bestand_pm_komplett.html', 'gemischt', '2026-10-01', false, true, null),
  (7263, 15, 16, null, 'Sozial gestaffelte Förderung kleiner E-Fahrzeuge für Pendelnde auf dem Land', '{1501}', 7258, 1, 3, null, 'Jedes ersetzte Verbrennerfahrzeug braucht kein Benzin oder Diesel mehr. Bei 4,1 % Elektroanteil im Pkw-Bestand (1. 1. 2026) und langer Erneuerungszeit wirkt das erst über Jahre und schützt nicht vor einem Preisschock im laufenden Jahr.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', 'https://www.kba.de/DE/Presse/Pressemitteilungen/Fahrzeugbestand/2026/pm09_fz_bestand_pm_komplett.html', 'gemischt', '2026-10-01', false, true, null),
  (7264, 15, 17, null, 'Volksleasing für umweltfreundliche Fahrzeuge aus europäischer Produktion, Kaufprämien im niedrigen Preissegment', '{1501}', 7258, 1, 3, null, 'Jedes ersetzte Verbrennerfahrzeug braucht kein Benzin oder Diesel mehr. Bei 4,1 % Elektroanteil im Pkw-Bestand (1. 1. 2026) und langer Erneuerungszeit wirkt das erst über Jahre und schützt nicht vor einem Preisschock im laufenden Jahr.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=29', 'https://www.kba.de/DE/Presse/Pressemitteilungen/Fahrzeugbestand/2026/pm09_fz_bestand_pm_komplett.html', 'gemischt', '2026-10-01', false, true, null),
  (7265, 15, 11, null, 'Technologieoffenheit: E-Fuels, Wasserstoff und nachhaltige Biokraftstoffe neben der Elektromobilität nutzen', '{1501}', 7259, 1, 1, null, 'Strombasierte Kraftstoffe entkoppeln den Preis vom Rohöl, sind aber nicht kommerziell verfügbar und würden zunächst etwa 2 Euro je Liter kosten (Benzin im Großhandel 0,50). Bis 2035 deckt es höchstens die Hälfte des Bedarfs von Luft-, Schifffahrt und Chemie. Das Verbrennerverbot ist EU-Recht.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=75', 'https://www.pik-potsdam.de/members/Ueckerdt/E-Fuels_Stand-und-Projektionen_PIK-Potsdam.pdf', 'offen', '2026-10-01', false, true, null),
  (7266, 15, 14, null, 'Statt eines Verbrennerverbots alternative Kraftstoffe wie E-Fuels ermöglichen', '{1501}', 7259, 1, 1, null, 'Strombasierte Kraftstoffe entkoppeln den Preis vom Rohöl, sind aber nicht kommerziell verfügbar und würden zunächst etwa 2 Euro je Liter kosten (Benzin im Großhandel 0,50). Bis 2035 deckt es höchstens die Hälfte des Bedarfs von Luft-, Schifffahrt und Chemie. Das Verbrennerverbot ist EU-Recht.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=42', 'https://www.pik-potsdam.de/members/Ueckerdt/E-Fuels_Stand-und-Projektionen_PIK-Potsdam.pdf', 'offen', '2026-10-01', false, true, null),
  (7267, 15, 15, null, 'Synthetische Kraftstoffe berücksichtigen und bei den Abgaben wie Elektrofahrzeuge behandeln', '{1501}', 7259, 1, 1, null, 'Strombasierte Kraftstoffe entkoppeln den Preis vom Rohöl, sind aber nicht kommerziell verfügbar und würden zunächst etwa 2 Euro je Liter kosten (Benzin im Großhandel 0,50). Bis 2035 deckt es höchstens die Hälfte des Bedarfs von Luft-, Schifffahrt und Chemie. Das Verbrennerverbot ist EU-Recht.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=44', 'https://www.pik-potsdam.de/members/Ueckerdt/E-Fuels_Stand-und-Projektionen_PIK-Potsdam.pdf', 'offen', '2026-10-01', false, true, null),
  (7268, 15, 17, null, 'Verbrauchsarme Verbrenner und alternative Kraftstoffe fördern', '{1501}', 7259, 1, 1, null, 'Strombasierte Kraftstoffe entkoppeln den Preis vom Rohöl, sind aber nicht kommerziell verfügbar und würden zunächst etwa 2 Euro je Liter kosten (Benzin im Großhandel 0,50). Bis 2035 deckt es höchstens die Hälfte des Bedarfs von Luft-, Schifffahrt und Chemie. Das Verbrennerverbot ist EU-Recht.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', 'https://www.pik-potsdam.de/members/Ueckerdt/E-Fuels_Stand-und-Projektionen_PIK-Potsdam.pdf', 'offen', '2026-10-01', false, true, null),
  (7269, 15, 11, null, 'In angespannter Lage Energie- und Umsatzsteuer für Güter des täglichen Bedarfs schnell senken dürfen', '{1501}', 7260, 1, 1, null, 'Senkt den Preis sofort, aber nur befristet; der Tankrabatt 2026 kam laut Monopolkommission zu einem großen Teil, aber nicht vollständig an. Die schnelle Senkung der Umsatzsteuer braucht EU-Zustimmung. Das Programm nennt Güter des täglichen Bedarfs, nicht nur Kraftstoff.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=14', 'https://www.monopolkommission.de/fileadmin/monopolkommission/Indexierte_Dateien/PDFs/Policy_Briefs/Monopolkommission-Policy-Brief-16-2026-Tankrabatt.pdf#page=1', 'gemischt', '2026-10-01', false, true, null),
  (7270, 15, 11, null, 'Europäischen Energiebinnenmarkt stärken, internationale Energiepartnerschaften ausbauen', '{1501}', null, 1, 3, null, 'Mehr Lieferländer machen Deutschland weniger anfällig für Preissprünge bei einzelnen Lieferanten; die Maßnahme nennt weder Öl noch konkrete Schritte.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'offen', '2026-10-01', false, true, null),
  (7271, 15, 17, null, 'Langfristige Lieferverträge für Energieimporte nach dem niedrigsten Preis', '{1501}', null, 1, 2, null, 'Langfristige Verträge können Preisschwankungen dämpfen, binden aber auch an Preise, wenn der Markt fällt; die Maßnahme nennt kein Öl, sondern Energieimporte allgemein.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'offen', '2026-10-01', false, true, null),
  (8001, 15, 16, null, 'Ablehnung des europäischen Emissionshandels für Wärme und Verkehr (ETS-2); stattdessen verbindliche Klimaziele und Emissionsgrenzen, damit kein CO₂-Preis auf Kraftstoffe entsteht.', '{1502}', 7011, 2, 1, null, 'Senkt den Spritpreis 2026 um rund 15 bis 18 Cent je Liter; ab 2028 gilt aber der europäische Emissionshandel für Verkehr, den Deutschland nicht allein abschaffen kann. Die Einnahmen fehlen für Entlastungen an anderer Stelle.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=33', null, 'belegt', '2026-10-05', false, true, null),
  (8555, 15, 18, null, 'Energiesteuer auf das nach EU-Recht zulässige Minimum senken, langfristig auf EU-Ebene ganz abschaffen.', '{1502}', 8554, 2, 2, null, 'Senkt Benzin um rund 30 Cent, Diesel um 14 Cent je Liter vor Mehrwertsteuer; 2022 kam die Senkung bei Benzin voll, bei Diesel nur teilweise an. Dauerhaft fehlen rund 12 Mrd. Euro im Jahr; die Abschaffung auf EU-Ebene braucht Einstimmigkeit.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', 'https://www.zew.de/PU84325', 'belegt', '2026-10-07', false, true, 'blind'),
  (8556, 15, 18, null, 'Dieselsteuer schrittweise an die Benzinsteuer angleichen.', '{1502}', null, 0, 3, null, 'Die Angleichung verteuert Diesel um gut 18 Cent je Liter (mit Mehrwertsteuer rund 22 Cent) und macht das Fahren für Dieselfahrende teurer statt günstiger; rechtlich mit einfachem Gesetz möglich und bringt dem Bund Einnahmen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=62', 'https://www.umweltbundesamt.de/en/press/pressinformation/environmentally-harmful-subsidies-in-transport', 'belegt', '2026-10-07', false, true, 'blind'),
  (8557, 15, 18, null, 'Ausbau der Ladeinfrastruktur für E-Fahrzeuge.', '{1505}', 7015, 1, 3, null, 'Hilft, wer nicht zu Hause laden kann, vor allem in Mehrparteienhäusern; öffentliches Laden bleibt aber meist teurer und aufwendiger als eine eigene Wallbox.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=70', null, 'gemischt', '2026-10-07', false, true, null);

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (7011, 15),
  (7012, 15),
  (7013, 15),
  (7014, 15),
  (7015, 15),
  (7025, 15),
  (7026, 15),
  (7031, 15),
  (7258, 15),
  (7259, 15),
  (7260, 15),
  (7270, 15),
  (7271, 15),
  (8554, 15),
  (8556, 15);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (15, 11, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 12, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 13, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 14, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 15, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 16, null, 'massnahmen', null, '2026-10-05', true, null),
  (15, 17, null, 'massnahmen', null, '2026-10-01', true, null),
  (15, 18, null, 'massnahmen', null, '2026-10-07', true, '{1501,1502,1503,1504,1505}');

commit;
