-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 16 „Heizungstausch“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 16;
delete from public.abdeckung where thema_id = 16;
delete from public.pruef_einheiten where thema_id = 16;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (7034, 16, 'Zuschüsse für neue klimafreundliche Heizungen fortführen oder ausbauen', 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'gemischt', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'bund', null, true, null),
  (7035, 16, 'Wärmepumpen-Leasing oder Wärme-Contracting ohne hohe Startinvestition', 'Nimmt Haushalten die hohe Anfangsinvestition ab, die laut KfW oft fehlt; solche Angebote gibt es bisher nur vereinzelt, ihre Wirkung in der Breite ist kaum untersucht.', 'offen', null, 'bund', null, true, null),
  (7036, 16, 'Heizungsgesetz abschaffen, freie Wahl der Heizung', 'Schafft Wahlfreiheit und beendet den Streit um die 65-Prozent-Vorgabe; ist aber selbst eine weitere Änderung der Regeln, und mit dem steigenden CO₂-Preis bleibt offen, welche Heizung sich langfristig lohnt. 2026 mit dem Gebäudemodernisierungsgesetz weitgehend umgesetzt.', 'gemischt', null, 'bund', null, true, null),
  (7037, 16, 'Geltende Vorgaben beibehalten, Planungssicherheit bis 2045', 'Vermeidet weitere Wechsel der Regeln; die Vorgaben selbst waren stark umstritten, und ob sie Regierungswechsel überdauern, ist offen – 2026 wurden sie grundlegend geändert.', 'gemischt', null, 'bund', null, true, null),
  (7038, 16, 'Kommunale Wärmeplanung und Wärmenetze fördern', 'Beschleunigt die Wärmepläne, auf die viele Eigentümer warten, und den Bau von Wärmenetzen; planen und bauen müssen die Kommunen, der Bund kann nur Geld und Beratung geben.', 'gemischt', 'https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/analysen-kompakt/2026/ak-09-2026.html', 'bund', null, true, null),
  (7039, 16, 'Modernisierungsumlage für energetische Sanierung abschaffen, Warmmietenneutralität', 'Schützt Mieterinnen und Mieter vor Mietsteigerungen durch den Heizungstausch; zugleich sinkt der Anreiz für Vermieter, die Heizung zu erneuern, sodass Mieter länger die Kosten alter Heizungen tragen können.', 'gemischt', null, 'bund', null, true, null),
  (7158, 16, 'Kommunale Wärmeplanung und Wärmenetze unterstützen: Beratung, Personal, Förderung (Landesprogramm)', 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'gemischt', null, 'land', null, true, null),
  (7159, 16, 'Kommunale Wärmeplanung vereinfachen, realistische Vorgaben (Landesprogramm)', 'Kann die Planung für kleine Gemeinden beschleunigen; wenn Pläne gröber werden, wissen Eigentümer aber weniger genau, was kommt.', 'offen', null, 'land', null, true, null),
  (7160, 16, 'Pflicht zur kommunalen Wärmeplanung abschaffen (Landesprogramm)', 'Nimmt Kommunen eine Pflicht ab und Eigentümern das Warten auf einen Plan, schafft aber keine Klarheit, ob ein Wärmenetz kommt. Die Pflicht steht im Bundesrecht; das Land kann nur sein Ausführungsgesetz ändern oder im Bundesrat werben.', 'offen', null, 'land', null, true, null)
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 16 and id not in (7034, 7035, 7036, 7037, 7038, 7039, 7158, 7159, 7160);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (7040, 16, 11, null, 'Heizungsgesetz der Ampel abschaffen, technologieoffene Wärmelösungen', '{1602}', 7036, 1, 3, null, 'Schafft Wahlfreiheit und beendet den Streit um die 65-Prozent-Vorgabe; ist aber selbst eine weitere Änderung der Regeln, und mit dem steigenden CO₂-Preis bleibt offen, welche Heizung sich langfristig lohnt. 2026 mit dem Gebäudemodernisierungsgesetz weitgehend umgesetzt.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'gemischt', '2026-09-30', false, true, null),
  (7041, 16, 11, null, 'Verlässliche, technologieoffene Förderung', '{1601}', 7034, 2, 3, null, 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7042, 16, 12, null, 'Förderung vor allem für die, die sich den Umstieg sonst nicht leisten können', '{1601}', 7034, 2, 3, null, 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=33', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7043, 16, 12, null, 'Beschlossene Gesetze umsetzen, Planungssicherheit', '{1602}', 7037, 1, 3, null, 'Vermeidet weitere Wechsel der Regeln; die Vorgaben selbst waren stark umstritten, und ob sie Regierungswechsel überdauern, ist offen – 2026 wurden sie grundlegend geändert.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=33', null, 'gemischt', '2026-09-30', false, true, null),
  (7044, 16, 12, null, 'Lokale Wärmepläne und Kommunen mit Fördermitteln unterstützen', '{1603}', 7038, 2, 2, null, 'Beschleunigt die Wärmepläne, auf die viele Eigentümer warten, und den Bau von Wärmenetzen; planen und bauen müssen die Kommunen, der Bund kann nur Geld und Beratung geben.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=33', 'https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/analysen-kompakt/2026/ak-09-2026.html', 'gemischt', '2026-09-30', false, true, null),
  (7045, 16, 12, null, 'Soziales Wärmepumpen-Leasing für ärmere Haushalte', '{1601,1604}', 7035, 2, 2, null, 'Nimmt Haushalten die hohe Anfangsinvestition ab, die laut KfW oft fehlt; solche Angebote gibt es bisher nur vereinzelt, ihre Wirkung in der Breite ist kaum untersucht.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', null, 'offen', '2026-09-30', false, true, null),
  (7046, 16, 13, null, 'Gebäudeenergiegesetz beibehalten, Planungssicherheit bis 2045', '{1602}', 7037, 1, 3, null, 'Vermeidet weitere Wechsel der Regeln; die Vorgaben selbst waren stark umstritten, und ob sie Regierungswechsel überdauern, ist offen – 2026 wurden sie grundlegend geändert.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', null, 'gemischt', '2026-09-30', false, true, null),
  (7047, 16, 13, null, 'Förderung von bis zu 70 % ausbauen', '{1601}', 7034, 2, 3, null, 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7048, 16, 13, null, 'Wärme-Contracting durch Stadtwerke und Firmen', '{1601}', 7035, 2, 2, null, 'Nimmt Haushalten die hohe Anfangsinvestition ab, die laut KfW oft fehlt; solche Angebote gibt es bisher nur vereinzelt, ihre Wirkung in der Breite ist kaum untersucht.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', null, 'offen', '2026-09-30', false, true, null),
  (7049, 16, 13, null, 'Klimakomponente im Wohngeld stärken', '{1604}', null, 1, 3, null, 'Hilft Haushalten mit Wohngeld, höhere Heizkosten oder Mieten nach einer Sanierung zu tragen; erreicht nur Wohngeldbeziehende und ändert nichts daran, ob die Heizung erneuert wird.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', null, 'gemischt', '2026-09-30', false, true, null),
  (7050, 16, 14, null, 'Heizungsgesetz vollständig auslaufen lassen, CO₂-Zertifikatehandel statt Einzelvorschriften', '{1602}', 7036, 1, 3, null, 'Schafft Wahlfreiheit und beendet den Streit um die 65-Prozent-Vorgabe; ist aber selbst eine weitere Änderung der Regeln, und mit dem steigenden CO₂-Preis bleibt offen, welche Heizung sich langfristig lohnt. 2026 mit dem Gebäudemodernisierungsgesetz weitgehend umgesetzt.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=45', null, 'gemischt', '2026-09-30', false, true, null),
  (7051, 16, 14, null, 'Kappungsgrenzen bei energetischen Sanierungen lockern', '{1604}', null, 1, 3, null, 'Erhöht den Anreiz für Vermieter, Heizung und Gebäude zu erneuern, was Heizkosten der Mieter senken kann; zugleich dürfen Mieten nach der Sanierung stärker steigen.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=44', null, 'gemischt', '2026-09-30', false, true, null),
  (7052, 16, 15, null, 'Gebäudeenergiegesetz abschaffen, Verbot von Gas- und Ölheizungen aufheben', '{1602}', 7036, 1, 3, null, 'Schafft Wahlfreiheit und beendet den Streit um die 65-Prozent-Vorgabe; ist aber selbst eine weitere Änderung der Regeln, und mit dem steigenden CO₂-Preis bleibt offen, welche Heizung sich langfristig lohnt. 2026 mit dem Gebäudemodernisierungsgesetz weitgehend umgesetzt.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=37', null, 'gemischt', '2026-09-30', false, true, null),
  (7053, 16, 16, null, 'Heizungstausch nach Einkommen fördern, bis zu 100 % für niedrige Einkommen; 25 Mrd. Euro im Jahr', '{1601}', null, 2, 1, null, 'Beseitigt die Kostenhürde für Haushalte mit kleinem und mittlerem Einkommen weitgehend; 25 Milliarden Euro im Jahr sind ein Vielfaches der heutigen Förderung, die Finanzierung hängt an neuen Steuern.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (7054, 16, 16, null, 'Umlage für energetische Sanierung abschaffen, Warmmietenneutralität verankern', '{1604}', 7039, 1, 3, null, 'Schützt Mieterinnen und Mieter vor Mietsteigerungen durch den Heizungstausch; zugleich sinkt der Anreiz für Vermieter, die Heizung zu erneuern, sodass Mieter länger die Kosten alter Heizungen tragen können.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (7055, 16, 16, null, 'Vermieter verpflichten, Fördermittel zu nutzen und weiterzugeben', '{1604}', null, 1, 2, null, 'Kann die Kosten für Mieter senken, wenn saniert wird; eine Pflicht zur Förderung ist ungewöhnlich und schwer durchzusetzen, und sie verpflichtet nicht zur Sanierung selbst.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=34', null, 'offen', '2026-09-30', false, true, null),
  (7056, 16, 16, null, 'Städte und Gemeinden beim Ausbau von Nah- und Fernwärmenetzen unterstützen', '{1603}', 7038, 2, 2, null, 'Beschleunigt die Wärmepläne, auf die viele Eigentümer warten, und den Bau von Wärmenetzen; planen und bauen müssen die Kommunen, der Bund kann nur Geld und Beratung geben.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=35', 'https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/analysen-kompakt/2026/ak-09-2026.html', 'gemischt', '2026-09-30', false, true, null),
  (7057, 16, 17, null, 'Einbau von Wärmepumpen fördern, ohne andere Technologien zu benachteiligen', '{1601}', 7034, 2, 3, null, 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-09-30', false, true, null),
  (7058, 16, 17, null, 'Heizungsgesetz sofort abschaffen und durch sinnvolle Regelungen ersetzen', '{1602}', 7036, 1, 3, null, 'Schafft Wahlfreiheit und beendet den Streit um die 65-Prozent-Vorgabe; ist aber selbst eine weitere Änderung der Regeln, und mit dem steigenden CO₂-Preis bleibt offen, welche Heizung sich langfristig lohnt. 2026 mit dem Gebäudemodernisierungsgesetz weitgehend umgesetzt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-30', false, true, null),
  (7059, 16, 17, null, 'Ausbau der Fernwärme unterstützen', '{1603}', 7038, 2, 2, null, 'Beschleunigt die Wärmepläne, auf die viele Eigentümer warten, und den Bau von Wärmenetzen; planen und bauen müssen die Kommunen, der Bund kann nur Geld und Beratung geben.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=12', 'https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/analysen-kompakt/2026/ak-09-2026.html', 'gemischt', '2026-09-30', false, true, null),
  (7161, 16, 11, 'ST', 'Kommunale Wärmeplanung realistisch und bezahlbar gestalten', '{1603}', 7159, 1, 3, null, 'Kann die Planung für kleine Gemeinden beschleunigen; wenn Pläne gröber werden, wissen Eigentümer aber weniger genau, was kommt.', 'https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf#page=46', null, 'offen', '2026-09-30', false, true, null),
  (7162, 16, 12, 'ST', 'Kommunen fachlich und finanziell bei der Wärmeplanung unterstützen', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf#page=24', null, 'gemischt', '2026-09-30', false, true, null),
  (7163, 16, 13, 'ST', 'Kommunen und Heizungsbesitzer bei der Wärmewende und Wärmeplanung stärker unterstützen', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf#page=25', null, 'gemischt', '2026-09-30', false, true, null),
  (7164, 16, 14, 'ST', 'Kommunen sollen Nahwärmenetze aufbauen können, auch mit Kooperationen oder Konzessionen', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://www.fdp-lsa.de/sites/default/files/2026-07/fdpwahlprogrammltw2026.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (7165, 16, 15, 'ST', 'Landesgesetz zur Wärmeplanung abschaffen, im Bundesrat für Abschaffung des Wärmeplanungsgesetzes', '{1603}', 7160, 1, 1, null, 'Nimmt Kommunen eine Pflicht ab und Eigentümern das Warten auf einen Plan, schafft aber keine Klarheit, ob ein Wärmenetz kommt. Die Pflicht steht im Bundesrecht; das Land kann nur sein Ausführungsgesetz ändern oder im Bundesrat werben.', 'https://afd-lsa.de/wp-content/uploads/2026/07/AfD_Sachsen-Anhalt_Regierungsprogramm_2026_230726-web.pdf#page=158', null, 'offen', '2026-09-30', false, true, null),
  (7166, 16, 16, 'ST', 'Kommunale Wärmeplanung fachlich und finanziell unterstützen, Wärmenetze auch auf dem Land fördern', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf#page=108', null, 'gemischt', '2026-09-30', false, true, null),
  (7167, 16, 17, 'ST', 'Kommunale Wärmeplanung flexibel und praxisnah gestalten', '{1603}', 7159, 1, 3, null, 'Kann die Planung für kleine Gemeinden beschleunigen; wenn Pläne gröber werden, wissen Eigentümer aber weniger genau, was kommt.', 'https://st.bsw-vg.de/wp-content/uploads/2026/04/BSW_Landtagswahlprogramm_SachsenAnhalt.pdf#page=34', null, 'offen', '2026-09-30', false, true, null),
  (7168, 16, 12, 'MV', 'Stadtwerke als zentrale Akteure der Wärmeplanung sichern und unterstützen', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf#page=17', null, 'gemischt', '2026-09-30', false, true, null),
  (7169, 16, 13, 'MV', 'Kommunen umfassend bei Wärmeplanung und Umsetzung unterstützen, Beratung ausbauen', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://gruene-mv.de/?wpdmdl=33772#page=8', null, 'gemischt', '2026-09-30', false, true, null),
  (7170, 16, 14, 'MV', 'Verpflichtende kommunale Wärmeplanung abschaffen, Freiwilligkeit', '{1603}', 7160, 1, 1, null, 'Nimmt Kommunen eine Pflicht ab und Eigentümern das Warten auf einen Plan, schafft aber keine Klarheit, ob ein Wärmenetz kommt. Die Pflicht steht im Bundesrecht; das Land kann nur sein Ausführungsgesetz ändern oder im Bundesrat werben.', 'https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf#page=65', null, 'offen', '2026-09-30', false, true, null),
  (7171, 16, 14, 'MV', 'Bürgschaftsprogramm für kleine Wärmenetze', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf#page=65', null, 'gemischt', '2026-09-30', false, true, null),
  (7172, 16, 15, 'MV', 'Tiefengeothermie als kommunale Wärmequelle fördern, Genehmigungen entbürokratisieren', '{1603}', null, 1, 2, null, 'Kann dort, wo die Geologie passt, Wärmenetze möglich machen und so Klarheit über die künftige Versorgung schaffen; Tiefengeothermie ist teuer, braucht Jahre und kommt nur für einen Teil der Gemeinden in Frage.', 'https://afd-vg.de/wp-content/uploads/2026/06/AfD-Regierungsprogramm-Mecklenburg-Vorpommern-2026.pdf#page=86', null, 'offen', '2026-09-30', false, true, null),
  (7173, 16, 11, 'BE', 'Kommunale Wärmeplanung als Orientierung fortführen, Fernwärme dekarbonisieren', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf#page=32', null, 'gemischt', '2026-09-30', false, true, null),
  (7174, 16, 12, 'BE', 'Fernwärme über die Wärmeplanung ausbauen, Förderdarlehen für neue Wärmenetze', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://library.fes.de/pdf-files/bibliothek/ltw-programme/SPD_Berlin_Wahlprogramm_20260521-v3-4_7942063.pdf#page=59', null, 'gemischt', '2026-09-30', false, true, null),
  (7175, 16, 13, 'BE', 'Wärmewende-Manager in den Bezirken, Förderinstrumente für die Umsetzung der Wärmeplanung', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf#page=13', null, 'gemischt', '2026-09-30', false, true, null),
  (7176, 16, 14, 'BE', 'Fern- und Nahwärmenetze im Stadtgebiet ausweiten', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf#page=87', null, 'gemischt', '2026-09-30', false, true, null),
  (7177, 16, 16, 'BE', 'Wärmeagentur, Beratung und Förderung, mehr Personal für die Bezirke', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf#page=195', null, 'gemischt', '2026-09-30', false, true, null),
  (7178, 16, 17, 'BE', 'Konsequenter Ausbau der Fernwärme, gesteuert über die kommunale Wärmeplanung', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf#page=46', null, 'gemischt', '2026-09-30', false, true, null),
  (7227, 16, 11, null, 'Investitionen in Klimatechnologien und Energieeffizienz steuerlich schneller absetzbar, auch für Vermieter', '{1604}', null, 1, 2, null, 'Macht den Heizungstausch auch für Vermieter steuerlich attraktiver, sodass mehr Mietwohnungen umgestellt werden können; ob Mieterinnen und Mieter dabei sparen, hängt von der Umlage ab, und die Maßnahme ist nicht auf Mietwohnungen zugeschnitten.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', null, 'offen', '2026-09-30', false, true, null),
  (8558, 16, 18, null, 'Finanzielle Unterstützung für klimaneutrale Maßnahmen bei Neubau und Sanierung.', '{1601}', 7034, 2, 3, null, 'Senkt die Investition, die viele Haushalte scheuen oder nicht aufbringen können, und setzt damit an den laut KfW größten Hindernissen an. Ob sie Haushalte mit wenig Geld erreicht, hängt von der Staffelung ab.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=96', 'https://www.kfw.de/PDF/Download-Center/Konzernthemen/Research/PDF-Dokumente-KfW-Energiewendebarometer/KfW-Energiewendebarometer-2026.pdf', 'gemischt', '2026-10-07', false, true, null),
  (8559, 16, 18, null, 'Kommunale Wärmeplanung dauerhaft finanzieren, Fernwärmeausbau über Duldungspflichten und Förderprogramme voranbringen.', '{1603}', 7038, 2, 2, null, 'Beschleunigt die Wärmepläne, auf die viele Eigentümer warten, und den Bau von Wärmenetzen; planen und bauen müssen die Kommunen, der Bund kann nur Geld und Beratung geben.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=68', 'https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/analysen-kompakt/2026/ak-09-2026.html', 'gemischt', '2026-10-07', false, true, null),
  (8605, 16, 18, 'BE', 'Ausgewiesene Wärmenetzgebiete zügig ans Fernwärmenetz anschließen und außerhalb davon Nahwärmelösungen schaffen, wo technisch und wirtschaftlich sinnvoll.', '{1603}', null, 2, 2, null, 'Schafft Klarheit, wo ein Wärmenetz kommt, und setzt den Wärmeplan um; Netzausbau ist teuer, dauert Jahre und rechnet sich nur bei hoher Anschlussquote, die im Bestand unsicher ist.', 'https://voltdeutschland.org/storage/assets-berlin/pdf/policy-wahlprogramm-2026/wahlprogramm-(last_edited_5-8-2026).pdf#page=92', 'https://www.roedl.com/insights/investitionsunsicherheit-ausbaugebiet-foerderung/', 'gemischt', '2026-10-08', false, true, 'blind'),
  (8606, 16, 18, 'ST', 'Zentrale Kompetenzstelle im Land, die Kommunen und Unternehmen bei Wärmeplanung und Wärmenetzprojekten berät und begleitet.', '{1603}', 7158, 2, 3, null, 'Beschleunigt die Wärmepläne und den Bau von Wärmenetzen, auf die viele Eigentümer warten; das Land kann Kommunen mit Geld und Fachleuten helfen.', 'https://voltdeutschland.org/storage/assets-sachsen-anhalt/pdf/landtagswahl-2026/wahlprogramm_volt_lv_lsa.pdf#page=69', null, 'gemischt', '2026-10-08', false, true, null);

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (7034, 16),
  (7035, 16),
  (7036, 16),
  (7037, 16),
  (7038, 16),
  (7039, 16),
  (7049, 16),
  (7051, 16),
  (7053, 16),
  (7055, 16),
  (7158, 16),
  (7159, 16),
  (7160, 16),
  (7172, 16),
  (7227, 16),
  (8605, 16);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (16, 11, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 12, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 13, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 14, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 15, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 16, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 17, null, 'massnahmen', null, '2026-09-30', true, null),
  (16, 11, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 12, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 13, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 14, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 15, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 16, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 17, 'ST', 'massnahmen', null, '2026-09-30', true, null),
  (16, 12, 'MV', 'massnahmen', null, '2026-09-30', true, null),
  (16, 13, 'MV', 'massnahmen', null, '2026-09-30', true, null),
  (16, 14, 'MV', 'massnahmen', null, '2026-09-30', true, null),
  (16, 15, 'MV', 'massnahmen', null, '2026-09-30', true, null),
  (16, 11, 'MV', 'keine', 'Landesprogramm durchsucht (Stichwörter Wärmeplanung, Wärmenetz, Nahwärme, Fernwärme, Wärmewende, Wärme): keine Maßnahme zur kommunalen Wärmeplanung oder zu Wärmenetzen.', '2026-09-30', true, null),
  (16, 16, 'MV', 'keine', 'Landesprogramm durchsucht (Stichwörter Wärmeplanung, Wärmenetz, Nahwärme, Fernwärme, Wärmewende, Wärme): keine Maßnahme zur kommunalen Wärmeplanung oder zu Wärmenetzen.', '2026-09-30', true, null),
  (16, 17, 'MV', 'keine', 'Landesprogramm durchsucht (Stichwörter Wärmeplanung, Wärmenetz, Nahwärme, Fernwärme, Wärmewende, Wärme): keine Maßnahme zur kommunalen Wärmeplanung oder zu Wärmenetzen.', '2026-09-30', true, null),
  (16, 11, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 12, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 13, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 14, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 16, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 17, 'BE', 'massnahmen', null, '2026-09-30', true, null),
  (16, 15, 'BE', 'keine', 'Landesprogramm durchsucht (Stichwörter Wärmeplanung, Wärmenetz, Nahwärme, Fernwärme, Wärmewende, Wärme): keine Maßnahme zur kommunalen Wärmeplanung oder zu Wärmenetzen.', '2026-09-30', true, null),
  (16, 18, null, 'massnahmen', null, '2026-10-07', true, '{1601,1602,1603,1604}'),
  (16, 18, 'BE', 'massnahmen', null, '2026-10-08', true, '{1603}'),
  (16, 18, 'MV', 'keine', 'Inhaltsverzeichnis, Kapitel Energie, Umwelt und Klimaschutz (PDF-S. 35-38) und Bauen und Wohnen (S. 59-61) gelesen; nichts zu kommunaler Wärmeplanung, Wärmenetz oder Fernwärme (Suchbegriffe ohne Treffer).', '2026-10-08', true, '{1603}'),
  (16, 18, 'ST', 'massnahmen', null, '2026-10-08', true, '{1603}');

commit;
