-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 3 „Energiepreise“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 3;
delete from public.abdeckung where thema_id = 3;
delete from public.pruef_einheiten where thema_id = 3;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (6703, 3, 'Netzentgelte mit Bundesmitteln senken oder deckeln', 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'belegt', null, 'bund', null, true, null),
  (6704, 3, 'Stromsteuer für alle auf das EU-Mindestmaß senken', 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'belegt', null, 'bund', null, true, null),
  (6705, 3, 'Klimageld: Einnahmen aus dem CO₂-Preis pro Kopf an die Haushalte zurückgeben', 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'belegt', null, 'bund', null, true, null),
  (6706, 3, 'CO₂-Preis auf Heizen abschaffen', 'Würde Gas- und Heizölpreise direkt senken; ab 2028 gilt aber der europäische Emissionshandel für Gebäude und Verkehr, den Deutschland nicht allein abschaffen kann.', 'belegt', null, 'bund', null, true, null),
  (6707, 3, 'Erneuerbare Energien und Speicher schneller ausbauen', 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'gemischt', null, 'bund', null, true, null),
  (6708, 3, 'Kohle- und Kernkraftwerke länger oder wieder betreiben', 'Mehr Kraftwerksleistung könnte die Börsenpreise in einzelnen Stunden senken; die abgeschalteten Kernkraftwerke sind weitgehend zurückgebaut, eine Wiederinbetriebnahme wäre teuer, langwierig und rechtlich neu zu regeln, und Kohlestrom wird durch den Emissionshandel teurer.', 'gemischt', null, 'bund', null, true, null),
  (6709, 3, 'Dynamische Stromtarife und intelligente Messsysteme', 'Haushalte, die Strom in günstigen Stunden nutzen können, sparen; für viele Haushalte ohne Wärmepumpe, E-Auto oder Batterie ist die Ersparnis gering.', 'gemischt', null, 'bund', null, true, null),
  (6828, 3, 'Wieder Gas aus Russland über Nord Stream beziehen', 'Mehr Pipelinegas könnte den Gaspreis senken, würde die Abhängigkeit von einem einzelnen Lieferland aber wieder erhöhen; die EU hat mit der Verordnung (EU) 2026/261 die Einfuhr von russischem Gas verboten (Pipelinegas spätestens ab Herbst 2027), eine Wiederaufnahme wäre EU-rechtswidrig.', 'gemischt', null, 'bund', null, true, null),
  (8465, 3, 'Ausbau von Fernwärmenetzen und kommunaler Wärmeplanung fördern (Bund)', 'Kann langfristig die Abhängigkeit von Gas- und Ölpreisen senken, wenn Netze erneuerbare Wärme oder Abwärme nutzen; Fernwärme wird heute aber noch stark mit Gas erzeugt, und in den Monopolnetzen sind die Preise oft hoch.', 'gemischt', 'https://www.vzbv.de/pressemitteilungen/teure-fernwaermepreise-verbraucherzentrale-fordert-preisdeckel', 'bund', null, true, 'blind')
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 3 and id not in (6703, 6704, 6705, 6706, 6707, 6708, 6709, 6828, 8465);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (6710, 3, 11, null, 'Netzentgelte senken und neu regeln', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'belegt', '2026-09-30', false, true, null),
  (6711, 3, 11, null, 'Stromsteuer für alle senken', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'belegt', '2026-09-30', false, true, null),
  (6712, 3, 11, null, 'Klimabonus als sozialer Ausgleich für den CO₂-Preis', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', null, 'belegt', '2026-09-30', false, true, null),
  (6713, 3, 11, null, 'Prüfen, ob die zuletzt abgeschalteten Kernkraftwerke wieder in Betrieb gehen können', '{304}', 6708, 1, 1, null, 'Mehr Kraftwerksleistung könnte die Börsenpreise in einzelnen Stunden senken; die abgeschalteten Kernkraftwerke sind weitgehend zurückgebaut, eine Wiederinbetriebnahme wäre teuer, langwierig und rechtlich neu zu regeln, und Kohlestrom wird durch den Emissionshandel teurer.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'gemischt', '2026-09-30', false, true, null),
  (6714, 3, 11, null, 'Smart Meter und Digitalisierung, damit Verbraucher flexibler auf den Strompreis reagieren können', '{304}', 6709, 1, 3, null, 'Haushalte, die Strom in günstigen Stunden nutzen können, sparen; für viele Haushalte ohne Wärmepumpe, E-Auto oder Batterie ist die Ersparnis gering.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'gemischt', '2026-09-30', false, true, null),
  (6715, 3, 11, null, 'Investitionen in Energieeffizienz steuerlich schneller absetzbar', '{305}', null, 1, 2, null, 'Macht Sanierungen und Heizungstausch für Eigentümer günstiger und senkt langfristig den Verbrauch; Mieterinnen und Mieter profitieren nur indirekt, und der Steuervorteil hilft Haushalten mit hohem Einkommen mehr.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=24', null, 'gemischt', '2026-09-30', false, true, null),
  (6716, 3, 12, null, 'Übertragungsnetzentgelte stabilisieren und auf 3 Cent pro Kilowattstunde deckeln', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=7', null, 'belegt', '2026-09-30', false, true, null),
  (6717, 3, 12, null, 'Klimageld, wenn ab 2027 der europäische CO₂-Preis gilt', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', null, 'belegt', '2026-09-30', false, true, null),
  (6718, 3, 12, null, 'Wind- und Solarenergie konsequent ausbauen, Speicher einbinden', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (6719, 3, 12, null, 'Soziales Wärmepumpen-Leasing für ärmere Haushalte', '{305}', null, 1, 2, null, 'Senkt die Hürde, von Gas oder Öl auf eine Wärmepumpe umzusteigen, für Haushalte ohne Ersparnisse; die meisten ärmeren Haushalte wohnen zur Miete und entscheiden nicht über die Heizung.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=34', null, 'offen', '2026-09-30', false, true, null),
  (6720, 3, 13, null, 'Netzentgelte für überregionale Stromleitungen aus dem Deutschlandfonds bezahlen', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=17', null, 'belegt', '2026-09-30', false, true, null),
  (6721, 3, 13, null, 'Stromsteuer auf das europäische Minimum senken', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=17', null, 'belegt', '2026-09-30', false, true, null),
  (6722, 3, 13, null, 'Sozial gestaffeltes Klimageld', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=40', null, 'belegt', '2026-09-30', false, true, null),
  (6723, 3, 13, null, 'Dynamische Stromtarife und flexible Netze', '{304}', 6709, 1, 3, null, 'Haushalte, die Strom in günstigen Stunden nutzen können, sparen; für viele Haushalte ohne Wärmepumpe, E-Auto oder Batterie ist die Ersparnis gering.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=42', null, 'gemischt', '2026-09-30', false, true, null),
  (6724, 3, 13, null, 'Strom in spätestens zehn Jahren vollständig erneuerbar', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=43', null, 'gemischt', '2026-09-30', false, true, null),
  (6725, 3, 13, null, 'Förderung von bis zu 70 Prozent für fossilfreie Heizungen', '{305}', null, 2, 3, null, 'Macht den Umstieg von Gas und Öl auf Wärmepumpen und Wärmenetze bezahlbarer und koppelt die Heizkosten von fossilen Preisen ab; die Förderung besteht bereits, der Umstieg dauert aber Jahre und hängt vom Strompreis ab.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=44', null, 'gemischt', '2026-09-30', false, true, null),
  (6726, 3, 14, null, 'Stromsteuer auf das EU-Mindestmaß senken, langfristig abschaffen', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=17', null, 'belegt', '2026-09-30', false, true, null),
  (6727, 3, 14, null, 'Netzausbau günstiger: Freileitungen statt Erdkabel, dynamische Netzentgelte', '{301}', null, 2, 2, null, 'Freileitungen sind deutlich billiger als Erdkabel und dämpfen so den Anstieg der Netzentgelte; für viele bereits geplante Leitungen wäre ein Wechsel aufwendig, und Freileitungen stoßen vor Ort häufiger auf Widerstand.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=17', null, 'gemischt', '2026-09-30', false, true, null),
  (6728, 3, 14, null, 'Klimadividende: Einnahmen aus dem Emissionshandel pro Kopf zurückzahlen', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=40', null, 'belegt', '2026-09-30', false, true, null),
  (6729, 3, 15, null, 'CO₂-Abgabe abschaffen', '{302,305}', 6706, 2, 1, null, 'Würde Gas- und Heizölpreise direkt senken; ab 2028 gilt aber der europäische Emissionshandel für Gebäude und Verkehr, den Deutschland nicht allein abschaffen kann.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'belegt', '2026-09-30', false, true, null),
  (6730, 3, 15, null, 'Energiesteuer reduzieren, Stromsteuer auf das Minimum senken', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'belegt', '2026-09-30', false, true, null),
  (6731, 3, 15, null, 'Kohlekraftwerke länger betreiben, Wiedereinstieg in die Kernenergie', '{304}', 6708, 1, 1, null, 'Mehr Kraftwerksleistung könnte die Börsenpreise in einzelnen Stunden senken; die abgeschalteten Kernkraftwerke sind weitgehend zurückgebaut, eine Wiederinbetriebnahme wäre teuer, langwierig und rechtlich neu zu regeln, und Kohlestrom wird durch den Emissionshandel teurer.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (6732, 3, 15, null, 'Nord-Stream-Pipelines reparieren und wieder in Betrieb nehmen', '{303}', 6828, 1, 0, null, 'Mehr Pipelinegas könnte den Gaspreis senken, würde die Abhängigkeit von einem einzelnen Lieferland aber wieder erhöhen; die EU hat mit der Verordnung (EU) 2026/261 die Einfuhr von russischem Gas verboten (Pipelinegas spätestens ab Herbst 2027), eine Wiederaufnahme wäre EU-rechtswidrig.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (6733, 3, 15, null, 'Ausbau der Windenergie stoppen, um höhere Netzentgelte zu verhindern', '{301}', null, 1, 3, null, 'Weniger neue Windparks bedeuten weniger neuen Netzausbau; zugleich fehlt günstiger Windstrom, sodass teurere Kraftwerke den Börsenpreis öfter bestimmen.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=14', null, 'gemischt', '2026-09-30', false, true, null),
  (6734, 3, 16, null, 'Soziales Klimageld von 320 Euro pro Person und Jahr', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=7', null, 'belegt', '2026-09-30', false, true, null),
  (6735, 3, 16, null, 'Neue Netzentgeltstruktur: Stromerzeuger und Stromhandel an den Transportkosten beteiligen', '{301}', null, 1, 1, null, 'Würde Haushalte bei den Netzentgelten entlasten; Entgelte für Erzeuger begrenzt das EU-Recht eng, und die Kosten würden zum Teil über höhere Strompreise wieder bei den Verbrauchern landen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', null, 'offen', '2026-09-30', false, true, null),
  (6736, 3, 16, null, 'Stromsteuer auf den europäischen Mindeststeuersatz senken', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', null, 'belegt', '2026-09-30', false, true, null),
  (6737, 3, 16, null, 'Schnellstmöglich auf erneuerbare Energien umsteigen', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=32', null, 'gemischt', '2026-09-30', false, true, null),
  (6738, 3, 16, null, 'Keine CO₂-Preise im Wärmebereich', '{302,305}', 6706, 2, 1, null, 'Würde Gas- und Heizölpreise direkt senken; ab 2028 gilt aber der europäische Emissionshandel für Gebäude und Verkehr, den Deutschland nicht allein abschaffen kann.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=34', null, 'belegt', '2026-09-30', false, true, null),
  (6739, 3, 16, null, 'Heizungstausch nach Einkommen gestaffelt fördern, bis zu 100 Prozent', '{305}', null, 2, 2, null, 'Ermöglicht auch Eigentümern mit wenig Geld den Umstieg von Gas und Öl und koppelt die Heizkosten von fossilen Preisen ab; das Programm soll 25 Milliarden Euro im Jahr kosten, die Finanzierung ist offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=34', null, 'gemischt', '2026-09-30', false, true, null),
  (6820, 3, 14, null, 'Wiederinbetriebnahme der vorhandenen Kernkraftwerke rechtlich ermöglichen', '{304}', 6708, 1, 1, null, 'Mehr Kraftwerksleistung könnte die Börsenpreise in einzelnen Stunden senken; die abgeschalteten Kernkraftwerke sind weitgehend zurückgebaut, eine Wiederinbetriebnahme wäre teuer, langwierig und rechtlich neu zu regeln, und Kohlestrom wird durch den Emissionshandel teurer.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=18', null, 'gemischt', '2026-09-30', false, true, null),
  (6821, 3, 14, null, 'Heimische Erdgasförderung ausbauen, auch mit Fracking', '{303}', null, 1, 2, null, 'Mehr heimisches Gas verringert die Importe etwas; der Gaspreis bildet sich aber auf dem europäischen Markt, und die möglichen Mengen sind im Vergleich zum Verbrauch klein. Genehmigungen, vor allem für Fracking, dauern lange.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=18', null, 'gemischt', '2026-09-30', false, true, null),
  (6822, 3, 11, null, 'Europäischen Energiebinnenmarkt stärken, internationale Energiepartnerschaften ausbauen', '{303}', null, 1, 3, null, 'Mehr Lieferländer machen Deutschland weniger anfällig für Preissprünge bei einzelnen Lieferanten; die Maßnahme bleibt allgemein und nennt keine konkreten Schritte.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=22', null, 'offen', '2026-09-30', false, true, null),
  (6823, 3, 13, null, 'Gasverbrauch schneller senken, Umstieg auf erneuerbare Energien', '{303}', null, 1, 2, null, 'Weniger Gasverbrauch verringert die Importabhängigkeit und damit das Risiko von Preissprüngen; die Wirkung auf die Rechnungen der Haushalte stellt sich erst über Jahre ein.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=43', null, 'gemischt', '2026-09-30', false, true, null),
  (6829, 3, 17, null, 'Netze aus öffentlichen Mitteln statt über den Strompreis finanzieren', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', null, 'belegt', '2026-09-30', false, true, null),
  (6830, 3, 17, null, 'Stromnetze verstaatlichen und Netzentgelte auf ein Minimum senken', '{301}', null, 1, 1, null, 'Ohne Renditen für private Netzbetreiber könnten die Netzentgelte etwas sinken; der Kauf der Netze würde viele Milliarden kosten, und der Ausbau bliebe trotzdem zu bezahlen.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', null, 'offen', '2026-09-30', false, true, null),
  (6831, 3, 17, null, 'CO₂-Preis abschaffen', '{302,305}', 6706, 2, 1, null, 'Würde Gas- und Heizölpreise direkt senken; ab 2028 gilt aber der europäische Emissionshandel für Gebäude und Verkehr, den Deutschland nicht allein abschaffen kann.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'belegt', '2026-09-30', false, true, null),
  (6832, 3, 17, null, 'Mit Russland über Gaslieferungen durch Nord Stream verhandeln', '{303}', 6828, 1, 0, null, 'Mehr Pipelinegas könnte den Gaspreis senken, würde die Abhängigkeit von einem einzelnen Lieferland aber wieder erhöhen; die EU hat mit der Verordnung (EU) 2026/261 die Einfuhr von russischem Gas verboten (Pipelinegas spätestens ab Herbst 2027), eine Wiederaufnahme wäre EU-rechtswidrig.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-30', false, true, null),
  (6833, 3, 17, null, 'Langfristige Lieferverträge für Energieimporte nach dem niedrigsten Preis', '{303}', null, 1, 2, null, 'Langfristige Verträge können Preisschwankungen dämpfen; sie binden aber auch an Preise, wenn der Markt fällt, und ein Kriterium nur nach dem Preis erhöht die Abhängigkeit von einzelnen Lieferländern.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-30', false, true, null),
  (6834, 3, 17, null, 'Neue Gaskraftwerke als Reserve für Dunkelflauten', '{304}', null, 1, 2, null, 'Mehr Reservekraftwerke können Preisspitzen in wind- und sonnenarmen Stunden dämpfen; sie senken den Durchschnittspreis kaum, weil gerade Gaskraftwerke den Preis dann setzen, und müssen über Umlagen oder Steuern bezahlt werden.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', null, 'gemischt', '2026-09-30', false, true, null),
  (6835, 3, 17, null, 'Repowering: alte Windanlagen durch neue ersetzen', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=11', null, 'gemischt', '2026-09-30', false, true, null),
  (6836, 3, 17, null, 'Einbau von Wärmepumpen fördern, ohne andere Heizungen zu benachteiligen', '{305}', null, 1, 3, null, 'Förderung erleichtert den Umstieg von Gas und Öl; ohne Vorgaben für neue Heizungen bleiben viele Haushalte bei fossilen Heizungen und damit von deren Preisen abhängig.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=10', null, 'gemischt', '2026-09-30', false, true, null),
  (8466, 3, 18, null, 'Teile der Netzentgelte aus dem Bundeshaushalt decken', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=53', null, 'belegt', '2026-10-07', false, true, null),
  (8467, 3, 18, null, 'Netzentgelte verursachungsgerecht gestalten, Investitionen nicht mehr allein darüber finanzieren', '{301}', 6703, 2, 2, null, 'Senkt einen großen Teil des Strompreises direkt und spürbar; die Kosten des Netzausbaus trägt dann der Bundeshaushalt, und die Finanzierung muss auf Dauer gesichert werden.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=67', null, 'belegt', '2026-10-07', false, true, null),
  (8468, 3, 18, null, 'Stromsteuer auf das europäische Minimum senken', '{302}', 6704, 2, 2, null, 'Senkt den Strompreis für Haushalte um gut 2 Cent je Kilowattstunde; kostet den Bundeshaushalt mehrere Milliarden Euro im Jahr.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=67', null, 'belegt', '2026-10-07', false, true, null),
  (8469, 3, 18, null, 'Einen Teil der CO₂-Einnahmen als direkte Zahlungen an die Menschen zurückgeben', '{302}', 6705, 1, 2, null, 'Gleicht höhere Heizkosten durch den CO₂-Preis vor allem für Haushalte mit geringem Einkommen aus, senkt die Preise selbst aber nicht; ein Auszahlungsweg muss erst aufgebaut werden.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=60', null, 'belegt', '2026-10-07', false, true, null),
  (8470, 3, 18, null, 'Strombedarf bis 2035 durchgehend vollständig aus erneuerbaren Energien decken', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=66', null, 'gemischt', '2026-10-07', false, true, null),
  (8471, 3, 18, null, 'Hemmnisse für Energiespeicher abbauen, damit Speicher wirtschaftlich attraktiv werden', '{304}', 6707, 2, 2, null, 'Mehr Wind- und Solarstrom verdrängt teure Gaskraftwerke an der Börse und senkt dort die Preise; zugleich kostet der dafür nötige Netzausbau Geld, das über die Netzentgelte bezahlt wird.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=66', null, 'gemischt', '2026-10-07', false, true, null),
  (8472, 3, 18, null, 'Fernwärmeausbau und kommunale Wärmeplanung durch Förderprogramme und Duldungspflichten fördern', '{305}', 8465, 1, 3, null, 'Kann langfristig die Abhängigkeit von Gas- und Ölpreisen senken, wenn Netze erneuerbare Wärme oder Abwärme nutzen; Fernwärme wird heute aber noch stark mit Gas erzeugt, und in den Monopolnetzen sind die Preise oft hoch.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=68', 'https://www.vzbv.de/pressemitteilungen/teure-fernwaermepreise-verbraucherzentrale-fordert-preisdeckel', 'gemischt', '2026-10-07', false, true, 'blind');

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (6703, 3),
  (6704, 3),
  (6705, 3),
  (6706, 3),
  (6707, 3),
  (6708, 3),
  (6709, 3),
  (6715, 3),
  (6719, 3),
  (6725, 3),
  (6727, 3),
  (6733, 3),
  (6735, 3),
  (6739, 3),
  (6821, 3),
  (6822, 3),
  (6823, 3),
  (6828, 3),
  (6830, 3),
  (6833, 3),
  (6834, 3),
  (6836, 3),
  (8465, 3);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (3, 11, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 12, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 13, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 14, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 15, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 16, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 17, null, 'massnahmen', null, '2026-09-30', true, null),
  (3, 18, null, 'massnahmen', null, '2026-10-07', true, '{301,302,303,304,305}');

commit;
