-- AUTOMATISCH ERZEUGT aus daten/ (npm run seed) – nicht von Hand bearbeiten.
-- Teil von supabase/seed.sql: Thema 7 „Rente“ – Instrumente, Maßnahmen, Prüfeinheiten, Abdeckung.
-- Nach 0-gemeinsam.sql ausführen. Mehrfach ausführbar, gespielte Runden bleiben erhalten.

begin;

delete from public.massnahmen where thema_id = 7;
delete from public.abdeckung where thema_id = 7;
delete from public.pruef_einheiten where thema_id = 7;

-- Lösungswege für die Forderungskarte (ohne Punkte). Upsert, damit gespeicherte Forderungen ihren Verweis behalten.
insert into public.instrumente (id, thema_id, name, begruendung, evidenz, beleg_studie_url, ebene, entspricht, ki_entwurf, entwurf_herkunft) values
  (6173, 7, 'Rentenniveau gesetzlich bei mindestens 48 Prozent halten', 'Eine Haltelinie verhindert, dass die Renten wegen des steigenden Verhältnisses von Rentnern zu Beitragszahlenden hinter den Löhnen zurückfallen; das Missverhältnis bleibt, die Kosten steigen über Beiträge oder Steuerzuschüsse. Per Bundesgesetz umsetzbar, die dauerhafte Finanzierung ist offen.', 'gemischt', null, 'bund', null, true, null),
  (6174, 7, 'Anreize, über das Rentenalter hinaus zu arbeiten', 'Mehr Weiterarbeit im Rentenalter bringt der Rentenversicherung etwas mehr Beiträge und Steuern; Studien erwarten nur kleine Beschäftigungseffekte, Steuerfreiheit kostet Einnahmen. Per Bundesgesetz umsetzbar.', 'gemischt', null, 'bund', null, true, null),
  (6175, 7, 'Pflicht zur Altersvorsorge für nicht abgesicherte Selbstständige', 'Viele Solo-Selbstständige sorgen kaum vor und sind im Alter häufiger arm; eine Vorsorgepflicht setzt direkt an dieser Lücke an, wirkt aber erst über Jahrzehnte, und Pflichtbeiträge belasten Selbstständige mit geringem Einkommen. Per Bundesgesetz umsetzbar.', 'gemischt', null, 'bund', null, true, null),
  (6176, 7, 'Beamte, Abgeordnete und weitere Gruppen in die gesetzliche Rente einbeziehen', 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'gemischt', null, 'bund', null, true, null),
  (6177, 7, 'Betriebsrenten stärker fördern und für kleine Betriebe erleichtern', 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'gemischt', null, 'bund', null, true, null),
  (6178, 7, 'Geförderte private Vorsorge neu ordnen (kostengünstige Depots, gezielte Förderung)', 'Kostengünstige, einfache Produkte und eine Förderung für kleine und mittlere Einkommen setzen an der Lücke bei der Zusatzvorsorge an; ob deutlich mehr Menschen vorsorgen, ist offen, solange die Teilnahme freiwillig bleibt. Per Bundesgesetz umsetzbar.', 'gemischt', null, 'bund', null, true, null),
  (6179, 7, 'Kapitalstock zur Stützung der gesetzlichen Rente', 'Ein Fonds kann den Beitragsanstieg dämpfen, wenn weniger Beitragszahlende auf mehr Rentner kommen; bei den vorgeschlagenen Größenordnungen ist der Effekt klein, die Erträge sind unsicher. Per Bundesgesetz umsetzbar, bei Kreditfinanzierung mit Haushaltsrisiken.', 'gemischt', null, 'bund', null, true, null),
  (6180, 7, 'Grundrente ausbauen, niedrige Rentenansprüche aufwerten', 'Eine stärkere Aufwertung niedriger Ansprüche setzt direkt an niedrigen Renten nach niedrigen Löhnen an; wer große Lücken im Erwerbsleben hat, profitiert oft nicht, die Kosten steigen. Per Bundesgesetz umsetzbar, die Finanzierung ist nicht geklärt.', 'gemischt', null, 'bund', null, true, null),
  (6181, 7, 'Mindestlohn auf mindestens 15 Euro anheben', 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'gemischt', null, 'bund', null, true, null),
  (6182, 7, 'Nicht beitragsgedeckte Leistungen aus dem Bundeshaushalt finanzieren', 'Verlagert Kosten von den Beitragszahlenden auf die Steuerzahlenden und entlastet die Beiträge; am Verhältnis von Beitragszahlenden zu Rentnern ändert es nichts. Es geht um zweistellige Milliardenbeträge im Jahr, deren Finanzierung offen ist.', 'gemischt', null, 'bund', null, true, null)
on conflict (id) do update set thema_id = excluded.thema_id, name = excluded.name, begruendung = excluded.begruendung,
  evidenz = excluded.evidenz, beleg_studie_url = excluded.beleg_studie_url, ebene = excluded.ebene,
  entspricht = excluded.entspricht, ki_entwurf = excluded.ki_entwurf, entwurf_herkunft = excluded.entwurf_herkunft;

delete from public.instrumente where thema_id = 7 and id not in (6173, 6174, 6175, 6176, 6177, 6178, 6179, 6180, 6181, 6182);

insert into public.massnahmen (id, thema_id, partei_id, land, beschreibung, ursachen_ids, instrument_id, wirksamkeit, umsetzbarkeit,
  rollen_modifikator, begruendung, beleg_programm_url, beleg_studie_url, evidenz, stand, geprueft, ki_entwurf, entwurf_herkunft) values
  (6183, 7, 11, null, 'Aktivrente: Arbeitslohn nach Erreichen der Regelaltersgrenze bis 2.000 Euro im Monat steuerfrei', '{701}', 6174, 1, 3, null, 'Mehr Weiterarbeit im Rentenalter bringt der Rentenversicherung etwas mehr Beiträge und Steuern; Studien erwarten nur kleine Beschäftigungseffekte, Steuerfreiheit kostet Einnahmen. Per Bundesgesetz umsetzbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=35', null, 'gemischt', '2026-09-29', false, true, null),
  (6184, 7, 11, null, 'Kleine und mittlere Arbeitgeber beim Abschluss von Betriebsrenten unterstützen', '{703}', 6177, 2, 3, null, 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=35', null, 'gemischt', '2026-09-29', false, true, null),
  (6185, 7, 11, null, 'Frühstart-Rente: 10 Euro im Monat vom 6. bis 18. Lebensjahr in ein kapitalgedecktes Altersvorsorgedepot', '{703}', null, 1, 3, null, '10 Euro im Monat ergeben bis zum Rentenalter nur einen kleinen Zusatzbetrag, und die Wirkung setzt erst in Jahrzehnten ein; das Depot kann aber den Einstieg in eigene Vorsorge erleichtern. Per Bundesgesetz umsetzbar, die Kosten sind überschaubar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=35', null, 'gemischt', '2026-09-29', false, true, null),
  (6186, 7, 11, null, 'Verbindliche Altersvorsorge für nicht ausreichend abgesicherte Selbstständige', '{702}', 6175, 2, 3, null, 'Viele Solo-Selbstständige sorgen kaum vor und sind im Alter häufiger arm; eine Vorsorgepflicht setzt direkt an dieser Lücke an, wirkt aber erst über Jahrzehnte, und Pflichtbeiträge belasten Selbstständige mit geringem Einkommen. Per Bundesgesetz umsetzbar.', 'https://www.cdu.de/app/uploads/2025/01/km_btw_2025_wahlprogramm_langfassung_ansicht.pdf#page=35', null, 'gemischt', '2026-09-29', false, true, null),
  (6187, 7, 12, null, 'Rentenniveau dauerhaft bei mindestens 48 Prozent sichern', '{701}', 6173, 1, 2, null, 'Eine Haltelinie verhindert, dass die Renten wegen des steigenden Verhältnisses von Rentnern zu Beitragszahlenden hinter den Löhnen zurückfallen; das Missverhältnis bleibt, die Kosten steigen über Beiträge oder Steuerzuschüsse. Per Bundesgesetz umsetzbar, die dauerhafte Finanzierung ist offen.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6188, 7, 12, null, 'Weiterarbeit nach Rentenbeginn: Arbeitgeberbeiträge an die Beschäftigten auszahlen', '{701}', 6174, 1, 3, null, 'Mehr Weiterarbeit im Rentenalter bringt der Rentenversicherung etwas mehr Beiträge und Steuern; Studien erwarten nur kleine Beschäftigungseffekte, Steuerfreiheit kostet Einnahmen. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6189, 7, 12, null, 'Langfristig alle Erwerbstätigen in die gesetzliche Rente einbeziehen', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6190, 7, 12, null, 'Zunächst alle Selbstständigen absichern', '{702}', 6175, 2, 3, null, 'Viele Solo-Selbstständige sorgen kaum vor und sind im Alter häufiger arm; eine Vorsorgepflicht setzt direkt an dieser Lücke an, wirkt aber erst über Jahrzehnte, und Pflichtbeiträge belasten Selbstständige mit geringem Einkommen. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6191, 7, 12, null, 'Steuerliche Förderung der Betriebsrente für Geringverdiener ausbauen', '{703}', 6177, 2, 3, null, 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6192, 7, 12, null, 'Förderung privater Vorsorge nur für Produkte mit gedeckelten Kosten, konzentriert auf kleine und mittlere Einkommen', '{703}', 6178, 2, 3, null, 'Kostengünstige, einfache Produkte und eine Förderung für kleine und mittlere Einkommen setzen an der Lücke bei der Zusatzvorsorge an; ob deutlich mehr Menschen vorsorgen, ist offen, solange die Teilnahme freiwillig bleibt. Per Bundesgesetz umsetzbar.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=25', null, 'gemischt', '2026-09-29', false, true, null),
  (6193, 7, 12, null, 'Mindestlohn spätestens 2026 auf 15 Euro', '{702}', 6181, 1, 3, null, 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf#page=23', null, 'gemischt', '2026-09-29', false, true, null),
  (6194, 7, 13, null, 'Rentenniveau bei mindestens 48 Prozent halten', '{701}', 6173, 1, 2, null, 'Eine Haltelinie verhindert, dass die Renten wegen des steigenden Verhältnisses von Rentnern zu Beitragszahlenden hinter den Löhnen zurückfallen; das Missverhältnis bleibt, die Kosten steigen über Beiträge oder Steuerzuschüsse. Per Bundesgesetz umsetzbar, die dauerhafte Finanzierung ist offen.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=97', null, 'gemischt', '2026-09-29', false, true, null),
  (6195, 7, 13, null, 'Grundrente zu einer Garantierente nach 30 Versicherungsjahren weiterentwickeln', '{702}', 6180, 2, 2, null, 'Eine stärkere Aufwertung niedriger Ansprüche setzt direkt an niedrigen Renten nach niedrigen Löhnen an; wer große Lücken im Erwerbsleben hat, profitiert oft nicht, die Kosten steigen. Per Bundesgesetz umsetzbar, die Finanzierung ist nicht geklärt.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=97', null, 'gemischt', '2026-09-29', false, true, null),
  (6196, 7, 13, null, 'Mehr Beitragszahlende durch höhere Erwerbstätigkeit von Frauen und qualifizierte Zuwanderung', '{701}', null, 2, 2, null, 'Eine höhere Erwerbstätigkeit, vor allem von Frauen, und Zuwanderung in Arbeit gelten in Studien als wichtigste Hebel gegen das sinkende Verhältnis von Beitragszahlenden zu Rentnern; das Programm nennt aber keine Größenordnung. Kitaausbau und Integration brauchen Länder, Kommunen und Zeit.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=97', null, 'belegt', '2026-09-29', false, true, null),
  (6197, 7, 13, null, 'Mindestlohn erneut anheben, Minijobs abbauen', '{702}', 6181, 1, 3, null, 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'gemischt', '2026-09-29', false, true, null),
  (6198, 7, 13, null, 'Gesetzliche Rente zur Bürgerversicherung: Abgeordnete und perspektivisch Beamte einbeziehen', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'gemischt', '2026-09-29', false, true, null),
  (6199, 7, 13, null, 'Nicht anderweitig abgesicherte Selbstständige einbeziehen', '{702}', 6175, 2, 3, null, 'Viele Solo-Selbstständige sorgen kaum vor und sind im Alter häufiger arm; eine Vorsorgepflicht setzt direkt an dieser Lücke an, wirkt aber erst über Jahrzehnte, und Pflichtbeiträge belasten Selbstständige mit geringem Einkommen. Per Bundesgesetz umsetzbar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'gemischt', '2026-09-29', false, true, null),
  (6200, 7, 13, null, 'Weiterarbeit neben dem Rentenbezug: Arbeitgeberbeiträge an die Beschäftigten auszahlen', '{701}', 6174, 1, 3, null, 'Mehr Weiterarbeit im Rentenalter bringt der Rentenversicherung etwas mehr Beiträge und Steuern; Studien erwarten nur kleine Beschäftigungseffekte, Steuerfreiheit kostet Einnahmen. Per Bundesgesetz umsetzbar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'gemischt', '2026-09-29', false, true, null),
  (6201, 7, 13, null, 'Ergänzende Kapitaldeckung in der gesetzlichen Rente aus Bundesmitteln (Bürger*innenfonds)', '{701}', 6179, 1, 2, null, 'Ein Fonds kann den Beitragsanstieg dämpfen, wenn weniger Beitragszahlende auf mehr Rentner kommen; bei den vorgeschlagenen Größenordnungen ist der Effekt klein, die Erträge sind unsicher. Per Bundesgesetz umsetzbar, bei Kreditfinanzierung mit Haushaltsrisiken.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'gemischt', '2026-09-29', false, true, null),
  (6202, 7, 13, null, 'Öffentlich verwalteter Bürger*innenfonds für die private Vorsorge mit Widerspruchslösung', '{703}', null, 2, 2, null, 'Automatische Teilnahme mit Widerspruchsrecht hat in Großbritannien und Neuseeland die Beteiligung an Zusatzvorsorge stark erhöht; wie hoch die Zusatzrente wird, hängt von den Beiträgen ab. Der öffentliche Fonds muss erst aufgebaut werden.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=98', null, 'belegt', '2026-09-29', false, true, null),
  (6203, 7, 13, null, 'Bürger*innenfonds auch für Betriebsrenten öffnen, vor allem für kleine und mittlere Unternehmen', '{703}', 6177, 2, 3, null, 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'https://cms.gruene.de/uploads/assets/20250318_Regierungsprogramm_DIGITAL_DINA5.pdf#page=99', null, 'gemischt', '2026-09-29', false, true, null),
  (6204, 7, 14, null, 'Flexibler Renteneintritt nach schwedischem Vorbild mit Zu- und Abschlägen', '{701}', null, 1, 3, null, 'Ein flexibler Renteneintritt mit fairen Zu- und Abschlägen kann längeres Arbeiten attraktiver machen; wie viele dadurch später in Rente gehen, ist unsicher, wer früher geht, bekommt weniger. Per Bundesgesetz umsetzbar.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6205, 7, 14, null, 'Gesetzliche Aktienrente: kleiner Teil der Rentenbeiträge in einen unabhängig verwalteten Fonds', '{701}', 6179, 1, 2, null, 'Ein Fonds kann den Beitragsanstieg dämpfen, wenn weniger Beitragszahlende auf mehr Rentner kommen; bei den vorgeschlagenen Größenordnungen ist der Effekt klein, die Erträge sind unsicher. Per Bundesgesetz umsetzbar, bei Kreditfinanzierung mit Haushaltsrisiken.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6206, 7, 14, null, 'Steuerlich gefördertes Altersvorsorgedepot für die private Vorsorge', '{703}', 6178, 2, 3, null, 'Kostengünstige, einfache Produkte und eine Förderung für kleine und mittlere Einkommen setzen an der Lücke bei der Zusatzvorsorge an; ob deutlich mehr Menschen vorsorgen, ist offen, solange die Teilnahme freiwillig bleibt. Per Bundesgesetz umsetzbar.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6207, 7, 14, null, 'Reine Beitragszusage allen Betrieben ermöglichen, vor allem Kleinstbetrieben', '{703}', 6177, 2, 3, null, 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'https://www.fdp.de/sites/default/files/2024-12/fdp-wahlprogramm_2025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6208, 7, 15, null, 'Verbeamtung nur für Hoheitsaufgaben, Politiker in die gesetzliche Rente', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=19', null, 'gemischt', '2026-09-29', false, true, null),
  (6209, 7, 15, null, 'Alle nicht beitragsgedeckten Leistungen aus dem Bundeshaushalt finanzieren', '{701}', 6182, 1, 1, null, 'Verlagert Kosten von den Beitragszahlenden auf die Steuerzahlenden und entlastet die Beiträge; am Verhältnis von Beitragszahlenden zu Rentnern ändert es nichts. Es geht um zweistellige Milliardenbeträge im Jahr, deren Finanzierung offen ist.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=19', null, 'gemischt', '2026-09-29', false, true, null),
  (6210, 7, 15, null, 'Elternschaft in der Rente höher bewerten', '{702}', null, 1, 2, null, 'Höhere Rentenansprüche für Eltern gleichen Lücken im Erwerbsleben durch Kindererziehung teilweise aus; das Programm nennt weder Umfang noch Finanzierung. Per Bundesgesetz umsetzbar, zuletzt bei der Mütterrente mit hohen Kosten.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=20', null, 'gemischt', '2026-09-29', false, true, null),
  (6211, 7, 15, null, 'Private und betriebliche Vorsorge mit Aktien, ETFs und Fonds systematisch steuerlich fördern', '{703}', 6178, 2, 3, null, 'Kostengünstige, einfache Produkte und eine Förderung für kleine und mittlere Einkommen setzen an der Lücke bei der Zusatzvorsorge an; ob deutlich mehr Menschen vorsorgen, ist offen, solange die Teilnahme freiwillig bleibt. Per Bundesgesetz umsetzbar.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=20', null, 'gemischt', '2026-09-29', false, true, null),
  (6212, 7, 15, null, 'Junior-Spardepot: 100 Euro im Monat aus Steuermitteln bis zum 18. Lebensjahr für jedes Kind mit deutscher Staatsangehörigkeit', '{703}', null, 2, 1, null, '100 Euro im Monat über 18 Jahre ergeben einen spürbaren Kapitalstock für das Alter; die Kosten von grob 15 Milliarden Euro im Jahr sind nicht gegenfinanziert, und die Beschränkung auf deutsche Kinder ist verfassungsrechtlich fraglich.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=20', null, 'offen', '2026-09-29', false, true, null),
  (6213, 7, 15, null, 'Zusätzlicher Steuerfreibetrag von 12.000 Euro für arbeitende Rentner', '{701}', 6174, 1, 3, null, 'Mehr Weiterarbeit im Rentenalter bringt der Rentenversicherung etwas mehr Beiträge und Steuern; Studien erwarten nur kleine Beschäftigungseffekte, Steuerfreiheit kostet Einnahmen. Per Bundesgesetz umsetzbar.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6214, 7, 15, null, 'Mehr Erwerbsanreize durch niedrigere Einkommensteuern und ein weniger attraktives Bürgergeld', '{701}', null, 1, 2, null, 'Stärkere Arbeitsanreize können die Zahl der Beitragszahlenden etwas erhöhen; wie stark Steuersenkungen und Kürzungen beim Bürgergeld die Beschäftigung steigern, ist in der Forschung umstritten. Steuersenkungen sind nicht gegenfinanziert.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6215, 7, 15, null, 'Willkommensprämie von 20.000 Euro für jedes neugeborene Kind', '{701}', null, 1, 1, null, 'Mehr Geburten würden das Verhältnis von Beitragszahlenden zu Rentnern erst nach rund zwei Jahrzehnten verbessern; ob Geldprämien die Geburtenrate dauerhaft erhöhen, ist umstritten. Die Kosten von rund 13 Milliarden Euro im Jahr sind nicht gegenfinanziert.', 'https://www.afd.de/wp-content/uploads/2025/02/AfD_Bundestagswahlprogramm2025_web.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6216, 7, 16, null, 'Solidarische Erwerbstätigenversicherung für alle mit Erwerbseinkommen', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6217, 7, 16, null, 'Rentenniveau auf 53 Prozent anheben', '{701}', null, 1, 1, null, 'Ein höheres Rentenniveau erhöht die Renten aller, gleicht aber nur die Folgen des steigenden Verhältnisses von Rentnern zu Beitragszahlenden aus; die Mehrkosten von jährlich deutlich über 30 Milliarden Euro sind nicht geklärt.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6218, 7, 16, null, 'Niedrige Rentenansprüche von Geringverdienenden, Erwerbslosen, Erziehenden und Pflegenden aufwerten', '{702}', 6180, 2, 2, null, 'Eine stärkere Aufwertung niedriger Ansprüche setzt direkt an niedrigen Renten nach niedrigen Löhnen an; wer große Lücken im Erwerbsleben hat, profitiert oft nicht, die Kosten steigen. Per Bundesgesetz umsetzbar, die Finanzierung ist nicht geklärt.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6219, 7, 16, null, 'Versicherungsfremde Leistungen nicht mehr aus Beiträgen finanzieren', '{701}', 6182, 1, 1, null, 'Verlagert Kosten von den Beitragszahlenden auf die Steuerzahlenden und entlastet die Beiträge; am Verhältnis von Beitragszahlenden zu Rentnern ändert es nichts. Es geht um zweistellige Milliardenbeträge im Jahr, deren Finanzierung offen ist.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6220, 7, 16, null, 'Solidarische Mindestrente bis zur Armutsrisikogrenze (rund 1.400 Euro)', '{702}', null, 2, 1, null, 'Ein Zuschlag bis zur Armutsrisikogrenze beseitigt Altersarmut nach niedrigen Löhnen und Lücken direkt, setzt aber nicht an den Löhnen selbst an und kann den Anreiz zu eigener Vorsorge schwächen. Die Kosten wären hoch, die Finanzierung ist offen.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6221, 7, 16, null, 'Betriebsrenten mindestens zur Hälfte durch die Arbeitgeber finanzieren', '{703}', null, 1, 3, null, 'Ein Pflichtanteil der Arbeitgeber erhöht die Leistungen bestehender Betriebsrenten, bringt aber nicht mehr Betriebe dazu, überhaupt eine anzubieten, und könnte kleine Betriebe eher abschrecken. Per Bundesgesetz umsetzbar.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6222, 7, 16, null, 'Mindestlohn von mindestens 15 Euro, ab 2026 16 Euro', '{702}', 6181, 1, 3, null, 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'https://www.die-linke.de/fileadmin/user_upload/Wahlprogramm_Langfassung_Linke-BTW25_01.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6435, 7, 17, null, 'Alle Erwerbstätigen, auch Abgeordnete und Minister, zahlen in die gesetzliche Rente ein', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=23', null, 'gemischt', '2026-09-29', false, true, null),
  (6436, 7, 17, null, 'Alle Selbstständigen in die Sozialversicherungen einbeziehen', '{702}', 6175, 2, 3, null, 'Viele Solo-Selbstständige sorgen kaum vor und sind im Alter häufiger arm; eine Vorsorgepflicht setzt direkt an dieser Lücke an, wirkt aber erst über Jahrzehnte, und Pflichtbeiträge belasten Selbstständige mit geringem Einkommen. Per Bundesgesetz umsetzbar.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=15', null, 'gemischt', '2026-09-29', false, true, null),
  (6437, 7, 17, null, 'Mindestlohn sofort auf 15 Euro anheben', '{702}', 6181, 1, 3, null, 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=21', null, 'gemischt', '2026-09-29', false, true, null),
  (6438, 7, 17, null, 'Mindestrente von 1.500 Euro nach 40 Versicherungsjahren, gestaffelt nach Versicherungsjahren', '{702}', null, 2, 1, null, 'Eine Mindestrente hebt niedrige Renten nach langen Versicherungszeiten direkt an; wer große Lücken im Erwerbsleben hat, erreicht die Stufen oft nicht. Die Kosten wären hoch, die Finanzierung nennt das Programm nicht.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=22', null, 'gemischt', '2026-09-29', false, true, null),
  (6439, 7, 17, null, 'Leistungsniveau von mindestens 75 Prozent des früheren Nettoeinkommens', '{701}', null, 1, 1, null, 'Ein deutlich höheres Leistungsniveau erhöht die Renten aller, gleicht aber nur die Folgen des steigenden Verhältnisses von Rentnern zu Beitragszahlenden aus; die Mehrkosten wären sehr hoch und sind nicht geklärt.', 'https://bsw-vg.de/wp-content/themes/bsw/assets/downloads/BSW%20Wahlprogramm%202025.pdf#page=23', null, 'gemischt', '2026-09-29', false, true, null),
  (8498, 7, 18, null, 'Renteneintrittsalter an die durchschnittliche Lebenserwartung koppeln', '{701}', null, 2, 3, null, 'Simulationen zeigen, dass die Kopplung den Beitragsanstieg spürbar dämpft und die Beschäftigung erhöht; Menschen mit geringerer Lebenserwartung (oft Geringverdienende) verlieren überproportional Rentenjahre. Per Bundesgesetz ohne Mehrkosten umsetzbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=92', 'https://www.bundesbank.de/de/aufgaben/themen/monatsbericht-wie-rentenreformen-wirken-koennten--892950', 'belegt', '2026-10-07', false, true, 'blind'),
  (8499, 7, 18, null, 'Beamte, Selbstständige und Freischaffende schrittweise in die gesetzliche Rentenversicherung einbeziehen', '{701}', 6176, 1, 2, null, 'Mehr Einzahlende verbessern das Verhältnis zu den Rentnern zunächst, später entstehen aus den Beiträgen aber auch Ansprüche; für Beamte kostet der Übergang Bund und Länder anfangs viel Geld. Per Bundesgesetz möglich, mit langen Übergangszeiten.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=92', null, 'gemischt', '2026-10-07', false, true, null),
  (8500, 7, 18, null, 'Einkommen oberhalb der Armutsgrenze unabhängig von der Erwerbsbiografie garantieren, ergänzend zu Rentenansprüchen', '{702}', null, 2, 1, null, 'Eine Mindestsicherung über der Armutsgrenze unabhängig von der Biografie senkt Altersarmut, wie Länder mit Mindest- oder Grundrente zeigen; sie gleicht Folgen niedriger Löhne aus, ohne die Ursache zu ändern. Höhe offen, Kosten hoch, Finanzierung ungeklärt.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=92', 'https://www.diw.de/de/diw_01.c.824031.de/publikationen/diw_aktuell/2021_0072/mindestrente__absicherung_gegen_altersarmut_und_notwendiger_baustein_fuer_weitere_reformen.html', 'belegt', '2026-10-07', false, true, 'blind'),
  (8501, 7, 18, null, 'Care-Arbeit, Freiwilligendienste und gesellschaftlich wertvolle Aufgaben bei der Rentenberechnung stärker berücksichtigen', '{702}', null, 2, 2, null, 'Anrechnung von Sorgezeiten senkt nachweislich Altersarmut von Frauen; sie wirkt aber wenig zielgenau und ist teuer (Mütterrente rund 14 Mrd. Euro jährlich). Umfang hier unbestimmt, Finanzierung offen.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=92', 'https://www.diw.de/de/diw_01.c.909964.de/publikationen/wochenberichte/2024_31_1/abschaffung_der_muetterrente_wuerde_altersarmut_erhoehen.html', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8502, 7, 18, null, 'Mindestlohn auf 60 % des Medianbruttolohns anheben und regelmäßig anpassen', '{702}', 6181, 1, 3, null, 'Ein höherer Mindestlohn erhöht die Rentenansprüche von Geringverdienenden; auch mit 15 Euro liegt die Rente nach Lücken im Erwerbsleben oft nahe der Grundsicherung. Per Bundesgesetz umsetzbar, bisher entscheidet die Mindestlohnkommission.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=89', null, 'gemischt', '2026-10-07', false, true, null),
  (8503, 7, 18, null, 'Geringfügig Beschäftigte in die Sozialversicherung einbinden', '{702}', null, 1, 3, null, 'Volle Versicherungspflicht schließt Lücken bei Minijobs, die meist von der Rentenpflicht befreit sind; die Ansprüche aus kleinen Verdiensten bleiben aber gering. Per Bundesgesetz umsetzbar, eine Expertenkommission empfiehlt es.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=89', 'https://www.bertelsmann-stiftung.de/de/presse/pressemitteilungen/pressemitteilung/pid/reformen-bei-minijobs-und-ehegattensplitting-koennten-60000-neue-vollzeitstellen-schaffen', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8504, 7, 18, null, 'Staatlich gefördertes Renten-Depot zur Geburt mit Startbudget und jährlichen Staatseinzahlungen bis zur Volljährigkeit', '{703}', null, 2, 2, null, 'Ein staatlich befülltes Depot ab Geburt erreicht alle Kinder, auch aus armen Familien, und baut über Jahrzehnte Vermögen auf; britische Erfahrungen zeigen kleine Effekte auf das Sparverhalten. Wirkt erst sehr spät, rund 2 Mrd. Euro jährlich ohne Finanzierung.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=93', 'https://publications.aston.ac.uk/id/eprint/45231', 'gemischt', '2026-10-07', false, true, 'blind'),
  (8505, 7, 18, null, 'Arbeitgeberbeiträge zur betrieblichen Altersvorsorge ins persönliche Depot', '{703}', 6177, 2, 3, null, 'Setzt direkt an der geringen Verbreitung von Betriebsrenten an; mehr Förderung und weniger Haftungsrisiken haben die Verbreitung bisher aber nur langsam erhöht, vor allem in kleinen Betrieben und bei Geringverdienenden. Per Bundesgesetz umsetzbar.', 'https://voltdeutschland.org/storage/assets-btw25/volt-programm-bundestagswahl-2025.pdf#page=93', null, 'gemischt', '2026-10-07', false, true, null);

select setval(pg_get_serial_sequence('public.massnahmen', 'id'), (select max(id) from public.massnahmen));

-- Was Prüfende je Thema bewerten (auch ungeprüfte Einträge): Instrumente und Maßnahmen ohne Instrument.
insert into public.pruef_einheiten (id, thema_id) values
  (6173, 7),
  (6174, 7),
  (6175, 7),
  (6176, 7),
  (6177, 7),
  (6178, 7),
  (6179, 7),
  (6180, 7),
  (6181, 7),
  (6182, 7),
  (6185, 7),
  (6196, 7),
  (6202, 7),
  (6204, 7),
  (6210, 7),
  (6212, 7),
  (6214, 7),
  (6215, 7),
  (6217, 7),
  (6220, 7),
  (6221, 7),
  (6438, 7),
  (6439, 7),
  (8498, 7),
  (8500, 7),
  (8501, 7),
  (8503, 7),
  (8504, 7);

insert into public.abdeckung (thema_id, partei_id, land, art, begruendung, stand, ki_entwurf, durchsucht_fuer) values
  (7, 11, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 12, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 13, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 14, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 15, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 16, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 17, null, 'massnahmen', null, '2026-09-29', true, null),
  (7, 18, null, 'massnahmen', null, '2026-10-07', true, '{701,702,703}');

commit;
